# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca gem bigdecimal`.


class BigDecimal < ::Numeric
  def %(_arg0); end
  def *(_arg0); end
  def **(y); end
  def +(_arg0); end
  def +@; end
  def -(_arg0); end
  def -@; end
  def /(_arg0); end
  def <(_arg0); end
  def <=(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def _decimal_shift(_arg0); end
  def _dump(*_arg0); end
  def abs; end
  def add(_arg0, _arg1); end
  def ceil(*_arg0); end
  def clone; end
  def coerce(_arg0); end
  def div(*_arg0); end
  def divmod(_arg0); end
  def dup; end
  def eql?(_arg0); end
  def exponent; end
  def finite?; end
  def fix; end
  def floor(*_arg0); end
  def frac; end
  def hash; end
  def infinite?; end
  def inspect; end
  def modulo(_arg0); end
  def mult(_arg0, _arg1); end
  def n_significant_digits; end
  def nan?; end
  def nonzero?; end
  def power(y, prec = T.unsafe(nil)); end
  def precision; end
  def precision_scale; end
  def quo(*_arg0); end
  def remainder(_arg0); end
  def round(*_arg0); end
  def scale; end
  def sign; end
  def split; end
  def sqrt(prec); end
  def sub(_arg0, _arg1); end
  def to_d; end
  def to_digits; end
  def to_f; end
  def to_i; end
  def to_int; end
  def to_r; end
  def to_s(format = T.unsafe(nil)); end
  def truncate(*_arg0); end
  def zero?; end

  class << self
    def _load(_arg0); end
    def double_fig; end
    def interpret_loosely(_arg0); end
    def limit(*_arg0); end
    def mode(*_arg0); end
    def save_exception_mode; end
    def save_limit; end
    def save_rounding_mode; end
  end
end

module BigDecimal::Internal
  class << self
    def coerce_to_bigdecimal(x, prec, method_name); end
    def coerce_validate_prec(prec, method_name, accept_zero: T.unsafe(nil)); end
    def infinity_computation_result; end
    def nan_computation_result; end
  end
end

BigDecimal::VERSION = T.let(T.unsafe(nil), String)

module BigMath
  private

  def _exp_taylor(x, prec); end
  def exp(x, prec); end
  def log(x, prec); end

  class << self
    def exp(x, prec); end
    def log(x, prec); end

    private

    def _exp_taylor(x, prec); end
  end
end

class Complex < ::Numeric
  def to_d(precision = T.unsafe(nil)); end
end

class Rational < ::Numeric
  def to_d(precision = T.unsafe(nil)); end
end
