# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nkf` gem.
# Please instead update this file by running `bin/tapioca gem nkf`.


module Kconv
  private

  def guess(str); end
  def iseuc(str); end
  def isjis(str); end
  def issjis(str); end
  def isutf8(str); end
  def kconv(str, to_enc, from_enc = T.unsafe(nil)); end
  def toeuc(str); end
  def tojis(str); end
  def tolocale(str); end
  def tosjis(str); end
  def toutf16(str); end
  def toutf32(str); end
  def toutf8(str); end

  class << self
    def guess(str); end
    def iseuc(str); end
    def isjis(str); end
    def issjis(str); end
    def isutf8(str); end
    def kconv(str, to_enc, from_enc = T.unsafe(nil)); end
    def toeuc(str); end
    def tojis(str); end
    def tolocale(str); end
    def tosjis(str); end
    def toutf16(str); end
    def toutf32(str); end
    def toutf8(str); end
  end
end

Kconv::AUTO = T.let(T.unsafe(nil), T.untyped)
Kconv::NOCONV = T.let(T.unsafe(nil), T.untyped)
Kconv::UNKNOWN = T.let(T.unsafe(nil), T.untyped)

class String
  include ::Comparable

  def iseuc; end
  def isjis; end
  def issjis; end
  def isutf8; end
  def kconv(to_enc, from_enc = T.unsafe(nil)); end
  def toeuc; end
  def tojis; end
  def tolocale; end
  def tosjis; end
  def toutf16; end
  def toutf32; end
  def toutf8; end
end
