# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `numbers_and_words` gem.
# Please instead update this file by running `bin/tapioca gem numbers_and_words`.


class Array
  include ::Enumerable

  def to_figures; end
  def to_words(options = T.unsafe(nil)); end
end

class Float < ::Numeric
  def to_words(options = T.unsafe(nil)); end
end

class Integer < ::Numeric
  def to_words(options = T.unsafe(nil)); end
end

module NumbersAndWords; end
module NumbersAndWords::ArrayExtensions; end

module NumbersAndWords::ArrayExtensions::Helpers
  def capacity_count; end
  def capacity_length; end
  def figures_array_in_capacity(capacity); end
  def figures_array_under_capacity(capacity); end
  def fraction_capacity; end
  def fraction_capacity_count; end
  def fraction_sub_capacity; end
  def hundreds; end
  def number_in_capacity(capacity); end
  def number_under_capacity(capacity); end
  def ones; end
  def only_ones; end
  def opaque?(capacity); end
  def ordinal_capacity; end
  def ordinal_index; end
  def round_hundred?; end
  def sub_capacity; end
  def teens; end
  def tens; end
  def tens_with_ones; end
end

NumbersAndWords::ArrayExtensions::Helpers::FIGURES_IN_CAPACITY = T.let(T.unsafe(nil), Integer)
NumbersAndWords::ArrayExtensions::Helpers::MICRO_CAPACITY_SHIFT = T.let(T.unsafe(nil), Integer)
NumbersAndWords::ArrayExtensions::Helpers::ONES_SHIFT = T.let(T.unsafe(nil), Integer)
NumbersAndWords::ArrayExtensions::Helpers::THOUSAND_CAPACITY = T.let(T.unsafe(nil), Integer)

class NumbersAndWords::FiguresArray < ::Array
  include ::NumbersAndWords::ArrayExtensions::Helpers

  def figures_array_in_capacity(capacity); end
  def local_language(&_arg0); end
  def reverse; end
  def to_words(options = T.unsafe(nil)); end
end

module NumbersAndWords::I18n
  private

  def files(directory, ext); end
  def language_class_name; end
  def languages; end
  def local_language(locale = T.unsafe(nil)); end
  def locale_files; end

  class << self
    def files(directory, ext); end
    def language_class_name; end
    def languages; end
    def local_language(locale = T.unsafe(nil)); end
    def locale_files; end
  end
end

module NumbersAndWords::I18n::Initialization
  private

  def init; end

  class << self
    def init; end
  end
end

module NumbersAndWords::I18n::Pluralization
  private

  def config_file; end
  def files; end
  def init; end
  def languages; end
  def plurals_files; end

  class << self
    def config_file; end
    def files; end
    def init; end
    def languages; end
    def plurals_files; end
  end
end

module NumbersAndWords::I18n::Plurals; end

module NumbersAndWords::I18n::Plurals::Cs
  private

  def few_conditions(number); end
  def many_conditions(number); end
  def one_conditions(number); end

  class << self
    def few_conditions(number); end
    def many_conditions(number); end
    def one_conditions(number); end
  end
end

NumbersAndWords::I18n::Plurals::Cs::RULE = T.let(T.unsafe(nil), Proc)

module NumbersAndWords::I18n::Plurals::Lt
  private

  def one_conditions(number); end
  def ones_conditions(number); end

  class << self
    def one_conditions(number); end
    def ones_conditions(number); end
  end
end

NumbersAndWords::I18n::Plurals::Lt::RULE = T.let(T.unsafe(nil), Proc)

module NumbersAndWords::I18n::Plurals::Lv
  private

  def one_conditions(number); end

  class << self
    def one_conditions(number); end
  end
end

NumbersAndWords::I18n::Plurals::Lv::RULE = T.let(T.unsafe(nil), Proc)

module NumbersAndWords::I18n::Plurals::Ru
  private

  def few_conditions(number); end
  def many_conditions(number); end
  def one_conditions(number); end

  class << self
    def few_conditions(number); end
    def many_conditions(number); end
    def one_conditions(number); end
  end
end

NumbersAndWords::I18n::Plurals::Ru::RULE = T.let(T.unsafe(nil), Proc)
module NumbersAndWords::I18n::Plurals::Ua; end
NumbersAndWords::I18n::Plurals::Ua::RULE = T.let(T.unsafe(nil), Proc)

module NumbersAndWords::Strategies
  class << self
    def array_joiner; end
    def figures_converter; end
  end
end

module NumbersAndWords::Strategies::ArrayJoiner; end

class NumbersAndWords::Strategies::ArrayJoiner::Base
  def initialize(elements, options = T.unsafe(nil)); end

  def elements; end
  def elements=(_arg0); end
  def language; end
  def language=(_arg0); end
  def options; end
  def options=(_arg0); end
  def run; end
  def translations; end
  def translations=(_arg0); end
end

module NumbersAndWords::Strategies::ArrayJoiner::Languages
  class << self
    def factory(strategy); end
  end
end

class NumbersAndWords::Strategies::ArrayJoiner::Languages::Base
  include ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Families::Base

  def initialize(strategy); end

  def elements; end
  def elements=(_arg0); end
  def join; end
  def options; end
  def options=(_arg0); end
  def strategy; end
  def strategy=(_arg0); end
  def strings; end
  def strings=(_arg0); end
  def translations; end
  def translations=(_arg0); end
end

class NumbersAndWords::Strategies::ArrayJoiner::Languages::Cs < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::En < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end

class NumbersAndWords::Strategies::ArrayJoiner::Languages::EnGb < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base
  def elements_logic; end
  def union_element; end
end

class NumbersAndWords::Strategies::ArrayJoiner::Languages::Es < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
module NumbersAndWords::Strategies::ArrayJoiner::Languages::Families; end

module NumbersAndWords::Strategies::ArrayJoiner::Languages::Families::Base
  def elements_logic; end
  def micro_separator; end
  def union_element; end
end

class NumbersAndWords::Strategies::ArrayJoiner::Languages::Fr < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::FrCh < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::Hu < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::Nl < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::PtBr < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::Ru < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::Ua < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
class NumbersAndWords::Strategies::ArrayJoiner::Languages::Vi < ::NumbersAndWords::Strategies::ArrayJoiner::Languages::Base; end
module NumbersAndWords::Strategies::FiguresConverter; end

class NumbersAndWords::Strategies::FiguresConverter::Base
  def initialize(figures, options = T.unsafe(nil)); end

  def decorator; end
  def decorator=(_arg0); end
  def figures; end
  def figures=(_arg0); end
  def language; end
  def language=(_arg0); end
  def options; end
  def options=(_arg0); end
  def run; end
  def translations; end
  def translations=(_arg0); end

  private

  def around(&_arg0); end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators
  class << self
    def factory(strategy, options); end

    private

    def decorator_class(method_name); end
    def decorator_class_name(method_name); end
    def enabled_decorator(options); end
  end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Base
  def initialize(strategy, options); end

  def run; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Cs::Base
  def run; end

  private

  def figures; end
  def integral_significance; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::En; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Base; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::EnGb; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::EnGb::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::EnGb::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Fractional
  def run; end

  private

  def fraction_to_digits; end
  def zero_length; end
end

NumbersAndWords::Strategies::FiguresConverter::Decorators::EnGb::Fractional::SHIFT_ZERO_LENGTH = T.let(T.unsafe(nil), Integer)
class NumbersAndWords::Strategies::FiguresConverter::Decorators::EnGb::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::En::Integral; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::Es; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Es::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Es::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Es::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Es::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Es::Base; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Base; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::FrCh; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::FrCh::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Base; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::FrCh::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Fractional; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::FrCh::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Fr::Integral; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Hu::Base; end
module NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Nl::Base
  def run; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::PtBr::Base
  def run; end

  private

  def figures; end
  def integral_significance; end
  def quantity; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Ru::Base
  def run; end

  private

  def figures; end
  def integral_significance; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua::Base
  def run; end

  private

  def figures; end
  def fraction_length; end
  def fraction_significance; end
  def full_fraction; end
  def zero_length; end
end

class NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Ua::Base
  def run; end

  private

  def figures; end
  def integral_significance; end
end

module NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi::Base < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Base; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi::Fractional < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi::Base; end
class NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi::Integral < ::NumbersAndWords::Strategies::FiguresConverter::Decorators::Vi::Base; end

module NumbersAndWords::Strategies::FiguresConverter::Languages
  class << self
    def factory(strategy); end
  end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Helpers
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Base

  def initialize(strategy); end

  def figures; end
  def figures=(_arg0); end
  def options; end
  def options=(_arg0); end
  def print_words; end
  def strategy; end
  def strategy=(_arg0); end
  def strings; end
  def strings=(_arg0); end
  def translations; end
  def translations=(_arg0); end
  def words; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Cs < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def gender; end
  def hundreds; end
  def megs(*args); end
  def ones; end
  def teens; end
  def tens; end
  def tens_with_ones; end
  def zero; end

  private

  def internal_options; end
  def maybe_ordinal; end
  def maybe_remove_zero; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Da < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def hundreds; end
  def megs; end
  def ones; end
  def print_words; end

  private

  def complex_part; end
  def gender; end
  def hundred?; end
  def one_hundred?; end
  def simple_part; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::De < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def complex_number_to_words; end
  def megs; end
  def ones; end
  def postfix; end
  def print_megs_words; end
  def print_words; end

  private

  def complex_part; end
  def print_megs; end
  def print_other; end
  def print_thousands; end
  def simple_part; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::En < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def hundreds; end
  def maybe_hyphen_separator; end
  def maybe_ordinal(type); end
  def maybe_remove_zero; end
  def maybe_union_after_hundreds(translations); end
  def megs; end
  def ones; end
  def strings_logic; end
  def teens; end
  def tens; end
  def tens_with_ones; end
  def zero; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::EnGb < ::NumbersAndWords::Strategies::FiguresConverter::Languages::En; end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Es < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def hundreds; end
  def megs; end
  def ones; end
  def tens_with_ones; end
  def zero; end

  private

  def gender; end
  def hundred_apocopated?; end
  def long_scale_thousand?; end
  def maybe_remove_zero; end
  def one_apocopated?; end
  def one_thousand?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Et < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def megs; end
end

module NumbersAndWords::Strategies::FiguresConverter::Languages::Families; end

module NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Base
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Helpers

  def capacity_iteration; end
  def complex_number_to_words; end
  def complex_tens; end
  def current_capacity; end
  def current_capacity=(_arg0); end
  def hundreds_number_to_words; end
  def number_without_capacity_to_words(capacity = T.unsafe(nil)); end
  def parent_figures; end
  def parent_figures=(_arg0); end
  def save_parent_figures; end
  def simple_number_to_words; end
  def strings_logic; end
  def words_in_capacity(capacity = T.unsafe(nil)); end
end

module NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Cyrillic
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Helpers
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Base

  def gender; end
  def megs(*args); end
  def ones(*args); end
  def tens_with_ones(*args); end
end

module NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Helpers
  def hundreds(*args); end
  def megs(*args); end
  def ones(*args); end
  def teens(*args); end
  def tens(*args); end
  def tens_with_ones(*args); end
  def translate(method_name, *args); end
  def zero(*args); end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Fr < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def hundreds; end
  def megs; end
  def tens; end

  private

  def one?; end
  def thousand?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::FrCh < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Fr; end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Hu < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def complex_number_to_words; end
  def greater_than_2000?; end
  def hundreds; end
  def inner_reverse_words; end
  def maybe_ordinal(type); end
  def megs; end
  def ones; end
  def print_words; end
  def simple_number_to_words; end
  def strings_logic; end
  def teens; end
  def tens; end
  def tens_with_ones; end
  def zero; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Hy < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base; end
class NumbersAndWords::Strategies::FiguresConverter::Languages::It < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Ka < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def hundreds; end
  def megs; end

  private

  def one?; end
  def thousand?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Kz < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Lt < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def megs; end

  private

  def one?; end
  def thousand?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Lv < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def megs; end
  def tens_with_ones; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Nl < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def hundreds_number_to_words; end
  def ones(*args); end
  def simple_number_to_words; end
  def tens_with_ones(*args); end
  def zero; end

  private

  def apply_tens_of_hundreds?; end
  def maybe_remove_zero; end
  def number_without_capacity_to_words; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Pt < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def hundreds; end
  def megs; end

  private

  def hundred?; end
  def one_hundred?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::PtBr < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end
  def complex_number_to_words; end
  def hundreds; end
  def megs; end
  def ones; end
  def teens; end
  def tens; end
  def tens_with_ones; end
  def words; end
  def zero; end

  private

  def gender; end
  def hundred?; end
  def internal_options; end
  def maybe_ordinal; end
  def maybe_remove_zero; end
  def one_hundred?; end
  def one_thousand?; end
  def opaque?; end
  def with_comma?; end
  def without_connector?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Ru < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Cyrillic
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Se < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Tr < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def capacity_iteration; end

  private

  def one?; end
  def thousand?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Ua < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  include ::NumbersAndWords::Strategies::FiguresConverter::Languages::Families::Cyrillic
end

class NumbersAndWords::Strategies::FiguresConverter::Languages::Vi < ::NumbersAndWords::Strategies::FiguresConverter::Languages::Base
  def billion_unit; end
  def fraction_length; end
  def fraction_number_zeros_leading; end
  def fractional?; end
  def fractional_with_zero_leading_string_logic; end
  def hundreds(options = T.unsafe(nil)); end
  def hundreds?; end
  def integral_string_logic; end
  def ones(options = T.unsafe(nil)); end
  def ones_union(options = T.unsafe(nil)); end
  def print_words; end
  def remove_billion_noise(value); end
  def strings_logic; end
end

module NumbersAndWords::Strategies::FiguresConverter::Options; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Base; end

class NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender
  def initialize(proxy, *_args); end

  def options; end
  def options=(_arg0); end
  def result; end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::Base::Ordinal
  def initialize(proxy, *_args); end

  def result; end

  private

  def active?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::Base::RemoveZero
  def initialize(proxy, *_args); end

  def options; end
  def options=(_arg0); end
  def result; end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
end

module NumbersAndWords::Strategies::FiguresConverter::Options::Cs; end

class NumbersAndWords::Strategies::FiguresConverter::Options::Cs::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender
  def result; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::Cs::Ordinal < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Ordinal; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Cs::RemoveZero < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::RemoveZero; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Da; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Da::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender; end
module NumbersAndWords::Strategies::FiguresConverter::Options::En; end

class NumbersAndWords::Strategies::FiguresConverter::Options::En::HundredsWithUnion
  def initialize(proxy, *_args); end

  def modify_or_leave(hundreds); end
  def options; end
  def options=(_arg0); end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
  def round_hundred?; end
  def translations; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Ordinal
  def result(type); end

  private

  def check_megs_numbers; end
  def check_simple_numbers; end
  def current_capacity; end
  def language_figures; end
  def megs_numbers_condition; end
  def simple_number_to_words; end
  def simple_numbers_condition; end
end

NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal::HUNDRED_TYPE = T.let(T.unsafe(nil), Symbol)
NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal::MEGS_TYPE = T.let(T.unsafe(nil), Symbol)
NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal::ZERO_TYPE = T.let(T.unsafe(nil), Symbol)

class NumbersAndWords::Strategies::FiguresConverter::Options::En::Pronounced
  def initialize(proxy, *_args); end

  def active?; end
  def handle_hundreds(language, figures); end
  def handle_thousands(language, figures); end
  def options; end
  def options=(_arg0); end
  def process(language, figures); end
  def strategy; end
  def strategy=(_arg0); end
  def tens_with_oh(language, figures); end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::En::RemoveHyphen
  def initialize(proxy, *_args); end

  def options; end
  def options=(_arg0); end
  def result; end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::En::RemoveZero < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::RemoveZero; end
module NumbersAndWords::Strategies::FiguresConverter::Options::EnGb; end
class NumbersAndWords::Strategies::FiguresConverter::Options::EnGb::HundredsWithUnion < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::HundredsWithUnion; end
class NumbersAndWords::Strategies::FiguresConverter::Options::EnGb::Ordinal < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal; end
class NumbersAndWords::Strategies::FiguresConverter::Options::EnGb::Pronounced < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::Pronounced; end
class NumbersAndWords::Strategies::FiguresConverter::Options::EnGb::RemoveHyphen < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::RemoveHyphen; end
class NumbersAndWords::Strategies::FiguresConverter::Options::EnGb::RemoveZero < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::RemoveZero; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Es; end

class NumbersAndWords::Strategies::FiguresConverter::Options::Es::Apocopated
  def initialize(proxy, *_args); end

  def options; end
  def options=(_arg0); end
  def result; end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::Es::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Es::RemoveZero < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::RemoveZero; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Hu; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Hu::Ordinal < ::NumbersAndWords::Strategies::FiguresConverter::Options::En::Ordinal; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Nl; end

class NumbersAndWords::Strategies::FiguresConverter::Options::Nl::TensOfHundreds
  def initialize(proxy, *_args); end

  def options; end
  def options=(_arg0); end
  def result; end
  def strategy; end
  def strategy=(_arg0); end

  private

  def active?; end
end

class NumbersAndWords::Strategies::FiguresConverter::Options::Proxy
  def initialize(strategy, options); end

  def method_missing(method_name, *args, &block); end
  def options; end
  def options=(_arg0); end
  def strategy; end
  def strategy=(_arg0); end

  private

  def module_name; end
  def proxy_class_name(method_name); end
  def respond_to_missing?(method_name, include_private: T.unsafe(nil)); end
end

module NumbersAndWords::Strategies::FiguresConverter::Options::PtBr; end
class NumbersAndWords::Strategies::FiguresConverter::Options::PtBr::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender; end
class NumbersAndWords::Strategies::FiguresConverter::Options::PtBr::Ordinal < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Ordinal; end
class NumbersAndWords::Strategies::FiguresConverter::Options::PtBr::RemoveZero < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::RemoveZero; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Ru; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Ru::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender; end
module NumbersAndWords::Strategies::FiguresConverter::Options::Ua; end
class NumbersAndWords::Strategies::FiguresConverter::Options::Ua::Gender < ::NumbersAndWords::Strategies::FiguresConverter::Options::Base::Gender; end

module NumbersAndWords::Translations
  class << self
    def factory; end
  end
end

class NumbersAndWords::Translations::Base
  def t(attribute, options = T.unsafe(nil)); end
end

NumbersAndWords::Translations::Base::I18N_NAMESPACE = T.let(T.unsafe(nil), Symbol)

class NumbersAndWords::Translations::Cs < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def integral(number, _options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def teens(numbers, options = T.unsafe(nil)); end
  def tens(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def zero(options = T.unsafe(nil)); end

  private

  def gender_to_use(options); end
  def ordinal?(options); end
end

class NumbersAndWords::Translations::Da < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base

  def hundreds(number, options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def tens(number, _options = T.unsafe(nil)); end
  def tens_with_ones(numbers, _options = T.unsafe(nil)); end
  def zero(_options = T.unsafe(nil)); end
end

NumbersAndWords::Translations::Da::DEFAULT_POSTFIX = T.let(T.unsafe(nil), T.untyped)

class NumbersAndWords::Translations::De < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base

  def hundreds(number, _options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def zero(_options = T.unsafe(nil)); end
end

NumbersAndWords::Translations::De::DEFAULT_POSTFIX = T.let(T.unsafe(nil), Symbol)

class NumbersAndWords::Translations::En < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance
end

class NumbersAndWords::Translations::EnGb < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance
end

class NumbersAndWords::Translations::Es < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def twenties_with_ones(numbers, options = T.unsafe(nil)); end
  def zero(_options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Et < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, _options = T.unsafe(nil)); end
end

module NumbersAndWords::Translations::Extensions; end

module NumbersAndWords::Translations::Extensions::FractionSignificance
  def micro(capacity); end
  def micro_prefix(capacity); end
  def micros(capacity, number = T.unsafe(nil)); end
end

module NumbersAndWords::Translations::Families; end

module NumbersAndWords::Translations::Families::Base
  def mega(capacity); end
  def megs(capacity, options = T.unsafe(nil)); end
  def micro_separator; end
  def teens(numbers, options = T.unsafe(nil)); end
  def tens(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def union; end
end

module NumbersAndWords::Translations::Families::Cyrillic
  include ::NumbersAndWords::Translations::Families::Base

  def hundreds(number, _options = T.unsafe(nil)); end
  def integral(number, _options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def zero(_options = T.unsafe(nil)); end
end

module NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Families::Base

  def hundreds(number, options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def zero(options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Fr < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def tens(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def tens_with_teens(numbers); end
end

NumbersAndWords::Translations::Fr::SPECIAL_TENS_CASE = T.let(T.unsafe(nil), Integer)

class NumbersAndWords::Translations::FrCh < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def tens(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Hu < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Hy < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, _options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::It < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, _options = T.unsafe(nil)); end
  def tens_with_ones(numbers, _options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Ka < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, _options = T.unsafe(nil)); end
  def vigesimal_range(number); end
end

NumbersAndWords::Translations::Ka::TENS_VIGESIMAL_RANGES = T.let(T.unsafe(nil), Array)

class NumbersAndWords::Translations::Kz < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
end

class NumbersAndWords::Translations::Lt < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, _options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Lv < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, _options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Nl < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, _options = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end

  private

  def union(units); end
end

class NumbersAndWords::Translations::Pt < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, _options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::PtBr < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def hundreds(number, options = T.unsafe(nil)); end
  def integral(number, _options = T.unsafe(nil)); end
  def megs(capacity, options = T.unsafe(nil)); end
  def micro_prefix(capacity, number); end
  def micros(capacity, number = T.unsafe(nil)); end
  def ones(number, options = T.unsafe(nil)); end
  def teens(number, options = T.unsafe(nil)); end
  def tens(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
  def zero(options = T.unsafe(nil)); end

  private

  def ordinal?(options); end
end

class NumbersAndWords::Translations::Ru < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Cyrillic
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance
end

class NumbersAndWords::Translations::Se < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def tens_with_ones(numbers, _options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Tr < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin

  def hundreds(number, options = T.unsafe(nil)); end
end

class NumbersAndWords::Translations::Ua < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Cyrillic
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance
end

class NumbersAndWords::Translations::Vi < ::NumbersAndWords::Translations::Base
  include ::NumbersAndWords::Translations::Families::Base
  include ::NumbersAndWords::Translations::Families::Latin
  include ::NumbersAndWords::Translations::Extensions::FractionSignificance

  def ones_of_tens(number, options = T.unsafe(nil)); end
  def ones_union(number, options = T.unsafe(nil)); end
  def tens_with_ones(numbers, options = T.unsafe(nil)); end
end

NumbersAndWords::VERSION = T.let(T.unsafe(nil), String)

class NumbersAndWords::WordsArray < ::Array
  def join(options = T.unsafe(nil)); end
  def local_language(&_arg0); end
end

module NumbersAndWords::Wrappers; end

class NumbersAndWords::Wrappers::Float
  def initialize(number); end

  def number; end
  def number=(_arg0); end
  def to_words(options = T.unsafe(nil)); end

  private

  def fractional_options; end
  def fractional_part; end
  def fractional_part_is_nil?; end
  def fractional_part_with(options); end
  def integral_options; end
  def integral_part; end
  def integral_part_with(options); end
  def options; end
  def options=(_arg0); end
  def parts; end
  def precision; end
end

NumbersAndWords::Wrappers::Float::ZERO_SYMBOL = T.let(T.unsafe(nil), String)

class NumbersAndWords::Wrappers::Integer
  def initialize(number); end

  def number; end
  def number=(_arg0); end
  def to_words(options = T.unsafe(nil)); end

  private

  def to_figures_array; end
end
