# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pdf-core` gem.
# Please instead update this file by running `bin/tapioca gem pdf-core`.


module PDF; end

module PDF::Core
  private

  def pdf_object(obj, in_content_stream = T.unsafe(nil)); end
  def real(num); end
  def real_params(array); end
  def string_to_hex(str); end
  def utf8_to_utf16(str); end

  class << self
    def pdf_object(obj, in_content_stream = T.unsafe(nil)); end
    def real(num); end
    def real_params(array); end
    def string_to_hex(str); end
    def utf8_to_utf16(str); end
  end
end

module PDF::Core::Annotations
  def annotate(options); end
  def link_annotation(rect, options = T.unsafe(nil)); end
  def text_annotation(rect, contents, options = T.unsafe(nil)); end

  private

  def sanitize_annotation_hash(options); end
end

class PDF::Core::ByteString < ::String; end

module PDF::Core::Destinations
  def add_dest(name, reference); end
  def dest_fit(dest_page = T.unsafe(nil)); end
  def dest_fit_bounds(dest_page = T.unsafe(nil)); end
  def dest_fit_bounds_horizontally(top, dest_page = T.unsafe(nil)); end
  def dest_fit_bounds_vertically(left, dest_page = T.unsafe(nil)); end
  def dest_fit_horizontally(top, dest_page = T.unsafe(nil)); end
  def dest_fit_rect(left, bottom, right, top, dest_page = T.unsafe(nil)); end
  def dest_fit_vertically(left, dest_page = T.unsafe(nil)); end
  def dest_xyz(left, top, zoom = T.unsafe(nil), dest_page = T.unsafe(nil)); end
  def dests; end
end

PDF::Core::Destinations::NAME_TREE_CHILDREN_LIMIT = T.let(T.unsafe(nil), Integer)

class PDF::Core::DocumentState
  def initialize(options); end

  def before_render_actions(_doc); end
  def before_render_callbacks; end
  def before_render_callbacks=(_arg0); end
  def compress; end
  def compress=(_arg0); end
  def encrypt; end
  def encrypt=(_arg0); end
  def encryption_key; end
  def encryption_key=(_arg0); end
  def insert_page(page, page_number); end
  def normalize_metadata(options); end
  def on_page_create_action(doc); end
  def on_page_create_callback; end
  def on_page_create_callback=(_arg0); end
  def page; end
  def page=(_arg0); end
  def page_count; end
  def pages; end
  def pages=(_arg0); end
  def populate_pages_from_store(document); end
  def render_body(output); end
  def skip_encoding; end
  def skip_encoding=(_arg0); end
  def store; end
  def store=(_arg0); end
  def trailer; end
  def trailer=(_arg0); end
  def version; end
  def version=(_arg0); end
end

PDF::Core::ESCAPED_NAME_CHARACTERS = T.let(T.unsafe(nil), Array)
module PDF::Core::Errors; end
class PDF::Core::Errors::EmptyGraphicStateStack < ::StandardError; end
class PDF::Core::Errors::FailedObjectConversion < ::StandardError; end
class PDF::Core::Errors::InvalidPageLayout < ::StandardError; end

class PDF::Core::FilterList
  def initialize; end

  def <<(filter); end
  def decode_params; end
  def each(&block); end
  def inspect; end
  def names; end
  def normalized; end
  def to_a; end
end

class PDF::Core::FilterList::NotFilter < ::StandardError
  def initialize(message = T.unsafe(nil), filter: T.unsafe(nil)); end
end

PDF::Core::FilterList::NotFilter::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)
PDF::Core::FilterList::NotFilter::MESSAGE_WITH_FILTER = T.let(T.unsafe(nil), String)
module PDF::Core::Filters; end

module PDF::Core::Filters::DCTDecode
  class << self
    def decode(stream, _params = T.unsafe(nil)); end
    def encode(stream, _params = T.unsafe(nil)); end
  end
end

module PDF::Core::Filters::FlateDecode
  class << self
    def decode(stream, _params = T.unsafe(nil)); end
    def encode(stream, _params = T.unsafe(nil)); end
  end
end

class PDF::Core::GraphicState
  def initialize(previous_state = T.unsafe(nil)); end

  def cap_style; end
  def cap_style=(_arg0); end
  def color_space; end
  def color_space=(_arg0); end
  def dash; end
  def dash=(_arg0); end
  def dash_setting; end
  def fill_color; end
  def fill_color=(_arg0); end
  def join_style; end
  def join_style=(_arg0); end
  def line_width; end
  def line_width=(_arg0); end
  def stroke_color; end
  def stroke_color=(_arg0); end

  private

  def initialize_copy(other); end
end

class PDF::Core::GraphicStateStack
  def initialize(previous_state = T.unsafe(nil)); end

  def current_state; end
  def empty?; end
  def present?; end
  def restore_graphic_state; end
  def save_graphic_state(graphic_state = T.unsafe(nil)); end
  def stack; end
  def stack=(_arg0); end
end

class PDF::Core::LiteralString < ::String; end
module PDF::Core::NameTree; end

class PDF::Core::NameTree::Node
  def initialize(document, limit, parent = T.unsafe(nil)); end

  def <<(value); end
  def >=(other); end
  def add(name, value); end
  def children; end
  def deep_copy; end
  def document; end
  def empty?; end
  def greatest; end
  def leaf?; end
  def least; end
  def limit; end
  def parent; end
  def parent=(_arg0); end
  def ref; end
  def ref=(_arg0); end
  def size; end
  def split!; end
  def to_hash; end

  protected

  def split(node); end

  private

  def insertion_point(value); end
  def new_node(parent = T.unsafe(nil)); end
  def split_children(node, left, right); end
end

class PDF::Core::NameTree::Value
  include ::Comparable

  def initialize(name, value); end

  def <=>(other); end
  def inspect; end
  def name; end
  def to_s; end
  def value; end
end

class PDF::Core::ObjectStore
  include ::Enumerable

  def initialize(opts = T.unsafe(nil)); end

  def <<(*args, &block); end
  def [](id); end
  def each; end
  def info; end
  def length; end
  def min_version; end
  def object_id_for_page(page); end
  def page_count; end
  def pages; end
  def push(*args, &block); end
  def ref(data, &block); end
  def root; end
  def size; end
end

class PDF::Core::OutlineItem
  def initialize(title, parent, options); end

  def closed; end
  def closed=(_arg0); end
  def count; end
  def count=(_arg0); end
  def dest; end
  def dest=(_arg0); end
  def first; end
  def first=(_arg0); end
  def last; end
  def last=(_arg0); end
  def next; end
  def next=(_arg0); end
  def parent; end
  def parent=(_arg0); end
  def prev; end
  def prev=(_arg0); end
  def title; end
  def title=(_arg0); end
  def to_hash; end
end

class PDF::Core::OutlineRoot
  def initialize; end

  def count; end
  def count=(_arg0); end
  def first; end
  def first=(_arg0); end
  def last; end
  def last=(_arg0); end
  def to_hash; end
end

class PDF::Core::Page
  def initialize(document, options = T.unsafe(nil)); end

  def art_box; end
  def art_indents; end
  def art_indents=(_arg0); end
  def bleed_box; end
  def bleeds; end
  def bleeds=(_arg0); end
  def content; end
  def content=(_arg0); end
  def crop_box; end
  def crops; end
  def crops=(_arg0); end
  def dictionary; end
  def dictionary=(_arg0); end
  def dimensions; end
  def document; end
  def document=(_arg0); end
  def ext_gstates; end
  def finalize; end
  def fonts; end
  def graphic_state; end
  def in_stamp_stream?; end
  def layout; end
  def margins; end
  def margins=(_arg0); end
  def resources; end
  def size; end
  def stack; end
  def stack=(_arg0); end
  def stamp_stream(dictionary); end
  def trim_box; end
  def trims; end
  def trims=(_arg0); end
  def xobjects; end

  private

  def inherited_dictionary_value(key, local_dict = T.unsafe(nil)); end
end

PDF::Core::Page::ZERO_INDENTS = T.let(T.unsafe(nil), Hash)
module PDF::Core::PageGeometry; end
PDF::Core::PageGeometry::SIZES = T.let(T.unsafe(nil), Hash)

class PDF::Core::Reference
  def initialize(id, data); end

  def <<(io); end
  def data; end
  def data=(_arg0); end
  def deep_copy(share = T.unsafe(nil)); end
  def gen; end
  def gen=(_arg0); end
  def identifier; end
  def identifier=(_arg0); end
  def object; end
  def offset; end
  def offset=(_arg0); end
  def replace(other_ref); end
  def stream; end
  def stream=(_arg0); end
  def to_s; end
end

class PDF::Core::Reference::CannotAttachStream < ::StandardError
  def initialize(message = T.unsafe(nil)); end
end

class PDF::Core::Renderer
  def initialize(state); end

  def add_content(str); end
  def before_render(&block); end
  def close_graphics_state; end
  def compression_enabled?; end
  def deref(obj); end
  def finalize_all_page_contents; end
  def go_to_page(page_number); end
  def graphic_stack; end
  def graphic_state; end
  def min_version(min); end
  def names; end
  def names?; end
  def on_page_create(&block); end
  def open_graphics_state; end
  def page_count; end
  def ref(data); end
  def ref!(data); end
  def render(output = T.unsafe(nil)); end
  def render_body(output); end
  def render_file(filename); end
  def render_header(output); end
  def render_trailer(output); end
  def render_xref(output); end
  def restore_graphics_state; end
  def save_graphics_state(graphic_state = T.unsafe(nil)); end
  def start_new_page(options = T.unsafe(nil)); end
  def state; end
end

class PDF::Core::Stream
  def initialize(io = T.unsafe(nil)); end

  def <<(io); end
  def compress!; end
  def compressed?; end
  def data; end
  def empty?; end
  def filtered_stream; end
  def filters; end
  def inspect; end
  def length; end
  def object; end
end

module PDF::Core::Text
  def add_text_content(text, x, y, options); end
  def character_spacing(amount = T.unsafe(nil)); end
  def default_kerning(boolean); end
  def default_kerning=(boolean); end
  def default_kerning?; end
  def default_leading(number = T.unsafe(nil)); end
  def default_leading=(number = T.unsafe(nil)); end
  def fallback_fonts(fallback_fonts = T.unsafe(nil)); end
  def fallback_fonts=(fallback_fonts = T.unsafe(nil)); end
  def forget_text_rendering_mode!; end
  def horizontal_text_scaling(amount = T.unsafe(nil)); end
  def process_text_options(options); end
  def skip_encoding; end
  def text_direction(direction = T.unsafe(nil)); end
  def text_direction=(direction = T.unsafe(nil)); end
  def text_rendering_mode(mode = T.unsafe(nil)); end
  def word_spacing(amount = T.unsafe(nil)); end
end

class PDF::Core::Text::BadFontFamily < ::StandardError
  def initialize(message = T.unsafe(nil)); end
end

PDF::Core::Text::MODES = T.let(T.unsafe(nil), Hash)
PDF::Core::Text::VALID_OPTIONS = T.let(T.unsafe(nil), Array)

module PDF::Core::Utils
  private

  def deep_clone(object); end

  class << self
    def deep_clone(object); end
  end
end
