# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prawn` gem.
# Please instead update this file by running `bin/tapioca gem prawn`.


class Arcfour
  def initialize(key); end

  def encrypt(string); end

  private

  def key_byte; end
end

module PDF; end

module PDF::Core
  private

  def encrypted_pdf_object(obj, key, id, gen, in_content_stream = T.unsafe(nil)); end

  class << self
    def encrypted_pdf_object(obj, key, id, gen, in_content_stream = T.unsafe(nil)); end
  end
end

class PDF::Core::Reference
  def encrypted_object(key); end
end

class PDF::Core::Stream
  def encrypted_object(key, id, gen); end
end

module Prawn
  private

  def debug; end
  def debug=(_arg0); end
  def verify_options(accepted, actual); end

  class << self
    def debug; end
    def debug=(_arg0); end
    def image_handler; end
    def verify_options(accepted, actual); end
  end
end

Prawn::BASEDIR = T.let(T.unsafe(nil), String)
Prawn::DATADIR = T.let(T.unsafe(nil), String)

class Prawn::Document
  include ::Prawn::Document::Internals
  include ::PDF::Core::Annotations
  include ::PDF::Core::Destinations
  include ::Prawn::Document::Security
  include ::PDF::Core::Text
  include ::Prawn::Text::Formatted
  include ::Prawn::Text
  include ::Prawn::Graphics::BlendMode
  include ::Prawn::Graphics::Color
  include ::Prawn::Graphics::Dash
  include ::Prawn::Graphics::CapStyle
  include ::Prawn::Graphics::JoinStyle
  include ::Prawn::Graphics::Transparency
  include ::Prawn::Graphics::Transformation
  include ::Prawn::Graphics::Patterns
  include ::Prawn::Graphics
  include ::Prawn::Images
  include ::Prawn::Stamp
  include ::Prawn::SoftMask
  include ::Prawn::TransformationStack

  def initialize(options = T.unsafe(nil), &block); end

  def bounding_box(point, *args, &block); end
  def bounds; end
  def bounds=(bounding_box); end
  def canvas(&block); end
  def column_box(*args, &block); end
  def cursor; end
  def define_grid(options = T.unsafe(nil)); end
  def delete_page(index); end
  def find_font(name, options = T.unsafe(nil)); end
  def float; end
  def font(name = T.unsafe(nil), options = T.unsafe(nil)); end
  def font_families; end
  def font_registry; end
  def font_size(points = T.unsafe(nil)); end
  def font_size=(size); end
  def go_to_page(page_number); end
  def grid(*args); end
  def group(*_arguments); end
  def indent(left, right = T.unsafe(nil), &block); end
  def initialize_first_page(options); end
  def margin_box; end
  def margin_box=(_arg0); end
  def margins; end
  def mask(*fields); end
  def move_cursor_to(new_y); end
  def move_down(amount); end
  def move_up(amount); end
  def number_pages(string, options = T.unsafe(nil)); end
  def outline; end
  def pad(y); end
  def pad_bottom(y); end
  def pad_top(y); end
  def page; end
  def page_count; end
  def page_match?(page_filter, page_number); end
  def page_number; end
  def page_number=(_arg0); end
  def reference_bounds; end
  def render(*arguments, &block); end
  def render_file(filename); end
  def repeat(page_filter, options = T.unsafe(nil), &block); end
  def repeaters; end
  def save_font; end
  def set_font(font, size = T.unsafe(nil)); end
  def span(width, options = T.unsafe(nil)); end
  def start_new_page(options = T.unsafe(nil)); end
  def state; end
  def state=(_arg0); end
  def text_formatter; end
  def text_formatter=(_arg0); end
  def transaction; end
  def width_of(string, options = T.unsafe(nil)); end
  def y; end
  def y=(new_y); end

  private

  def apply_margin_options(options); end
  def font_metric_cache; end
  def generate_margin_box; end
  def init_bounding_box(user_block, options = T.unsafe(nil)); end
  def init_column_box(user_block, options = T.unsafe(nil)); end
  def multi_box(box1, box2); end
  def single_box(rows, columns); end
  def use_graphic_settings(override_settings = T.unsafe(nil)); end
  def width_of_inline_formatted_string(string, options = T.unsafe(nil)); end
  def width_of_string(string, options = T.unsafe(nil)); end

  class << self
    def extensions; end
    def generate(filename, options = T.unsafe(nil), &block); end
    def inherited(base); end
  end
end

class Prawn::Document::BoundingBox
  def initialize(document, parent, point, options = T.unsafe(nil)); end

  def absolute_bottom; end
  def absolute_bottom_left; end
  def absolute_bottom_right; end
  def absolute_left; end
  def absolute_right; end
  def absolute_top; end
  def absolute_top_left; end
  def absolute_top_right; end
  def add_left_padding(left_padding); end
  def add_right_padding(right_padding); end
  def anchor; end
  def bottom; end
  def bottom_left; end
  def bottom_right; end
  def deep_copy; end
  def document; end
  def height; end
  def indent(left_padding, right_padding = T.unsafe(nil)); end
  def left; end
  def left_side; end
  def move_past_bottom; end
  def parent; end
  def reference_bounds; end
  def right; end
  def right_side; end
  def stretchy?; end
  def subtract_left_padding(left_padding); end
  def subtract_right_padding(right_padding); end
  def top; end
  def top_left; end
  def top_right; end
  def total_left_padding; end
  def total_right_padding; end
  def update_height; end
  def width; end

  class << self
    def restore_deep_copy(bounds, document); end
  end
end

class Prawn::Document::BoundingBox::NoReferenceBounds < ::StandardError
  def initialize(message = T.unsafe(nil)); end
end

class Prawn::Document::ColumnBox < ::Prawn::Document::BoundingBox
  def initialize(document, parent, point, options = T.unsafe(nil)); end

  def add_left_padding(left_padding); end
  def add_right_padding(right_padding); end
  def bare_column_width; end
  def left; end
  def left_side; end
  def move_past_bottom; end
  def right; end
  def right_side; end
  def subtract_left_padding(left_padding); end
  def subtract_right_padding(right_padding); end
  def width; end
  def width_of_column; end
end

class Prawn::Document::Grid
  def initialize(pdf, options = T.unsafe(nil)); end

  def column_gutter; end
  def column_width; end
  def columns; end
  def gutter; end
  def pdf; end
  def row_gutter; end
  def row_height; end
  def rows; end
  def show_all(color = T.unsafe(nil)); end

  private

  def apply_gutter(options); end
  def subdivide(total, num, gutter); end
end

class Prawn::Document::GridBox
  def initialize(pdf, rows, columns); end

  def bottom; end
  def bottom_left; end
  def bottom_right; end
  def bounding_box(&blk); end
  def gutter; end
  def height; end
  def left; end
  def name; end
  def pdf; end
  def right; end
  def show(grid_color = T.unsafe(nil)); end
  def top; end
  def top_left; end
  def top_right; end
  def total_height; end
  def width; end

  private

  def grid; end
end

module Prawn::Document::Internals
  extend ::Forwardable

  def add_content(*args, **_arg1, &block); end
  def compression_enabled?(*args, **_arg1, &block); end
  def deref(*args, **_arg1, &block); end
  def graphic_state(*args, **_arg1, &block); end
  def names(*args, **_arg1, &block); end
  def on_page_create(*args, **_arg1, &block); end
  def ref(*args, **_arg1, &block); end
  def ref!(*args, **_arg1, &block); end
  def renderer; end
  def restore_graphics_state; end
  def save_graphics_state(state = T.unsafe(nil), &block); end
end

class Prawn::Document::MultiBox
  def initialize(pdf, box1, box2); end

  def bottom; end
  def bottom_left; end
  def bottom_right; end
  def bounding_box(&blk); end
  def gutter; end
  def height; end
  def left; end
  def name; end
  def pdf; end
  def right; end
  def show(grid_color = T.unsafe(nil)); end
  def top; end
  def top_left; end
  def top_right; end
  def total_height; end
  def width; end

  private

  def bottom_box; end
  def left_box; end
  def right_box; end
  def top_box; end
end

module Prawn::Document::Security
  def encrypt_document(options = T.unsafe(nil)); end

  private

  def encryption_dictionary; end
  def owner_password_hash; end
  def pad_password(password); end
  def permissions=(perms = T.unsafe(nil)); end
  def permissions_value; end
  def user_encryption_key; end
  def user_password_hash; end

  class << self
    def encrypt_string(str, key, id, gen); end
  end
end

Prawn::Document::Security::FULL_PERMISSIONS = T.let(T.unsafe(nil), Integer)
Prawn::Document::Security::PASSWORD_PADDING = T.let(T.unsafe(nil), String)
Prawn::Document::Security::PERMISSIONS_BITS = T.let(T.unsafe(nil), Hash)
Prawn::Document::VALID_OPTIONS = T.let(T.unsafe(nil), Array)
module Prawn::Encoding; end
class Prawn::Encoding::WinAnsi; end
Prawn::Encoding::WinAnsi::CHARACTERS = T.let(T.unsafe(nil), Array)
module Prawn::Errors; end
class Prawn::Errors::BlockRequired < ::StandardError; end
class Prawn::Errors::CannotFit < ::StandardError; end
class Prawn::Errors::CannotGroup < ::StandardError; end
class Prawn::Errors::IncompatibleStringEncoding < ::StandardError; end
class Prawn::Errors::InvalidGraphicsPath < ::StandardError; end
class Prawn::Errors::InvalidJoinStyle < ::StandardError; end
class Prawn::Errors::InvalidName < ::StandardError; end
class Prawn::Errors::InvalidTableSpan < ::StandardError; end
class Prawn::Errors::NameTaken < ::StandardError; end
class Prawn::Errors::NotOnPage < ::StandardError; end
class Prawn::Errors::RequiredOption < ::StandardError; end
class Prawn::Errors::UndefinedObjectName < ::StandardError; end
class Prawn::Errors::UnknownFont < ::StandardError; end
class Prawn::Errors::UnknownOption < ::StandardError; end
class Prawn::Errors::UnknownOutlineTitle < ::StandardError; end
class Prawn::Errors::UnrecognizedTableContent < ::StandardError; end
class Prawn::Errors::UnsupportedImageType < ::StandardError; end
Prawn::FLOAT_PRECISION = T.let(T.unsafe(nil), Float)

class Prawn::Font
  def initialize(document, name, options = T.unsafe(nil)); end

  def add_to_current_page(subset); end
  def ascender; end
  def descender; end
  def eql?(other); end
  def family; end
  def hash; end
  def height; end
  def height_at(size); end
  def identifier_for(subset); end
  def inspect; end
  def line_gap; end
  def name; end
  def normalize_encoding(_string); end
  def normalize_encoding!(str); end
  def options; end

  protected

  def size; end

  private

  def generate_unique_id; end
  def key_is_unique?(test_key); end

  class << self
    def font_format(src, options); end
    def load(document, src, options = T.unsafe(nil)); end
  end
end

Prawn::Font::AFM = Prawn::Fonts::AFM
Prawn::Font::DFont = Prawn::Fonts::DFont
Prawn::Font::TTC = Prawn::Fonts::TTC
Prawn::Font::TTF = Prawn::Fonts::TTF

class Prawn::FontMetricCache
  def initialize(document); end

  def width_of(string, options); end
end

class Prawn::FontMetricCache::CacheEntry < ::Struct
  def font; end
  def font=(_); end
  def options; end
  def options=(_); end
  def string; end
  def string=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

module Prawn::Fonts; end

class Prawn::Fonts::AFM < ::Prawn::Font
  def initialize(document, name, options = T.unsafe(nil)); end

  def attributes; end
  def bbox; end
  def character_count(str); end
  def compute_width_of(string, options = T.unsafe(nil)); end
  def encode_text(text, options = T.unsafe(nil)); end
  def glyph_present?(char); end
  def has_kerning_data?; end
  def normalize_encoding(text); end
  def to_utf8(text); end
  def unicode?; end

  private

  def find_font(file); end
  def kern(string); end
  def parse_afm(file_name); end
  def parse_generic_afm_attribute(line, hash); end
  def register(_subset); end
  def symbolic?; end
  def unscaled_width_of(string); end

  class << self
    def font_data; end
    def hide_m17n_warning; end
    def hide_m17n_warning=(_arg0); end
    def metrics_path; end
  end
end

Prawn::Fonts::AFM::BUILT_INS = T.let(T.unsafe(nil), Array)

class Prawn::Fonts::DFont < ::Prawn::Fonts::TTF
  private

  def read_ttf_file; end

  class << self
    def font_count(file); end
    def named_fonts(file); end
  end
end

class Prawn::Fonts::OTF < ::Prawn::Fonts::TTF; end

class Prawn::Fonts::TTC < ::Prawn::Fonts::TTF
  private

  def font_option_to_index(file, option); end
  def read_ttf_file; end

  class << self
    def font_names(file); end
  end
end

class Prawn::Fonts::TTF < ::Prawn::Font
  def initialize(document, name, options = T.unsafe(nil)); end

  def basename; end
  def bbox; end
  def cap_height; end
  def character_count(str); end
  def compute_width_of(string, options = T.unsafe(nil)); end
  def encode_text(text, options = T.unsafe(nil)); end
  def family_class; end
  def glyph_present?(char); end
  def has_kerning_data?; end
  def italic_angle; end
  def normalize_encoding(text); end
  def pdf_flags; end
  def script?; end
  def serif?; end
  def stem_v; end
  def subsets; end
  def to_utf8(text); end
  def ttf; end
  def unicode?; end
  def x_height; end

  private

  def character_width_by_code(code); end
  def cmap; end
  def embed(reference, subset); end
  def hmtx; end
  def kern(string); end
  def kern_pairs_table; end
  def read_ttf_file; end
  def register(subset); end
  def scale_factor; end
end

class Prawn::Fonts::TTF::Error < ::StandardError
  def initialize(message = T.unsafe(nil), font: T.unsafe(nil)); end
end

Prawn::Fonts::TTF::Error::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)
Prawn::Fonts::TTF::Error::MESSAGE_WITH_FONT = T.let(T.unsafe(nil), String)
class Prawn::Fonts::TTF::NoPostscriptName < ::Prawn::Fonts::TTF::Error; end
Prawn::Fonts::TTF::NoPostscriptName::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)
Prawn::Fonts::TTF::NoPostscriptName::MESSAGE_WITH_FONT = T.let(T.unsafe(nil), String)
class Prawn::Fonts::TTF::NoUnicodeCMap < ::Prawn::Fonts::TTF::Error; end
Prawn::Fonts::TTF::NoUnicodeCMap::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)
Prawn::Fonts::TTF::NoUnicodeCMap::MESSAGE_WITH_FONT = T.let(T.unsafe(nil), String)
Prawn::Fonts::TTF::UNICODE_CMAP_TEMPLATE = T.let(T.unsafe(nil), String)

module Prawn::Graphics
  include ::Prawn::Graphics::BlendMode
  include ::Prawn::Graphics::Color
  include ::Prawn::Graphics::Dash
  include ::Prawn::Graphics::CapStyle
  include ::Prawn::Graphics::JoinStyle
  include ::Prawn::Graphics::Transparency
  include ::Prawn::Graphics::Transformation
  include ::Prawn::Graphics::Patterns

  def circle(center, radius); end
  def close_and_stroke; end
  def close_path; end
  def curve(origin, dest, options = T.unsafe(nil)); end
  def curve_to(dest, options = T.unsafe(nil)); end
  def ellipse(point, radius1, radius2 = T.unsafe(nil)); end
  def fill(options = T.unsafe(nil)); end
  def fill_and_stroke(options = T.unsafe(nil)); end
  def fill_and_stroke_circle(*args); end
  def fill_and_stroke_circle_at(*args); end
  def fill_and_stroke_curve(*args); end
  def fill_and_stroke_curve_to(*args); end
  def fill_and_stroke_ellipse(*args); end
  def fill_and_stroke_ellipse_at(*args); end
  def fill_and_stroke_horizontal_line(*args); end
  def fill_and_stroke_horizontal_rule(*args); end
  def fill_and_stroke_line(*args); end
  def fill_and_stroke_line_to(*args); end
  def fill_and_stroke_polygon(*args); end
  def fill_and_stroke_rectangle(*args); end
  def fill_and_stroke_rounded_polygon(*args); end
  def fill_and_stroke_rounded_rectangle(*args); end
  def fill_and_stroke_rounded_vertex(*args); end
  def fill_and_stroke_vertical_line(*args); end
  def fill_circle(*args); end
  def fill_circle_at(*args); end
  def fill_curve(*args); end
  def fill_curve_to(*args); end
  def fill_ellipse(*args); end
  def fill_ellipse_at(*args); end
  def fill_horizontal_line(*args); end
  def fill_horizontal_rule(*args); end
  def fill_line(*args); end
  def fill_line_to(*args); end
  def fill_polygon(*args); end
  def fill_rectangle(*args); end
  def fill_rounded_polygon(*args); end
  def fill_rounded_rectangle(*args); end
  def fill_rounded_vertex(*args); end
  def fill_vertical_line(*args); end
  def horizontal_line(x1, x2, options = T.unsafe(nil)); end
  def horizontal_rule; end
  def line(*points); end
  def line_to(*point); end
  def line_width(width = T.unsafe(nil)); end
  def line_width=(width); end
  def move_to(*point); end
  def polygon(*points); end
  def rectangle(point, width, height); end
  def rounded_polygon(radius, *points); end
  def rounded_rectangle(point, width, height, radius); end
  def rounded_vertex(radius, *points); end
  def stroke; end
  def stroke_axis(options = T.unsafe(nil)); end
  def stroke_bounds; end
  def stroke_circle(*args); end
  def stroke_circle_at(*args); end
  def stroke_curve(*args); end
  def stroke_curve_to(*args); end
  def stroke_ellipse(*args); end
  def stroke_ellipse_at(*args); end
  def stroke_horizontal_line(*args); end
  def stroke_horizontal_rule(*args); end
  def stroke_line(*args); end
  def stroke_line_to(*args); end
  def stroke_polygon(*args); end
  def stroke_rectangle(*args); end
  def stroke_rounded_polygon(*args); end
  def stroke_rounded_rectangle(*args); end
  def stroke_rounded_vertex(*args); end
  def stroke_vertical_line(*args); end
  def vertical_line(y1, y2, params); end

  private

  def current_line_width; end
  def current_line_width=(width); end
  def degree_to_rad(angle); end
  def map_to_absolute(*point); end
  def map_to_absolute!(point); end
  def point_on_line(distance_from_end, *points); end
  def write_line_width; end
end

module Prawn::Graphics::BlendMode
  def blend_mode(blend_mode = T.unsafe(nil)); end

  private

  def blend_mode_dictionary_name(blend_mode); end
  def blend_mode_dictionary_registry; end
end

module Prawn::Graphics::CapStyle
  def cap_style(style = T.unsafe(nil)); end
  def cap_style=(style = T.unsafe(nil)); end

  private

  def current_cap_style; end
  def current_cap_style=(style); end
  def write_stroke_cap_style; end
end

Prawn::Graphics::CapStyle::CAP_STYLES = T.let(T.unsafe(nil), Hash)

module Prawn::Graphics::Color
  def fill_color(*color); end
  def fill_color=(*color); end
  def stroke_color(*color); end
  def stroke_color=(*color); end

  private

  def color_space(color); end
  def color_to_s(color); end
  def color_type(color); end
  def current_color_space(type); end
  def current_fill_color; end
  def current_fill_color=(color); end
  def current_stroke_color; end
  def current_stroke_color=(color); end
  def hex2rgb(hex); end
  def normalize_color(color); end
  def process_color(*color); end
  def rgb2hex(rgb); end
  def set_color(type, color, options = T.unsafe(nil)); end
  def set_color_space(type, color_space); end
  def set_current_color_space(color_space, type); end
  def set_fill_color(color = T.unsafe(nil)); end
  def set_stroke_color(color = T.unsafe(nil)); end
  def update_colors; end
  def write_color(color, operator); end

  class << self
    def hex2rgb(hex); end
    def rgb2hex(rgb); end
  end
end

Prawn::Graphics::Color::COLOR_SPACES = T.let(T.unsafe(nil), Array)

module Prawn::Graphics::Dash
  def dash(length = T.unsafe(nil), options = T.unsafe(nil)); end
  def dash=(length = T.unsafe(nil), options = T.unsafe(nil)); end
  def dashed?; end
  def undash; end

  private

  def current_dash_state; end
  def current_dash_state=(dash_options); end
  def dash_setting; end
  def undashed_setting; end
  def write_stroke_dash; end
end

module Prawn::Graphics::JoinStyle
  def join_style(style = T.unsafe(nil)); end
  def join_style=(style = T.unsafe(nil)); end

  private

  def current_join_style; end
  def current_join_style=(style); end
  def write_stroke_join_style; end
end

Prawn::Graphics::JoinStyle::JOIN_STYLES = T.let(T.unsafe(nil), Hash)
Prawn::Graphics::KAPPA = T.let(T.unsafe(nil), Float)

module Prawn::Graphics::Patterns
  def fill_gradient(*args, **kwargs); end
  def stroke_gradient(*args, **kwargs); end

  private

  def create_gradient_pattern(gradient); end
  def gradient_coordinates(gradient); end
  def gradient_registry; end
  def gradient_registry_key(gradient); end
  def parse_gradient_arguments(*arguments, from: T.unsafe(nil), to: T.unsafe(nil), r1: T.unsafe(nil), r2: T.unsafe(nil), stops: T.unsafe(nil), apply_transformations: T.unsafe(nil)); end
  def set_gradient(type, *grad, **kwargs); end
end

class Prawn::Graphics::Patterns::Gradient < ::Struct
  def apply_transformations; end
  def apply_transformations=(_); end
  def from; end
  def from=(_); end
  def r1; end
  def r1=(_); end
  def r2; end
  def r2=(_); end
  def stops; end
  def stops=(_); end
  def to; end
  def to=(_); end
  def type; end
  def type=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Prawn::Graphics::Patterns::GradientStop < ::Struct
  def color; end
  def color=(_); end
  def position; end
  def position=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

module Prawn::Graphics::Transformation
  def rotate(angle, options = T.unsafe(nil), &block); end
  def scale(factor, options = T.unsafe(nil), &block); end
  def transformation_matrix(*matrix); end
  def translate(x, y, &block); end
end

module Prawn::Graphics::Transparency
  def transparent(opacity, stroke_opacity = T.unsafe(nil)); end

  private

  def next_opacity_dictionary_id; end
  def opacity_dictionary_name(opacity, stroke_opacity); end
  def opacity_dictionary_registry; end
end

class Prawn::ImageHandler
  def initialize; end

  def find(image_blob); end
  def register(handler); end
  def register!(handler); end
  def unregister(handler); end
end

module Prawn::Images
  def build_image_object(file); end
  def embed_image(pdf_obj, info, options); end
  def image(file, options = T.unsafe(nil)); end

  private

  def determine_y_with_page_flow(height); end
  def image_position(width, height, options); end
  def image_registry; end
  def next_image_id; end
  def overruns_page?(height); end
  def verify_and_read_image(io_or_path); end
end

class Prawn::Images::Image
  def calc_image_dimensions(options); end
end

class Prawn::Images::JPG < ::Prawn::Images::Image
  def initialize(data); end

  def bits; end
  def build_pdf_object(document); end
  def channels; end
  def height; end
  def scaled_height; end
  def scaled_height=(_arg0); end
  def scaled_width; end
  def scaled_width=(_arg0); end
  def width; end

  class << self
    def can_render?(image_blob); end
  end
end

class Prawn::Images::JPG::FormatError < ::StandardError; end
Prawn::Images::JPG::JPEG_SOF_BLOCKS = T.let(T.unsafe(nil), Array)

class Prawn::Images::PNG < ::Prawn::Images::Image
  def initialize(data); end

  def alpha_channel; end
  def alpha_channel?; end
  def bits; end
  def build_pdf_object(document); end
  def color_type; end
  def colors; end
  def compression_method; end
  def filter_method; end
  def height; end
  def img_data; end
  def interlace_method; end
  def min_pdf_version; end
  def palette; end
  def scaled_height; end
  def scaled_height=(_arg0); end
  def scaled_width; end
  def scaled_width=(_arg0); end
  def split_alpha_channel!; end
  def transparency; end
  def width; end

  private

  def generate_alpha_channel; end
  def split_image_data; end

  class << self
    def can_render?(image_blob); end
  end
end

module Prawn::Measurements
  def cm2mm(cm); end
  def cm2pt(cm); end
  def dm2mm(dm); end
  def dm2pt(dm); end
  def ft2in(ft); end
  def ft2pt(ft); end
  def in2pt(inch); end
  def m2mm(m); end
  def m2pt(m); end
  def mm2pt(mm); end
  def pt2mm(pt); end
  def pt2pt(pt); end
  def yd2in(yd); end
  def yd2pt(yd); end
end

class Prawn::Outline
  def initialize(document); end

  def add_subsection_to(title, position = T.unsafe(nil), &block); end
  def define(&block); end
  def document; end
  def document=(_arg0); end
  def insert_section_after(title, &block); end
  def items; end
  def items=(_arg0); end
  def page(options = T.unsafe(nil)); end
  def page_number; end
  def parent; end
  def parent=(_arg0); end
  def prev; end
  def prev=(_arg0); end
  def section(title, options = T.unsafe(nil), &block); end
  def update(&block); end

  private

  def add_outline_item(title, options, &block); end
  def adjust_relations(nxt, last); end
  def create_outline_item(title, options); end
  def establish_relations(outline_item); end
  def increase_count; end
  def insert_section(nxt, &block); end
  def reset_parent(outline_item); end
  def reset_root_positioning; end
  def root; end
  def set_variables_for_block(outline_item, block); end
end

class Prawn::Repeater
  def initialize(document, page_filter, dynamic = T.unsafe(nil), &block); end

  def match?(page_number); end
  def name; end
  def run(page_number); end

  class << self
    def count; end
    def count=(_arg0); end
  end
end

module Prawn::SoftMask
  def soft_mask(&block); end

  private

  def soft_mask_registry; end
end

module Prawn::Stamp
  def create_stamp(name, &block); end
  def stamp(name); end
  def stamp_at(name, point); end

  private

  def create_stamp_dictionary(name); end
  def freeze_stamp_graphics; end
  def next_stamp_dictionary_id; end
  def stamp_dictionary(name); end
  def stamp_dictionary_registry; end
  def update_annotation_references(annots); end
end

class Prawn::SynchronizedCache
  def initialize; end

  def [](key); end
  def []=(key, value); end
end

module Prawn::Text
  include ::PDF::Core::Text
  include ::Prawn::Text::Formatted

  def draw_text(text, options); end
  def draw_text!(text, options); end
  def formatted_text(array, options = T.unsafe(nil)); end
  def height_of(string, options = T.unsafe(nil)); end
  def height_of_formatted(array, options = T.unsafe(nil)); end
  def text(string, options = T.unsafe(nil)); end
  def text_box(string, options = T.unsafe(nil)); end

  private

  def draw_indented_formatted_line(string, options); end
  def draw_remaining_formatted_text_on_new_pages(remaining_text, options); end
  def fill_formatted_text_box(text, options); end
  def inspect_options_for_draw_text(options); end
  def inspect_options_for_text(options); end
  def merge_text_box_positioning_options(options); end
  def move_text_position(amount); end
  def process_final_gap_option(options); end
  def process_indent_paragraphs_option(options); end
end

class Prawn::Text::Box < ::Prawn::Text::Formatted::Box
  def initialize(string, options = T.unsafe(nil)); end

  def render(flags = T.unsafe(nil)); end
end

module Prawn::Text::Formatted
  def formatted_text_box(array, options = T.unsafe(nil)); end
end

class Prawn::Text::Formatted::Arranger
  def initialize(document, options = T.unsafe(nil)); end

  def apply_color_and_font_settings(fragment, &block); end
  def apply_font_settings(fragment = T.unsafe(nil), &block); end
  def consumed; end
  def consumed=(_arg0); end
  def current_format_state; end
  def finalize_line; end
  def finalized; end
  def finished?; end
  def font_style(styles); end
  def format_array=(array); end
  def fragments; end
  def initialize_line; end
  def line; end
  def line_width; end
  def max_ascender; end
  def max_descender; end
  def max_line_height; end
  def next_string; end
  def preview_next_string; end
  def repack_unretrieved; end
  def retrieve_fragment; end
  def space_count; end
  def unconsumed; end
  def update_last_string(printed, unprinted, normalized_soft_hyphen = T.unsafe(nil)); end

  private

  def apply_font_size(size, styles, &block); end
  def fragment_measurements=(fragment); end
  def line_measurement_maximums=(fragment); end
  def load_previous_format_state; end
  def omit_trailing_whitespace_from_line_width; end
  def subscript?(styles); end
  def superscript?(styles); end
end

class Prawn::Text::Formatted::Arranger::BadFontFamily < ::StandardError
  def initialize(message = T.unsafe(nil)); end
end

class Prawn::Text::Formatted::Arranger::NotFinalized < ::StandardError
  def initialize(message = T.unsafe(nil), method: T.unsafe(nil)); end
end

Prawn::Text::Formatted::Arranger::NotFinalized::DEFAULT_MESSAGE = T.let(T.unsafe(nil), String)
Prawn::Text::Formatted::Arranger::NotFinalized::MESSAGE_WITH_METHOD = T.let(T.unsafe(nil), String)

class Prawn::Text::Formatted::Box
  include ::Prawn::Text::Formatted::Wrap

  def initialize(formatted_text, options = T.unsafe(nil)); end

  def ascender; end
  def at; end
  def available_width; end
  def descender; end
  def draw_fragment(fragment, accumulated_width = T.unsafe(nil), line_width = T.unsafe(nil), word_spacing = T.unsafe(nil)); end
  def everything_printed?; end
  def height; end
  def leading; end
  def line_gap; end
  def line_height; end
  def nothing_printed?; end
  def render(flags = T.unsafe(nil)); end
  def text; end
  def valid_options; end

  private

  def analyze_glyphs_for_fallback_font_support(hash); end
  def default_height; end
  def draw_fragment_overlay_anchor(fragment); end
  def draw_fragment_overlay_link(fragment); end
  def draw_fragment_overlay_local(fragment); end
  def draw_fragment_overlay_styles(fragment); end
  def draw_fragment_overlays(fragment); end
  def draw_fragment_underlays(fragment); end
  def find_font_for_this_glyph(char, current_font, fallback_fonts); end
  def form_fragments_from_like_font_glyph_pairs(font_glyph_pairs, hash); end
  def move_baseline_down; end
  def normalize_encoding; end
  def normalized_text(flags); end
  def original_text; end
  def original_text=(formatted_text); end
  def process_fallback_fonts(formatted_text); end
  def process_options; end
  def process_vertical_alignment(text); end
  def render_rotated(text); end
  def shrink_to_fit(text); end

  class << self
    def extensions; end
    def inherited(base); end
  end
end

class Prawn::Text::Formatted::Fragment
  def initialize(text, format_state, document); end

  def absolute_bottom; end
  def absolute_bottom_left; end
  def absolute_bottom_right; end
  def absolute_bounding_box; end
  def absolute_left; end
  def absolute_right; end
  def absolute_top; end
  def absolute_top_left; end
  def absolute_top_right; end
  def anchor; end
  def ascender; end
  def ascender=(_arg0); end
  def baseline; end
  def baseline=(_arg0); end
  def bottom; end
  def bottom_left; end
  def bottom_right; end
  def bounding_box; end
  def callback_objects; end
  def character_spacing; end
  def color; end
  def default_direction=(direction); end
  def descender; end
  def descender=(_arg0); end
  def direction; end
  def font; end
  def format_state; end
  def height; end
  def include_trailing_white_space!; end
  def left; end
  def left=(_arg0); end
  def line_height; end
  def line_height=(_arg0); end
  def link; end
  def local; end
  def right; end
  def size; end
  def space_count; end
  def strikethrough_points; end
  def styles; end
  def subscript?; end
  def superscript?; end
  def text; end
  def top; end
  def top_left; end
  def top_right; end
  def underline_points; end
  def width; end
  def width=(_arg0); end
  def word_spacing; end
  def word_spacing=(_arg0); end
  def y_offset; end

  private

  def exclude_trailing_white_space?; end
  def normalized_soft_hyphen; end
  def process_soft_hyphens(string); end
  def process_text(text); end
  def soft_hyphens_need_processing?(string); end
  def strip_zero_width_spaces(string); end
end

class Prawn::Text::Formatted::LineWrap
  def paragraph_finished?; end
  def space_count; end
  def tokenize(fragment); end
  def width; end
  def wrap_line(options); end

  private

  def add_fragment_to_line(fragment); end
  def append_char(char); end
  def apply_font_settings_and_add_fragment_to_line(fragment); end
  def break_chars(encoding = T.unsafe(nil)); end
  def empty_line?(fragment); end
  def end_of_the_line_reached(segment); end
  def first_fragment_on_this_line?(fragment); end
  def fragment_begins_with_breakable?(fragment); end
  def fragment_finished(fragment); end
  def hyphen(_encoding = T.unsafe(nil)); end
  def initialize_line(options); end
  def line_empty?; end
  def line_finished?; end
  def next_string_newline?; end
  def previous_fragment_ended_with_breakable?; end
  def pull_preceding_fragment_to_join_this_one?(current_fragment); end
  def remember_this_fragment_for_backward_looking_ops; end
  def scan_pattern(encoding = T.unsafe(nil)); end
  def soft_hyphen(encoding = T.unsafe(nil)); end
  def update_line_status_based_on_last_output; end
  def update_output_based_on_last_fragment(fragment, normalized_soft_hyphen = T.unsafe(nil)); end
  def whitespace(encoding = T.unsafe(nil)); end
  def word_division_scan_pattern(encoding = T.unsafe(nil)); end
  def wrap_by_char(segment); end
  def zero_width_space(encoding = T.unsafe(nil)); end
end

class Prawn::Text::Formatted::Parser
  class << self
    def array_from_tokens(tokens); end
    def array_paragraphs(array); end
    def format(string, *_args); end
    def to_string(array); end
  end
end

Prawn::Text::Formatted::Parser::PARSER_REGEX = T.let(T.unsafe(nil), Regexp)

module Prawn::Text::Formatted::Wrap
  def initialize(_array, options); end

  def wrap(array); end

  private

  def enough_height_for_this_line?; end
  def format_and_draw_fragment(fragment, accumulated_width, line_width, word_spacing); end
  def initialize_wrap(array); end
  def print_line; end
  def word_spacing_for_this_line; end
end

Prawn::Text::NBSP = T.let(T.unsafe(nil), String)
Prawn::Text::SHY = T.let(T.unsafe(nil), String)
Prawn::Text::ZWSP = T.let(T.unsafe(nil), String)

module Prawn::TransformationStack
  def add_to_transformation_stack(a, b, c, d, e, f); end
  def current_transformation_matrix_with_translation(x = T.unsafe(nil), y = T.unsafe(nil)); end
  def restore_transformation_stack; end
  def save_transformation_stack; end
end

Prawn::VERSION = T.let(T.unsafe(nil), String)

module Prawn::View
  def document; end
  def method_missing(method_name, *arguments, &block); end
  def save_as(filename); end
  def update(&block); end

  private

  def respond_to_missing?(method_name, _include_all = T.unsafe(nil)); end
end
