# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `strings-ansi` gem.
# Please instead update this file by running `bin/tapioca gem strings-ansi`.


module Strings; end

module Strings::ANSI
  private

  def ansi?(string); end
  def only_ansi?(string); end
  def sanitize(string); end

  class << self
    def ansi?(string); end
    def only_ansi?(string); end
    def sanitize(string); end
  end
end

Strings::ANSI::ANSI_MATCHER = T.let(T.unsafe(nil), String)
Strings::ANSI::CSI = T.let(T.unsafe(nil), String)
Strings::ANSI::RESET = T.let(T.unsafe(nil), String)
Strings::ANSI::VERSION = T.let(T.unsafe(nil), String)
