# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-exit` gem.
# Please instead update this file by running `bin/tapioca gem tty-exit`.


module TTY; end

module TTY::Exit
  extend ::TTY::Exit

  def exit_code(name_or_code = T.unsafe(nil)); end
  def exit_codes; end
  def exit_message(name_or_code = T.unsafe(nil)); end
  def exit_messages; end
  def exit_reserved?(code); end
  def exit_success?(code); end
  def exit_valid?(code); end
  def exit_with(name_or_code = T.unsafe(nil), message = T.unsafe(nil), io: T.unsafe(nil)); end

  class << self
    def included(base); end
  end
end

TTY::Exit::CODE_TO_EXIT_MESSAGE = T.let(T.unsafe(nil), Hash)
module TTY::Exit::Code; end
TTY::Exit::Code::ABORT = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::ALARM = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::BASE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::BUS_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::CANNOT_EXECUTE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::CANT_CREATE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::COMMAND_NOT_FOUND = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::CONFIG_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::DATA_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::HANGUP = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::ILLEGAL_INSTRUCTION = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::INTERRUPT = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::INVALID_ARGUMENT = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::IO_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::KILL = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::MEMORY_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::NO_HOST = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::NO_INPUT = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::NO_PERM = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::NO_USER = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::PIPE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::PROTOCOL = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::QUIT = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SERVICE_UNAVAILABLE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SHELL_MISUSE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SIGNAL_BASE = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SOFTWARE_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SUCCESS = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SYSTEM_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::SYSTEM_FILE_MISSING = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::TEMP_FAIL = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::TRACE_TRAP = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::USAGE_ERROR = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::USER1 = T.let(T.unsafe(nil), Integer)
TTY::Exit::Code::USER2 = T.let(T.unsafe(nil), Integer)
class TTY::Exit::Error < ::StandardError; end
TTY::Exit::NAME_TO_EXIT_CODE = T.let(T.unsafe(nil), Hash)

module TTY::Exit::Registry
  class << self
    def exits; end
    def register_exit(name, code, message); end
  end
end

TTY::Exit::VERSION = T.let(T.unsafe(nil), String)
