# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-option` gem.
# Please instead update this file by running `bin/tapioca gem tty-option`.


module TTY; end

module TTY::Option
  include ::TTY::Option::Interface

  mixes_in_class_methods ::TTY::Option::DSL
  mixes_in_class_methods ::TTY::Option::Inheritance

  class << self
    def included(base); end
  end
end

class TTY::Option::AggregateErrors
  include ::Enumerable
  include ::TTY::Option::UsageWrapper
  extend ::Forwardable

  def initialize(errors = T.unsafe(nil)); end

  def add(error); end
  def any?(*args, **_arg1, &block); end
  def clear(*args, **_arg1, &block); end
  def each(&block); end
  def empty?(*args, **_arg1, &block); end
  def messages; end
  def size(*args, **_arg1, &block); end
  def summary(width: T.unsafe(nil), indent: T.unsafe(nil)); end
end

class TTY::Option::AmbiguousOption < ::TTY::Option::ParseError; end
class TTY::Option::ConfigurationError < ::TTY::Option::Error; end
module TTY::Option::Const; end
TTY::Option::Const::Undefined = T.let(T.unsafe(nil), Object)
class TTY::Option::ConversionAlreadyDefined < ::TTY::Option::Error; end
class TTY::Option::ConversionError < ::TTY::Option::Error; end

module TTY::Option::Conversions
  extend ::TTY::Option::Converter
end

TTY::Option::Conversions::FALSE_VALUES = T.let(T.unsafe(nil), Regexp)
TTY::Option::Conversions::TRUE_VALUES = T.let(T.unsafe(nil), Regexp)

module TTY::Option::Converter
  def [](name); end
  def contain?(name); end
  def conversions; end
  def convert(*names, &block); end
  def fetch(name); end
  def raise_unsupported_error(conv_name); end
end

module TTY::Option::DSL
  include ::TTY::Option::DSL::Arity
  include ::TTY::Option::DSL::Conversion
  include ::TTY::Option::Inflection
  extend ::Forwardable

  def argument(name, **settings, &block); end
  def banner(*args, **_arg1, &block); end
  def command(*args, **_arg1, &block); end
  def desc(*args, **_arg1, &block); end
  def env(name, **settings, &block); end
  def environment(name, **settings, &block); end
  def example(*args, **_arg1, &block); end
  def flag(name, **settings, &block); end
  def footer(*args, **_arg1, &block); end
  def header(*args, **_arg1, &block); end
  def ignore(*names); end
  def keyword(name, **settings, &block); end
  def no_command(*args, **_arg1, &block); end
  def opt(name, **settings, &block); end
  def option(name, **settings, &block); end
  def parameters; end
  def program(*args, **_arg1, &block); end
  def skip(*names); end
  def usage(**properties, &block); end
end

module TTY::Option::DSL::Arity
  def any; end
  def any_args; end
  def at_least(number); end
  def one; end
  def one_or_more; end
  def two; end
  def two_or_more; end
  def zero_or_more; end
end

module TTY::Option::DSL::Conversion
  def list_of(type); end
  def map_of(type); end
end

module TTY::Option::DeepDup
  class << self
    def deep_dup(object, cache = T.unsafe(nil)); end

    private

    def deep_dup_array(object, cache); end
    def deep_dup_hash(object, cache); end
  end
end

TTY::Option::DeepDup::NONDUPLICATABLE = T.let(T.unsafe(nil), Array)
class TTY::Option::Error < ::StandardError; end

class TTY::Option::ErrorAggregator
  include ::TTY::Option::Inflection

  def initialize(errors = T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end

  def call(error, message = T.unsafe(nil)); end
  def errors; end
end

class TTY::Option::Formatter
  include ::TTY::Option::UsageWrapper

  def initialize(parameters, usage, param_display: T.unsafe(nil), width: T.unsafe(nil), order: T.unsafe(nil), indent: T.unsafe(nil)); end

  def help; end
  def help_arguments; end
  def help_banner; end
  def help_description; end
  def help_environments; end
  def help_examples; end
  def help_footer; end
  def help_header; end
  def help_keywords; end
  def help_options; end

  private

  def find_longest_long_option; end
  def find_longest_parameter(params, &name_selector); end
  def find_longest_short_option; end
  def format_argument_usage(arg); end
  def format_arguments_usage; end
  def format_default(param); end
  def format_description; end
  def format_examples; end
  def format_keyword_usage(kwarg); end
  def format_keywords_usage; end
  def format_long_option(option, longest); end
  def format_multiline(lines, indent); end
  def format_option(option, longest_short, longest_long); end
  def format_options; end
  def format_parameter_description(param); end
  def format_parameter_usage(param, param_name); end
  def format_permitted(values); end
  def format_section(params, name_selector = T.unsafe(nil)); end
  def format_section_parameter(param, longest_param, name_selector); end
  def format_short_option(option, longest); end
  def format_usage; end
  def kwarg_param_display(kwarg, param_display = T.unsafe(nil)); end
  def parameter_default?(param); end
  def parameter_description?(param); end
  def short_and_long_option_separator(option); end

  class << self
    def help(parameters, usage, **config, &block); end
  end
end

TTY::Option::Formatter::BOOLEANS = T.let(T.unsafe(nil), Array)
TTY::Option::Formatter::DEFAULT_NAME_SELECTOR = T.let(T.unsafe(nil), Proc)
TTY::Option::Formatter::DEFAULT_ORDER = T.let(T.unsafe(nil), Proc)
TTY::Option::Formatter::DEFAULT_PARAM_DISPLAY = T.let(T.unsafe(nil), Proc)
TTY::Option::Formatter::DEFAULT_WIDTH = T.let(T.unsafe(nil), Integer)
TTY::Option::Formatter::DOUBLE_SPACE = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::ELLIPSIS = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::EMPTY = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::LIST_SEPARATOR = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::MAP_SEPARATOR = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::NEWLINE = T.let(T.unsafe(nil), String)
TTY::Option::Formatter::NOOP_PROC = T.let(T.unsafe(nil), Proc)
TTY::Option::Formatter::SPACE = T.let(T.unsafe(nil), String)

module TTY::Option::Inflection
  private

  def dasherize(name); end
  def demodulize(name); end
  def underscore(name); end

  class << self
    def dasherize(name); end
    def demodulize(name); end
    def underscore(name); end
  end
end

module TTY::Option::Inheritance
  def inherited(subclass); end
end

module TTY::Option::Interface
  def help(**config, &block); end
  def params; end
  def parse(argv = T.unsafe(nil), env = T.unsafe(nil), check_invalid_params: T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end
end

class TTY::Option::InvalidArgument < ::TTY::Option::ParseError
  def initialize(param_or_message, value = T.unsafe(nil)); end
end

TTY::Option::InvalidArgument::MESSAGE = T.let(T.unsafe(nil), String)

class TTY::Option::InvalidArity < ::TTY::Option::ParseError
  def initialize(param_or_message, arity = T.unsafe(nil)); end

  def pluralize(noun, count = T.unsafe(nil)); end
end

TTY::Option::InvalidArity::MESSAGE = T.let(T.unsafe(nil), String)

class TTY::Option::InvalidConversionArgument < ::TTY::Option::ParseError
  def initialize(param, value); end
end

TTY::Option::InvalidConversionArgument::MESSAGE = T.let(T.unsafe(nil), String)
class TTY::Option::InvalidParameter < ::TTY::Option::ParseError; end

class TTY::Option::MissingArgument < ::TTY::Option::ParseError
  def initialize(param); end
end

TTY::Option::MissingArgument::MESSAGE = T.let(T.unsafe(nil), String)

class TTY::Option::MissingParameter < ::TTY::Option::ParseError
  def initialize(param_or_message); end
end

TTY::Option::MissingParameter::MESSAGE = T.let(T.unsafe(nil), String)

module TTY::Option::ParamConversion
  private

  def [](param, value); end
  def call(param, value); end

  class << self
    def [](param, value); end
    def call(param, value); end
  end
end

module TTY::Option::ParamPermitted
  private

  def [](param, value); end
  def call(param, value); end

  class << self
    def [](param, value); end
    def call(param, value); end
  end
end

module TTY::Option::ParamValidation
  private

  def [](param, value); end
  def call(param, value); end
  def valid?(param, value); end
  def valid_or_error(param, value); end
  def validate_array(param, values); end
  def validate_hash(param, values); end
  def validate_object(param, value, &block); end

  class << self
    def [](param, value); end
    def call(param, value); end

    private

    def valid?(param, value); end
    def valid_or_error(param, value); end
    def validate_array(param, values); end
    def validate_hash(param, values); end
    def validate_object(param, value, &block); end
  end
end

class TTY::Option::Parameter
  include ::Comparable
  include ::TTY::Option::DSL::Arity
  include ::TTY::Option::DSL::Conversion

  def initialize(key, **settings, &block); end

  def <=>(other); end
  def ==(other); end
  def arity(value = T.unsafe(nil)); end
  def convert(value = T.unsafe(nil)); end
  def convert?; end
  def default(value = T.unsafe(nil)); end
  def default?; end
  def default_arity; end
  def default_name; end
  def defaults(value = T.unsafe(nil)); end
  def desc(value = T.unsafe(nil)); end
  def desc?; end
  def display?; end
  def dup; end
  def eql?(other); end
  def hidden; end
  def hidden?; end
  def key; end
  def min_arity; end
  def multi_argument?; end
  def multiple?; end
  def name(value = T.unsafe(nil)); end
  def optional; end
  def optional?; end
  def permit(value = T.unsafe(nil)); end
  def permit?; end
  def required; end
  def required?; end
  def to_h(&block); end
  def to_sym; end
  def validate(value = T.unsafe(nil)); end
  def validate?; end

  private

  def check_arity(value); end
  def check_default(value); end
  def check_permitted(value); end
  def check_required(value); end
  def check_validation(value); end

  class << self
    def create(key, **settings, &block); end
  end
end

class TTY::Option::Parameter::Argument < ::TTY::Option::Parameter
  def required?; end
end

class TTY::Option::Parameter::Environment < ::TTY::Option::Parameter
  def <=>(other); end
  def default_name; end
end

class TTY::Option::Parameter::Keyword < ::TTY::Option::Parameter
  def required?; end
end

TTY::Option::Parameter::ONE_OR_MORE_ARITY = T.let(T.unsafe(nil), Regexp)

class TTY::Option::Parameter::Option < ::TTY::Option::Parameter
  def <=>(other); end
  def argument_optional?; end
  def argument_required?; end
  def default_long; end
  def default_name; end
  def long(value = T.unsafe(nil)); end
  def long?; end
  def long_name; end
  def short(value = T.unsafe(nil)); end
  def short?; end
  def short_name; end
end

TTY::Option::Parameter::Option::LONG_ARGUMENT_OPTIONAL_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parameter::Option::LONG_ARGUMENT_REQUIRED_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parameter::Option::SHORT_ARGUMENT_OPTIONAL_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parameter::Option::SHORT_ARGUMENT_REQUIRED_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parameter::ZERO_OR_MORE_ARITY = T.let(T.unsafe(nil), Regexp)
class TTY::Option::ParameterConflict < ::TTY::Option::Error; end

class TTY::Option::Parameters
  include ::Enumerable

  def initialize; end

  def <<(parameter); end
  def add(parameter); end
  def argument?(param); end
  def arguments; end
  def arguments?; end
  def delete(*keys); end
  def dup; end
  def each(&block); end
  def environment?(param); end
  def environments; end
  def environments?; end
  def keyword?(param); end
  def keywords; end
  def keywords?; end
  def list; end
  def option?(param); end
  def options; end
  def options?; end

  private

  def check_key_uniqueness!(key); end
  def check_long_option_uniqueness!(long_name); end
  def check_short_option_uniqueness!(short_name); end

  class << self
    def define_param_query(name); end
    def define_query(name); end
  end
end

class TTY::Option::Params
  extend ::Forwardable

  def initialize(parameters, remaining: T.unsafe(nil), errors: T.unsafe(nil)); end

  def ==(other); end
  def [](key); end
  def []=(key, value); end
  def each_key(*args, **_arg1, &block); end
  def each_value(*args, **_arg1, &block); end
  def empty?(*args, **_arg1, &block); end
  def eql?(other); end
  def errors; end
  def fetch(key, *args, &block); end
  def has_key?(*args, **_arg1, &block); end
  def has_value?(*args, **_arg1, &block); end
  def hash; end
  def include?(*args, **_arg1, &block); end
  def inspect; end
  def key?(*args, **_arg1, &block); end
  def keys(*args, **_arg1, &block); end
  def member?(*args, **_arg1, &block); end
  def merge(other_params); end
  def merge!(other_params); end
  def remaining; end
  def to_h; end
  def to_s; end
  def valid?; end
  def value?(*args, **_arg1, &block); end

  class << self
    def create(parameters = T.unsafe(nil), remaining = T.unsafe(nil), errors = T.unsafe(nil)); end
  end
end

class TTY::Option::ParseError < ::TTY::Option::Error
  def format_value(value); end
  def param; end
  def param=(_arg0); end
end

class TTY::Option::Parser
  def initialize(parameters, **config); end

  def config; end
  def parameters; end
  def parse(argv, env); end
end

TTY::Option::Parser::ARGUMENT_SEPARATOR = T.let(T.unsafe(nil), Regexp)

class TTY::Option::Parser::Arguments
  include ::TTY::Option::Parser::ParamTypes

  def initialize(arguments, check_invalid_params: T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end

  def parse(argv); end

  private

  def assign_argument(arg, values); end
  def next_argument(arg); end
  def process_exact_arity(arg); end
  def process_infinite_arity(arg); end
end

class TTY::Option::Parser::ArityCheck
  def initialize(error_aggregator); end

  def <<(param); end
  def add(param); end
  def call(arities); end
end

class TTY::Option::Parser::Environments
  include ::TTY::Option::Parser::ParamTypes

  def initialize(environments, check_invalid_params: T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end

  def parse(argv, env); end

  private

  def assign_envvar(env_arg, val); end
  def consume_arguments(values: T.unsafe(nil)); end
  def next_envvar; end
end

TTY::Option::Parser::Environments::ENV_VAR_RE = T.let(T.unsafe(nil), Regexp)

class TTY::Option::Parser::Keywords
  include ::TTY::Option::Parser::ParamTypes

  def initialize(keywords, check_invalid_params: T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end

  def parse(argv); end

  private

  def assign_keyword(kwarg, val); end
  def consume_arguments(values: T.unsafe(nil)); end
  def next_keyword; end
end

TTY::Option::Parser::Keywords::KEYWORD_ARG_RE = T.let(T.unsafe(nil), Regexp)

class TTY::Option::Parser::Options
  include ::TTY::Option::Parser::ParamTypes

  def initialize(options, check_invalid_params: T.unsafe(nil), raise_on_parse_error: T.unsafe(nil)); end

  def parse(argv); end
  def setup_opts; end

  private

  def assign_option(opt, val); end
  def consume_arguments(values: T.unsafe(nil)); end
  def next_option; end
  def process_double_option(long, sep, rest); end
  def process_single_option(short, other_singles); end
end

TTY::Option::Parser::Options::LONG_OPTION_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parser::Options::SHORT_OPTION_RE = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parser::PARAMETER_PARSERS = T.let(T.unsafe(nil), Hash)

module TTY::Option::Parser::ParamTypes
  def argument?(value); end
  def env_var?(value); end
  def keyword?(value); end
  def option?(value); end
end

TTY::Option::Parser::ParamTypes::ARGUMENT_PARAMETER = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parser::ParamTypes::ENV_VAR_PARAMETER = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parser::ParamTypes::KEYWORD_PARAMETER = T.let(T.unsafe(nil), Regexp)
TTY::Option::Parser::ParamTypes::OPTION_PARAMETER = T.let(T.unsafe(nil), Regexp)

class TTY::Option::Parser::RequiredCheck
  def initialize(error_aggregator); end

  def <<(param); end
  def add(param); end
  def call; end
  def delete(param); end
end

class TTY::Option::Pipeline
  def initialize(error_aggregator); end

  def call(param, value); end
end

TTY::Option::Pipeline::PROCESSORS = T.let(T.unsafe(nil), Array)

class TTY::Option::Result
  def error; end
  def failure?; end
  def success?; end
  def value; end

  class << self
    def failure(value); end
    def success(value); end
  end
end

class TTY::Option::Result::Failure < ::TTY::Option::Result
  def initialize(error); end
end

class TTY::Option::Result::Success < ::TTY::Option::Result
  def initialize(value); end
end

class TTY::Option::Section
  def initialize(name, content = T.unsafe(nil)); end

  def content; end
  def content=(_arg0); end
  def empty?; end
  def name; end
  def name=(_arg0); end
  def to_a; end
  def to_s; end
end

class TTY::Option::Sections
  include ::Enumerable
  extend ::Forwardable

  def initialize; end

  def [](name); end
  def add(name, content); end
  def add_after(name, sect_name, sect_content); end
  def add_before(name, sect_name, sect_content); end
  def delete(*names); end
  def each(&block); end
  def replace(name, content); end
  def size(*args, **_arg1, &block); end
  def to_a(*args, **_arg1, &block); end

  private

  def find_index(name); end
end

class TTY::Option::UnpermittedArgument < ::TTY::Option::ParseError
  def initialize(param_or_message, value = T.unsafe(nil)); end

  private

  def format_choices(choices); end
end

TTY::Option::UnpermittedArgument::MESSAGE = T.let(T.unsafe(nil), String)
class TTY::Option::UnsupportedConversion < ::TTY::Option::Error; end

class TTY::Option::Usage
  def initialize(**properties, &block); end

  def banner(value = T.unsafe(nil)); end
  def banner?; end
  def command(*values); end
  def command?; end
  def commands(*values); end
  def desc(*values); end
  def desc?; end
  def description(*values); end
  def description?; end
  def example(*values); end
  def example?; end
  def examples(*values); end
  def examples?; end
  def footer(*values); end
  def footer?; end
  def header(*values); end
  def header?; end
  def no_command; end
  def no_command?; end
  def program(name = T.unsafe(nil)); end
  def to_h(&block); end

  class << self
    def create(**properties, &block); end
  end
end

module TTY::Option::UsageWrapper
  private

  def next_line(text, wrap: T.unsafe(nil)); end
  def wrap(text, width: T.unsafe(nil), indent: T.unsafe(nil), indent_first: T.unsafe(nil)); end

  class << self
    def wrap(text, width: T.unsafe(nil), indent: T.unsafe(nil), indent_first: T.unsafe(nil)); end

    private

    def next_line(text, wrap: T.unsafe(nil)); end
  end
end

TTY::Option::VERSION = T.let(T.unsafe(nil), String)
