# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `udb_helpers` gem.
# Please instead update this file by running `bin/tapioca gem udb_helpers`.


class String
  include ::Comparable

  def sanitize; end
end

module Udb; end

module Udb::Helpers
  class << self
    def version; end
  end
end

module Udb::Helpers::AntoraUtils
  class << self
    def resolve_links(path_or_str); end
  end
end

module Udb::Helpers::AsciidocUtils
  class << self
    def resolve_links(path_or_str); end
  end
end

module Udb::Helpers::TemplateHelpers
  include ::Udb::Helpers::WavedromUtil

  def anchor_for_non_isa_spec(name); end
  def anchor_for_udb_doc_cov_pt(org, id); end
  def anchor_for_udb_doc_csr(name); end
  def anchor_for_udb_doc_csr_field(csr_name, field_name); end
  def anchor_for_udb_doc_ext(ext_name); end
  def anchor_for_udb_doc_ext_param(ext_name, param_name); end
  def anchor_for_udb_doc_idl_func(name); end
  def anchor_for_udb_doc_inst(name); end
  def anchor_for_udb_doc_mmr(name); end
  def anchor_for_udb_doc_mmr_field(mmr_name, field_name); end
  def anchor_inside_idl_inst_code(inst_name, id); end
  def link_into_idl_inst_code(inst_name, id); end
  def link_to_udb_doc_cov_pt(org, id); end
  def link_to_udb_doc_csr(csr_name); end
  def link_to_udb_doc_csr_field(csr_name, field_name); end
  def link_to_udb_doc_ext(ext_name); end
  def link_to_udb_doc_ext_param(ext_name, param_name, link_text); end
  def link_to_udb_doc_idl_func(func_name); end
  def link_to_udb_doc_inst(inst_name); end
  def link_to_udb_doc_mmr(mmr_name); end
  def link_to_udb_doc_mmr_field(mmr_name, field_name); end
  def partial(template_pname, inputs = T.unsafe(nil)); end

  private

  def check_no_periods(s); end
end

module Udb::Helpers::WavedromUtil
  def fix_entities(text); end
  def json_dump_with_hex_literals(data); end
  def process_wavedrom(json_data); end
end
