# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `write_xlsx` gem.
# Please instead update this file by running `bin/tapioca gem write_xlsx`.


class ColName
  include ::Singleton::SingletonInstanceMethods
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  def initialize; end

  def col_str(col); end
  def row_str(row); end

  private

  def col_str_build(col); end

  class << self
    private

    def allocate; end
    def new(*_arg0); end
  end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::Udb::Helpers::WavedromUtil

  private

  def ruby_18; end
  def ruby_19; end
end

class String
  include ::Comparable

  def first_line; end
end

class WriteXLSX < ::Writexlsx::Workbook; end
class WriteXLSXDimensionError < ::StandardError; end
class WriteXLSXInsufficientArgumentError < ::StandardError; end
class WriteXLSXOptionParameterError < ::StandardError; end
module Writexlsx; end

class Writexlsx::Chart
  include ::Writexlsx::Utility
  include ::Writexlsx::Gradient

  def initialize(subtype); end

  def add_series(params); end
  def already_inserted=(_arg0); end
  def already_inserted?; end
  def assemble_xml_file; end
  def axis2_ids; end
  def combine(chart); end
  def combined; end
  def data_id(full_formula, data); end
  def date_category=(_arg0); end
  def embedded; end
  def formula_data; end
  def formula_ids; end
  def height; end
  def id; end
  def id=(_arg0); end
  def index=(_arg0); end
  def is_secondary?; end
  def label_position_default; end
  def label_positions; end
  def name; end
  def name=(_arg0); end
  def palette=(_arg0); end
  def process_names(name = T.unsafe(nil), name_formula = T.unsafe(nil)); end
  def protection=(_arg0); end
  def series_index=(_arg0); end
  def set_chartarea(params); end
  def set_drop_lines(params = T.unsafe(nil)); end
  def set_embedded_config_data; end
  def set_high_low_lines(params = T.unsafe(nil)); end
  def set_legend(params); end
  def set_plotarea(params); end
  def set_size(params = T.unsafe(nil)); end
  def set_style(style_id = T.unsafe(nil)); end
  def set_table(params = T.unsafe(nil)); end
  def set_title(params); end
  def set_up_down_bars(params = T.unsafe(nil)); end
  def set_x2_axis(params = T.unsafe(nil)); end
  def set_x_axis(params = T.unsafe(nil)); end
  def set_xml_writer(filename); end
  def set_y2_axis(params = T.unsafe(nil)); end
  def set_y_axis(params = T.unsafe(nil)); end
  def show_blanks_as(option); end
  def show_hidden_data; end
  def show_na_as_empty_cell; end
  def size(params = T.unsafe(nil)); end
  def width; end
  def write_bar_chart(params); end
  def write_val_axis(x_axis, y_axis, axis_ids, position = T.unsafe(nil)); end
  def writer=(_arg0); end
  def x2_axis; end
  def x_offset; end
  def x_scale; end
  def y2_axis; end
  def y_offset; end
  def y_scale; end

  private

  def add_axis_ids(params); end
  def axes_series(params); end
  def axis_setup; end
  def chart_space_attributes; end
  def display_setup; end
  def get_data_type(data); end
  def get_primary_axes_series; end
  def get_secondary_axes_series; end
  def has_fill_formatting(element); end
  def ids; end
  def position_allowed; end
  def primary_axes_series; end
  def secondary_axes_series; end
  def series_property(object, property); end
  def set_axis_defaults; end
  def set_default_properties; end
  def write_a_alpha(val); end
  def write_a_bg_clr(color); end
  def write_a_fg_clr(color); end
  def write_a_fill_to_rect(type); end
  def write_a_grad_fill(gradient); end
  def write_a_gs_lst(gradient); end
  def write_a_latin(args); end
  def write_a_lin(angle); end
  def write_a_ln(line); end
  def write_a_no_fill; end
  def write_a_p_pr_rich(font); end
  def write_a_p_rich(title, font, ignore_rich_pr); end
  def write_a_path(type); end
  def write_a_patt_fill(pattern); end
  def write_a_prst_dash(val); end
  def write_a_r(title, font); end
  def write_a_r_pr(font); end
  def write_a_t(title); end
  def write_a_tile_rect(type); end
  def write_auto(val); end
  def write_auto_title_deleted; end
  def write_axis_font(font); end
  def write_axis_id(val); end
  def write_axis_ids(params); end
  def write_axis_pos(val, reverse = T.unsafe(nil)); end
  def write_backward(val); end
  def write_bars_base(tag, format); end
  def write_c_crosses_at(val); end
  def write_c_invert_if_negative(invert = T.unsafe(nil)); end
  def write_c_log_base(val); end
  def write_c_major_time_unit(val); end
  def write_c_major_unit(val = T.unsafe(nil)); end
  def write_c_max(max = T.unsafe(nil)); end
  def write_c_min(min = T.unsafe(nil)); end
  def write_c_minor_time_unit(val); end
  def write_c_minor_unit(val = T.unsafe(nil)); end
  def write_c_smooth(smooth); end
  def write_cat(series); end
  def write_cat_axis(params); end
  def write_cat_number_format(axis); end
  def write_chart; end
  def write_chart_space(&block); end
  def write_chart_type; end
  def write_cross_axis(val = T.unsafe(nil)); end
  def write_cross_between(val = T.unsafe(nil)); end
  def write_crosses(val); end
  def write_crossing(crossing); end
  def write_custom_error(error_bars); end
  def write_custom_error_base(tag, values, data); end
  def write_custom_label_format_only(label); end
  def write_custom_label_formula(label); end
  def write_custom_label_str(label); end
  def write_custom_labels(parent, labels); end
  def write_d_lbl_pos(val); end
  def write_d_lbls(labels); end
  def write_d_pt(points = T.unsafe(nil)); end
  def write_d_pt_point(index, point); end
  def write_d_table; end
  def write_data_label_number_format(format_code); end
  def write_date_axis(params); end
  def write_delete(val); end
  def write_disp_blanks_as; end
  def write_disp_eq; end
  def write_disp_rsqr; end
  def write_disp_units(units, display); end
  def write_down_bars(format); end
  def write_drop_lines; end
  def write_err_bar_type(val); end
  def write_err_bars(direction, error_bars); end
  def write_err_dir(val); end
  def write_err_val_type(val); end
  def write_error_bars(error_bars); end
  def write_error_val(val); end
  def write_ext_lst_display_na; end
  def write_ext_lst_inverted_fill(color); end
  def write_format_code(data); end
  def write_forward(val); end
  def write_gap_width(val = T.unsafe(nil)); end
  def write_gridlines_base(tag, gridlines); end
  def write_grouping(val); end
  def write_header_footer; end
  def write_hi_low_lines; end
  def write_idx(val); end
  def write_intercept(val); end
  def write_label_align(val); end
  def write_label_offset(val); end
  def write_lang; end
  def write_layout(layout = T.unsafe(nil), type = T.unsafe(nil)); end
  def write_legend; end
  def write_legend_entry(index); end
  def write_legend_pos(val); end
  def write_lines_base(lines, tag); end
  def write_major_gridlines(gridlines); end
  def write_major_tick_mark(val); end
  def write_manual_layout(layout, type); end
  def write_marker(marker = T.unsafe(nil)); end
  def write_marker_size(val); end
  def write_marker_value; end
  def write_minor_gridlines(gridlines); end
  def write_minor_tick_mark(val); end
  def write_multi_lvl_str_ref(formula, data); end
  def write_name(data); end
  def write_no_end_cap; end
  def write_num_base(tag, data); end
  def write_num_cache(data); end
  def write_num_lit(data); end
  def write_num_or_str_ref(tag, formula, data, type); end
  def write_num_ref(formula, data, type); end
  def write_num_ref_or_lit(values, data); end
  def write_number_format(axis); end
  def write_order(val); end
  def write_orientation(reverse = T.unsafe(nil)); end
  def write_overlap(val = T.unsafe(nil)); end
  def write_overlay; end
  def write_page_margins; end
  def write_page_setup; end
  def write_period(val = T.unsafe(nil)); end
  def write_plot_area; end
  def write_plot_vis_only; end
  def write_print_settings; end
  def write_protection; end
  def write_pt(idx, value); end
  def write_pt_count(val); end
  def write_pts(data); end
  def write_rich(title, font, is_y_axis, ignore_rich_pr = T.unsafe(nil)); end
  def write_scaling(reverse, min = T.unsafe(nil), max = T.unsafe(nil), log_base = T.unsafe(nil)); end
  def write_scaling_with_param(param); end
  def write_separator(data); end
  def write_ser(series); end
  def write_ser_base(series); end
  def write_series(series); end
  def write_series_formula(formula); end
  def write_series_name(series); end
  def write_show_cat_name; end
  def write_show_leader_lines; end
  def write_show_legend_key; end
  def write_show_percent; end
  def write_show_ser_name; end
  def write_show_val; end
  def write_sp_pr(series); end
  def write_str_cache(data); end
  def write_str_ref(formula, data, type); end
  def write_style; end
  def write_symbol(val); end
  def write_tick_label_pos(val); end
  def write_tick_lbl_skip(val); end
  def write_tick_mark_skip(val); end
  def write_title_formula(title, is_y_axis = T.unsafe(nil), axis = T.unsafe(nil), layout = T.unsafe(nil), overlay = T.unsafe(nil)); end
  def write_title_rich(title, is_y_axis, font, layout, overlay = T.unsafe(nil)); end
  def write_trendline(trendline); end
  def write_trendline_lbl(trendline); end
  def write_trendline_num_fmt; end
  def write_trendline_order(val = T.unsafe(nil)); end
  def write_trendline_type(val); end
  def write_tx_formula(title, data_id); end
  def write_tx_rich(title, is_y_axis, font); end
  def write_tx_value(title); end
  def write_up_bars(format); end
  def write_up_down_bars; end
  def write_v(data); end
  def write_val(series); end
  def write_val_axis_base(x_axis, y_axis, axis_ids_0, axis_ids_1, position); end
  def write_val_base(formula, data_id, tag); end
  def x2_axis_defaults; end
  def x_axis_defaults; end
  def y2_axis_defaults; end
  def y_axis_defaults; end

  class << self
    def factory(current_subclass, subtype = T.unsafe(nil)); end
  end
end

class Writexlsx::Chart::Axis < ::Writexlsx::Chart::Caption
  def crossing; end
  def defaults; end
  def defaults=(_arg0); end
  def display_units; end
  def display_units_visible; end
  def fill; end
  def interval_tick; end
  def interval_unit; end
  def label_align; end
  def label_position; end
  def layout; end
  def line; end
  def log_base; end
  def major_gridlines; end
  def major_tick_mark; end
  def major_tick_mark=(_arg0); end
  def major_unit; end
  def major_unit_type; end
  def max; end
  def max=(_arg0); end
  def merge_with_hash(params); end
  def min; end
  def min=(_arg0); end
  def minor_gridlines; end
  def minor_tick_mark; end
  def minor_tick_mark=(_arg0); end
  def minor_unit; end
  def minor_unit_type; end
  def num_font; end
  def num_format; end
  def num_format=(_arg0); end
  def num_format_linked; end
  def position; end
  def position=(_arg0); end
  def position_axis; end
  def reverse; end
  def text_axis; end
  def visible; end
  def write_cat_number_format(writer, cat_has_num_fmt); end
  def write_number_format(writer); end

  private

  def get_display_units(display_units); end
  def get_tick_type(tick_type); end
  def num_fmt_attributes; end
  def set_axis_fill(args); end
  def set_axis_line(args); end
  def set_axis_name_layout(args); end
  def set_display_units(args); end
  def set_display_units_visible(args); end
  def set_font_properties(args); end
  def set_major_minor_gridlines(args); end
  def set_position(args); end
  def set_position_axis; end
  def source_linked; end
  def user_defined_num_fmt_set?; end
end

class Writexlsx::Chart::Caption
  include ::Writexlsx::Utility

  def initialize(chart); end

  def data_id; end
  def data_id=(_arg0); end
  def formula; end
  def formula=(_arg0); end
  def layout; end
  def merge_with_hash(params); end
  def name; end
  def name=(_arg0); end
  def name_font; end
  def name_font=(_arg0); end
  def none; end
  def overlay; end

  private

  def chart; end
end

class Writexlsx::Chart::Chartline
  include ::Writexlsx::Utility
  include ::Writexlsx::Gradient

  def initialize(params); end

  def fill; end
  def fill_defined?; end
  def gradient; end
  def line; end
  def line_defined?; end
  def pattern; end
  def type; end
end

class Writexlsx::Chart::Errorbars
  include ::Writexlsx::Utility

  def initialize(params); end

  def direction; end
  def endcap; end
  def fill; end
  def line; end
  def minus_data; end
  def minus_values; end
  def plus_data; end
  def plus_values; end
  def type; end
  def value; end

  private

  def error_bar_direction(direction); end
  def types; end
end

class Writexlsx::Chart::Gridline < ::Writexlsx::Chart::Chartline
  def initialize(params); end

  def visible; end
end

class Writexlsx::Chart::Legend
  def initialize; end

  def delete_series; end
  def delete_series=(_arg0); end
  def fill; end
  def fill=(_arg0); end
  def font; end
  def font=(_arg0); end
  def gradient; end
  def gradient=(_arg0); end
  def layout; end
  def layout=(_arg0); end
  def line; end
  def line=(_arg0); end
  def pattern; end
  def pattern=(_arg0); end
  def position; end
  def position=(_arg0); end
end

class Writexlsx::Chart::Marker < ::Writexlsx::Chart::Chartline
  def initialize(params); end

  def automatic?; end
  def size; end

  private

  def types; end
end

class Writexlsx::Chart::Point < ::Writexlsx::Chart::Chartline; end

class Writexlsx::Chart::Series
  include ::Writexlsx::Utility
  include ::Writexlsx::Gradient

  def initialize(chart, params = T.unsafe(nil)); end

  def ==(other); end
  def cat_data_id; end
  def categories; end
  def error_bars; end
  def fill; end
  def gradient; end
  def invert_if_negative; end
  def inverted_color; end
  def labels; end
  def line; end
  def line=(_arg0); end
  def line_defined?; end
  def marker; end
  def marker=(_arg0); end
  def name; end
  def name_formula; end
  def name_id; end
  def pattern; end
  def points; end
  def smooth; end
  def trendline; end
  def val_data_id; end
  def values; end
  def x2_axis; end
  def y2_axis; end

  private

  def aref_to_formula(data); end
  def errorbars(x, y); end
  def labels_properties(labels); end
  def set_data_ids(params); end
end

class Writexlsx::Chart::Trendline < ::Writexlsx::Chart::Chartline
  def initialize(params); end

  def backward; end
  def display_equation; end
  def display_r_squared; end
  def forward; end
  def intercept; end
  def label; end
  def name; end
  def order; end
  def period; end

  private

  def trendline_label_properties(_label); end
  def types; end
end

class Writexlsx::ChartArea
  include ::Writexlsx::Utility
  include ::Writexlsx::Gradient

  def initialize(params = T.unsafe(nil)); end

  def fill; end
  def gradient; end
  def layout; end
  def line; end
  def pattern; end

  private

  def numeric_or_downcase(val); end
  def params_to_border(params); end
  def swe_line_pattern(val); end
  def swe_line_pattern_hash; end
  def swe_line_weight(val); end
  def swe_line_weight_hash; end
end

class Writexlsx::Chartsheet < ::Writexlsx::Worksheet
  def initialize(workbook, index, name); end

  def add_series(*args); end
  def assemble_xml_file; end
  def chart=(_arg0); end
  def external_links; end
  def prepare_chart(_index, chart_id, drawing_id); end
  def protect(password = T.unsafe(nil), user_options = T.unsafe(nil), options = T.unsafe(nil)); end
  def set_chartarea(*args); end
  def set_drop_lines(*args); end
  def set_high_low_lines(*args); end
  def set_legend(*args); end
  def set_plotarea(*args); end
  def set_size(*args); end
  def set_style(*args); end
  def set_table(*args); end
  def set_title(*args); end
  def set_up_down_bars(*args); end
  def set_x2_axis(*args); end
  def set_x_axis(*args); end
  def set_y2_axis(*args); end
  def set_y_axis(*args); end
  def show_blanks_as(*args); end
  def show_hidden_data(*args); end
  def show_na_as_empty_cell; end

  private

  def write_chartsheet(&block); end
  def write_sheet_pr; end
end

class Writexlsx::Colors
  def color(color_code = T.unsafe(nil)); end
  def inspect; end
end

Writexlsx::Colors::COLORS = T.let(T.unsafe(nil), Hash)

class Writexlsx::Drawing
  include ::Writexlsx::Utility

  def initialize(type, dimensions, width, height, shape, anchor, rel_index = T.unsafe(nil), url_rel_index = T.unsafe(nil), tip = T.unsafe(nil), name = T.unsafe(nil), description = T.unsafe(nil), decorative = T.unsafe(nil)); end

  def anchor; end
  def anchor=(_arg0); end
  def decorative; end
  def description; end
  def description=(_arg0); end
  def dimensions; end
  def dimensions=(_arg0); end
  def embedded=(_arg0); end
  def height; end
  def height=(_arg0); end
  def name; end
  def name=(_arg0); end
  def orientation=(_arg0); end
  def rel_index; end
  def rel_index=(_arg0); end
  def shape; end
  def shape=(_arg0); end
  def tip; end
  def type; end
  def type=(_arg0); end
  def url_rel_index; end
  def url_rel_index=(_arg0); end
  def width; end
  def width=(_arg0); end
  def write_a16_creation_id; end
  def write_a_av_lst(shape = T.unsafe(nil)); end
  def write_a_blip(index); end
  def write_a_ext(cx, cy); end
  def write_a_fill_rect; end
  def write_a_graphic_frame_locks; end
  def write_a_hlink_click(index, tip); end
  def write_a_ln(shape = T.unsafe(nil)); end
  def write_a_off; end
  def write_a_pic_locks; end
  def write_a_prst_geom(shape = T.unsafe(nil)); end
  def write_a_solid_fill(rgb = T.unsafe(nil)); end
  def write_a_stretch; end
  def write_a_uri_ext(uri); end
  def write_a_xfrm(shape = T.unsafe(nil)); end
  def write_absolute_anchor(index); end
  def write_adec_decorative; end
  def write_atag_graphic(index); end
  def write_atag_graphic_data(index); end
  def write_blip_fill; end
  def write_c_chart(id); end
  def write_c_nv_graphic_frame_pr; end
  def write_c_nv_pic_pr; end
  def write_c_nv_pr(index, name, description = T.unsafe(nil), url_rel_index = T.unsafe(nil), tip = T.unsafe(nil), decorative = T.unsafe(nil)); end
  def write_client_data; end
  def write_col(data); end
  def write_col_off(data); end
  def write_decorative; end
  def write_from; end
  def write_graphic_frame(index, rel_index, name = T.unsafe(nil), description = T.unsafe(nil), decorative = T.unsafe(nil), macro = T.unsafe(nil)); end
  def write_nv_cxn_sp_pr(index, shape); end
  def write_nv_graphic_frame_pr(index, name = T.unsafe(nil), description = T.unsafe(nil), decorative = T.unsafe(nil)); end
  def write_nv_pic_pr(index); end
  def write_nv_sp_pr(index, shape); end
  def write_pic(index); end
  def write_pos(x, y); end
  def write_row(data); end
  def write_row_off(data); end
  def write_sp(index, shape); end
  def write_sp_pr(shape); end
  def write_to; end
  def write_two_cell_anchor(index); end
  def write_tx_body(shape); end
  def write_xdr_ext(cx, cy); end
  def write_xdr_sp_pr(shape); end
  def write_xfrm; end
  def write_xfrm_extension; end
  def write_xfrm_offset; end
  def writer=(_arg0); end
end

class Writexlsx::Drawings
  include ::Writexlsx::Utility

  def initialize; end

  def add_drawing_object(drawing); end
  def assemble_xml_file; end
  def embedded=(_arg0); end
  def orientation=(_arg0); end
  def set_xml_writer(filename); end
  def xml_str; end

  private

  def write_drawing_workspace(&block); end
end

class Writexlsx::Format
  include ::Writexlsx::Utility

  def initialize(formats, params = T.unsafe(nil)); end

  def [](attr); end
  def bg_color; end
  def bg_color=(_arg0); end
  def bold; end
  def bold?; end
  def border_attributes; end
  def border_index; end
  def border_index=(_arg0); end
  def bottom; end
  def bottom_color; end
  def color(color_code); end
  def color?; end
  def color_indexed; end
  def copy(other); end
  def diag_border; end
  def diag_border=(_arg0); end
  def diag_color; end
  def diag_type; end
  def dxf_bg_color; end
  def dxf_bg_color=(_arg0); end
  def dxf_fg_color; end
  def dxf_fg_color=(_arg0); end
  def dxf_index; end
  def fg_color; end
  def fg_color=(_arg0); end
  def fill_index; end
  def fill_index=(_arg0); end
  def font; end
  def font_condense; end
  def font_condense=(_arg0); end
  def font_extend; end
  def font_extend=(_arg0); end
  def font_family; end
  def font_index; end
  def font_index=(_arg0); end
  def font_only; end
  def font_scheme; end
  def font_script; end
  def font_strikeout; end
  def force_text_format?; end
  def get_align_properties; end
  def get_alignment_key; end
  def get_border_key; end
  def get_dxf_index; end
  def get_fill_key; end
  def get_font_key; end
  def get_format_key; end
  def get_protection_properties; end
  def get_xf_index; end
  def has_border(flag); end
  def has_border?; end
  def has_dxf_border(flag); end
  def has_dxf_border?; end
  def has_dxf_fill(flag); end
  def has_dxf_fill?; end
  def has_dxf_font(flag); end
  def has_dxf_font?; end
  def has_fill(flag); end
  def has_fill?; end
  def has_font(flag); end
  def has_font?; end
  def hyperlink; end
  def inspect; end
  def italic; end
  def italic?; end
  def left; end
  def left_color; end
  def method_missing(name, *args); end
  def num_format; end
  def num_format_index; end
  def num_format_index=(_arg0); end
  def outline?; end
  def pattern; end
  def pattern=(_arg0); end
  def quote_prefix; end
  def quote_prefix=(_arg0); end
  def right; end
  def right_color; end
  def rotation; end
  def set_align(location); end
  def set_bold(bold = T.unsafe(nil)); end
  def set_border(style); end
  def set_border_color(color); end
  def set_border_info(borders); end
  def set_center_across(_flag = T.unsafe(nil)); end
  def set_font_info(fonts); end
  def set_format_properties(*properties); end
  def set_hyperlink(hyperlink); end
  def set_merge(_merge = T.unsafe(nil)); end
  def set_rotation(rotation); end
  def set_valign(location); end
  def shadow?; end
  def size; end
  def strikeout?; end
  def theme; end
  def top; end
  def top_color; end
  def underline; end
  def underline?; end
  def write_font(writer, worksheet, dxf_format = T.unsafe(nil)); end
  def write_font_rpr(writer, worksheet); end
  def xf_attributes; end
  def xf_id; end
  def xf_index; end

  private

  def write_condense(writer); end
  def write_extend(writer); end
  def write_font_family_scheme(writer); end
  def write_font_shapes(writer); end
  def write_underline(writer, underline); end
  def write_underline_attributes(underline); end
  def write_vert_align(writer, val); end

  class << self
    def color(color_code); end
  end
end

class Writexlsx::Formats
  include ::Writexlsx::Utility

  def initialize; end

  def dxf_format_indices; end
  def dxf_index_by_key(key); end
  def formats; end
  def set_dxf_index_by_key(key); end
  def set_xf_index_by_key(key); end
  def xf_format_indices; end
  def xf_index_by_key(key); end
end

module Writexlsx::Gradient
  def gradient_properties(args); end
end

class Writexlsx::Image
  def initialize(row, col, image, x_offset, y_offset, x_scale, y_scale, url, tip, anchor, description, decorative); end

  def anchor; end
  def col; end
  def decorative; end
  def description; end
  def filename; end
  def height; end
  def height_emus; end
  def image; end
  def md5; end
  def name; end
  def position; end
  def ref_id; end
  def row; end
  def scaled_height; end
  def scaled_width; end
  def tip; end
  def type; end
  def url; end
  def width; end
  def width_emus; end
  def x_dpi; end
  def x_offset; end
  def x_scale; end
  def y_dpi; end
  def y_offset; end
  def y_scale; end
end

class Writexlsx::ImageProperty
  def initialize(filename, options = T.unsafe(nil)); end

  def body; end
  def body=(_arg0); end
  def decorative; end
  def description; end
  def filename; end
  def height; end
  def md5; end
  def name; end
  def position; end
  def position=(_arg0); end
  def process_bmp(data); end
  def process_gif(data); end
  def process_jpg(data); end
  def process_png(data); end
  def ref_id; end
  def ref_id=(_arg0); end
  def type; end
  def width; end
  def x_dpi; end
  def y_dpi; end
end

class Writexlsx::InsertedChart
  include ::Writexlsx::Utility

  def initialize(row, col, chart, x_offset, y_offset, x_scale, y_scale, anchor, description, decorative); end

  def anchor; end
  def chart; end
  def col; end
  def decorative; end
  def description; end
  def name; end
  def row; end
  def scaled_height; end
  def scaled_width; end
  def x_offset; end
  def x_scale; end
  def y_offset; end
  def y_scale; end
end

Writexlsx::MAX_URL_LENGTH = T.let(T.unsafe(nil), Integer)
Writexlsx::OFFICE_URL = T.let(T.unsafe(nil), String)
module Writexlsx::Package; end

class Writexlsx::Package::AboveAverageFormat < ::Writexlsx::Package::ConditionalFormat
  def attributes; end
end

class Writexlsx::Package::App
  include ::Writexlsx::Utility

  def initialize(workbook); end

  def add_chartsheet_heading_pairs; end
  def add_chartsheet_part_names; end
  def add_heading_pair(heading_pair); end
  def add_named_range_heading_pairs; end
  def add_named_ranges_parts; end
  def add_part_name(part_name); end
  def add_worksheet_heading_pairs; end
  def add_worksheet_part_names; end
  def assemble_xml_file; end
  def doc_security=(_arg0); end
  def set_properties(properties); end
  def set_xml_writer(filename); end

  private

  def write_app_version; end
  def write_application; end
  def write_company; end
  def write_doc_security; end
  def write_heading_pairs; end
  def write_hyperlink_base; end
  def write_hyperlinks_changed; end
  def write_links_up_to_date; end
  def write_manager; end
  def write_properties(&block); end
  def write_scale_crop; end
  def write_shared_doc; end
  def write_titles_of_parts; end
  def write_vt_data(type, data); end
  def write_vt_vector(base_type, data); end
end

class Writexlsx::Package::BlanksOrErrorsFormat < ::Writexlsx::Package::ConditionalFormat
  def write_cf_rule; end
end

class Writexlsx::Package::Button
  include ::Writexlsx::Utility

  def initialize(worksheet, row, col, params, default_row_pixels, button_number); end

  def color; end
  def fill_attributes; end
  def style_addition; end
  def type; end
  def v_shape_attributes(id, z_index); end
  def write_client_data; end
  def write_fmla_macro; end
  def write_print_object; end
  def write_rotation_lock; end
  def write_shape(writer, id, z_index); end
  def write_text_halign; end
  def write_text_valign; end
  def write_textbox; end
end

class Writexlsx::Package::CellIsFormat < ::Writexlsx::Package::ConditionalFormat
  def attributes; end
  def write_cf_rule; end
end

class Writexlsx::Package::ColorScaleFormat < ::Writexlsx::Package::ConditionalFormat
  def write_cf_rule; end
  def write_color_scale; end
end

class Writexlsx::Package::Comment
  include ::Writexlsx::Utility

  def initialize(workbook, worksheet, row, col, string, options = T.unsafe(nil)); end

  def author; end
  def author=(_arg0); end
  def backgrount_color(color); end
  def col; end
  def color; end
  def default_start_col(col); end
  def default_start_row(row); end
  def default_x_offset(col); end
  def default_y_offset(row); end
  def fill_attributes; end
  def font_family; end
  def font_name; end
  def font_size; end
  def rgb_color(rgb); end
  def row; end
  def string; end
  def style_addition; end
  def type; end
  def v_shape_attributes(id, z_index); end
  def vertices; end
  def visibility; end
  def visible; end
  def visible=(_arg0); end
  def write_client_data; end
  def write_shadow; end
  def write_shape(writer, id, z_index); end
  def write_textbox; end
  def writer=(_arg0); end

  private

  def options_parse(row, col, options); end
end

Writexlsx::Package::Comment::DEFAULT_COLOR = T.let(T.unsafe(nil), Integer)
Writexlsx::Package::Comment::DEFAULT_HEIGHT = T.let(T.unsafe(nil), Integer)
Writexlsx::Package::Comment::DEFAULT_WIDTH = T.let(T.unsafe(nil), Integer)

class Writexlsx::Package::Comments
  include ::Writexlsx::Utility

  def initialize(worksheet); end

  def [](row); end
  def add(workbook, worksheet, row, col, string, options); end
  def assemble_xml_file; end
  def empty?; end
  def has_comment_in_row?(row); end
  def set_xml_writer(filename); end
  def size; end
  def sorted_comments; end

  private

  def comments_visible?; end
  def write_author(data); end
  def write_authors(comment_data); end
  def write_color; end
  def write_comment(comment); end
  def write_comment_list(comment_data); end
  def write_comments(&block); end
  def write_family(val); end
  def write_r_font(val); end
  def write_r_pr(comment); end
  def write_sz(val); end
  def write_text(comment); end
  def write_text_r(comment); end
  def write_text_t(comment); end
end

class Writexlsx::Package::ConditionalFormat
  include ::Writexlsx::Utility

  def initialize(worksheet, range, param); end

  def attributes; end
  def bar_axis_color; end
  def bar_axis_position; end
  def bar_border_color; end
  def bar_color; end
  def bar_negative_color; end
  def bar_negative_color_same; end
  def bar_no_border; end
  def bar_only; end
  def criteria; end
  def direction; end
  def format; end
  def formula; end
  def icon_style; end
  def icons; end
  def icons_only; end
  def max_color; end
  def max_type; end
  def max_value; end
  def maximum; end
  def mid_color; end
  def mid_type; end
  def mid_value; end
  def min_color; end
  def min_type; end
  def min_value; end
  def minimum; end
  def priority; end
  def range; end
  def range_param_for_conditional_formatting(*args); end
  def reverse_icons; end
  def stop_if_true; end
  def total_icons; end
  def type; end
  def value; end
  def write_cf_rule; end
  def write_cf_rule_formula_tag(tag = T.unsafe(nil)); end
  def write_cfvo(type, value, criteria = T.unsafe(nil)); end
  def write_formula_tag(data); end

  private

  def check_conditional_formatting_parameters(param); end
  def convert_date_time_if_required(val); end
  def date_1904?; end
  def handling_of_blanks_error_types; end
  def handling_of_text_criteria; end
  def handling_of_time_period_criteria; end
  def icon_set_styles; end
  def palette_color(index); end
  def param_for_conditional_formatting(*args); end
  def range_start_cell_for_conditional_formatting(*args); end
  def row_col_param_for_conditional_formatting(*args); end
  def set_icon_properties(total_icons, user_props); end
  def valid_criteria_type_for_conditional_formatting; end
  def valid_parameter_for_conditional_formatting; end
  def valid_type_for_conditional_formatting; end

  class << self
    def factory(worksheet, *args); end
  end
end

class Writexlsx::Package::ContentTypes
  include ::Writexlsx::Utility

  def initialize(workbook); end

  def add_calc_chain; end
  def add_chart_name(name); end
  def add_chart_names; end
  def add_chartsheet_name(name); end
  def add_chartsheet_names; end
  def add_comment_name(name); end
  def add_comment_names; end
  def add_custom_properties; end
  def add_default(part_name, content_type); end
  def add_drawing_name(name); end
  def add_drawing_names; end
  def add_image_types; end
  def add_metadata; end
  def add_override(part_name, content_type); end
  def add_richvalue; end
  def add_shared_strings; end
  def add_table_name(table_name); end
  def add_table_names(table_count); end
  def add_vba_project; end
  def add_vml_name; end
  def add_worksheet_name(name); end
  def add_worksheet_names; end
  def assemble_xml_file; end
  def set_xml_writer(filename); end

  private

  def change_the_workbook_xml_content_type_from_xlsx_to_xlsm; end
  def write_default(extension, content_type); end
  def write_default_or_override(tag, param0, a); end
  def write_defaults; end
  def write_override(part_name, content_type); end
  def write_overrides; end
  def write_types(&block); end
end

Writexlsx::Package::ContentTypes::App_document = T.let(T.unsafe(nil), String)
Writexlsx::Package::ContentTypes::App_package = T.let(T.unsafe(nil), String)

class Writexlsx::Package::Core
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def set_properties(properties); end
  def set_xml_writer(filename); end

  private

  def datetime_to_iso8601_date(gm_time = T.unsafe(nil)); end
  def dcterms_date; end
  def write_base(key, tag, default = T.unsafe(nil)); end
  def write_cp_category; end
  def write_cp_content_status; end
  def write_cp_core_properties(&block); end
  def write_cp_core_properties_base; end
  def write_cp_keywords; end
  def write_cp_last_modified_by; end
  def write_dc_creator; end
  def write_dc_description; end
  def write_dc_subject; end
  def write_dc_title; end
  def write_dcterms(tag); end
  def write_dcterms_created; end
  def write_dcterms_modified; end
end

Writexlsx::Package::Core::App_document = T.let(T.unsafe(nil), String)
Writexlsx::Package::Core::App_package = T.let(T.unsafe(nil), String)

class Writexlsx::Package::Custom
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def set_properties(properties); end
  def set_xml_writer(filename); end

  private

  def write_properties; end
  def write_property(property); end
  def write_vt_bool(data); end
  def write_vt_filetime(data); end
  def write_vt_i4(data); end
  def write_vt_lpwstr(data); end
  def write_vt_r8(data); end
end

class Writexlsx::Package::DataBarFormat < ::Writexlsx::Package::ConditionalFormat
  def write_cf_rule; end
  def write_data_bar; end
  def write_data_bar_ext(param); end
end

class Writexlsx::Package::ExpressionFormat < ::Writexlsx::Package::ConditionalFormat
  def write_cf_rule; end
end

class Writexlsx::Package::IconSetFormat < ::Writexlsx::Package::ConditionalFormat
  def write_cf_rule; end
  def write_icon_set; end
end

class Writexlsx::Package::Metadata
  include ::Writexlsx::Utility

  def initialize(workbook); end

  def assemble_xml_file; end
  def has_dynamic_functions=(_arg0); end
  def num_embedded_images=(_arg0); end
  def set_xml_writer(filename); end

  private

  def write_cell_ext; end
  def write_cell_future_metadata; end
  def write_cell_metadata; end
  def write_cell_metadata_type; end
  def write_metadata; end
  def write_metadata_types; end
  def write_rc(type, value); end
  def write_value_ext(num); end
  def write_value_future_metadata; end
  def write_value_metadata; end
  def write_value_metadata_type; end
  def write_xda_dynamic_array_properties; end
  def write_xlrd_rvb(value); end
end

class Writexlsx::Package::Packager
  include ::Writexlsx::Utility

  def initialize(workbook); end

  def create_package; end
  def set_package_dir(package_dir); end

  private

  def add_image_files; end
  def add_vba_project; end
  def write_app_file; end
  def write_chart_files; end
  def write_chart_or_drawing_files(objects, filename); end
  def write_chartsheet_files; end
  def write_chartsheet_rels_files; end
  def write_comment_files; end
  def write_content_types_file; end
  def write_core_file; end
  def write_custom_file; end
  def write_drawing_files; end
  def write_drawing_rels_files; end
  def write_image_x_xml_files(image, index); end
  def write_metadata_file; end
  def write_rich_value_file; end
  def write_rich_value_files; end
  def write_rich_value_rel; end
  def write_rich_value_rels_files; end
  def write_rich_value_structure_file; end
  def write_rich_value_types_file; end
  def write_root_rels_file; end
  def write_shared_strings_file; end
  def write_styles_file; end
  def write_table_files; end
  def write_theme_file; end
  def write_vml_files; end
  def write_workbook_file; end
  def write_workbook_rels_file; end
  def write_worksheet_files; end
  def write_worksheet_rels_files; end
end

class Writexlsx::Package::Relationships
  include ::Writexlsx::Utility

  def initialize; end

  def add_document_relationship(type, target, target_mode = T.unsafe(nil)); end
  def add_ms_package_relationship(type, target); end
  def add_package_relationship(type, target); end
  def add_rich_value_relationships; end
  def add_worksheet_relationship(type, target, target_mode = T.unsafe(nil)); end
  def assemble_xml_file; end
  def set_xml_writer(filename); end

  private

  def write_relationship(type, target, target_mode = T.unsafe(nil)); end
  def write_relationships; end
end

Writexlsx::Package::Relationships::Document_schema = T.let(T.unsafe(nil), String)
Writexlsx::Package::Relationships::Package_schema = T.let(T.unsafe(nil), String)
Writexlsx::Package::Relationships::Schema_root = T.let(T.unsafe(nil), String)

class Writexlsx::Package::RichValue
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def embedded_images; end
  def embedded_images=(_arg0); end
  def set_xml_writer(filename); end

  private

  def write_rv(index, description, decorative); end
  def write_rv_data; end
  def write_v(data); end
end

class Writexlsx::Package::RichValueRel
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def set_xml_writer(filename); end
  def value_count=(_arg0); end

  private

  def write_rel(id); end
  def write_rich_value_rels; end
end

class Writexlsx::Package::RichValueStructure
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def has_embedded_descriptions=(_arg0); end
  def set_xml_writer(filename); end

  private

  def write_k(n, t); end
  def write_rv_structures; end
  def write_s; end
end

class Writexlsx::Package::RichValueTypes
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def set_xml_writer(filename); end

  private

  def write_flag(name); end
  def write_key(name, flags = T.unsafe(nil)); end
  def write_rv_types_info; end
end

class Writexlsx::Package::SharedStrings
  include ::Writexlsx::Utility

  def initialize; end

  def add(string); end
  def assemble_xml_file; end
  def empty?; end
  def index(string, params = T.unsafe(nil)); end
  def set_xml_writer(filename); end
  def string(index); end
  def strings; end

  private

  def add_c2_c3(string); end
  def total_count; end
  def unique_count; end
  def write_si(string); end
  def write_sst(&block); end
  def write_sst_strings; end
end

Writexlsx::Package::SharedStrings::PRESERVE_SPACE_ATTRIBUTES = T.let(T.unsafe(nil), Array)

class Writexlsx::Package::Styles
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def bg_and_fg_color(format, dxf_format); end
  def palette_color(index); end
  def pattern_only_case?(format, dxf_format); end
  def set_style_properties(xf_formats, palette, font_count, num_formats, border_count, fill_count, custom_colors, dxf_formats, has_comments); end
  def set_xml_writer(filename); end
  def write_border(format, dxf_format = T.unsafe(nil)); end
  def write_border_base(format, dxf_format); end
  def write_border_sub_elements(format); end
  def write_borders; end
  def write_borders_base; end
  def write_cell_style_xfs; end
  def write_cell_xfs; end
  def write_comment_font; end
  def write_default_fill(pattern_type); end
  def write_fill(format, dxf_format = T.unsafe(nil)); end
  def write_fill_base(format, dxf_format); end
  def write_fills; end
  def write_fills_base; end
  def write_font_base; end
  def write_fonts; end
  def write_format_elements(elements, count, &block); end
  def write_num_fmt(num_fmt_id, format_code); end
  def write_num_fmts; end
  def write_pattern_fill(format, dxf_format); end
  def write_style_sheet(&block); end
  def write_style_xf(has_hyperlink, font_id); end
  def write_sub_border(type, style = T.unsafe(nil), color = T.unsafe(nil)); end

  private

  def write_cell_style(name, xf_id, builtin_id); end
  def write_cell_styles; end
  def write_colors; end
  def write_condense; end
  def write_dxf(format); end
  def write_dxfs; end
  def write_extend; end
  def write_mru_colors(custom_colors); end
  def write_style_sheet_base; end
  def write_table_styles; end
  def write_xf(format); end
end

Writexlsx::Package::Styles::BORDER_STYLES = T.let(T.unsafe(nil), Array)
Writexlsx::Package::Styles::FORMAT_CODES = T.let(T.unsafe(nil), Hash)
Writexlsx::Package::Styles::PATTERNS = T.let(T.unsafe(nil), Array)

class Writexlsx::Package::Table
  include ::Writexlsx::Utility

  def initialize(worksheet, *args); end

  def add_the_table_columns; end
  def assemble_xml_file; end
  def id; end
  def name; end
  def overwrite_the_defaults_with_any_use_defined_values(col_id, col_data, col_num); end
  def prepare(id); end
  def set_xml_writer(filename); end
  def store_filter_cell_positions; end
  def write_any_columns_formulas_after_the_user_supplied_table_data; end
  def write_the_cell_data_if_supplied; end
  def write_the_column_headers_to_the_worksheet(col_num, col_data); end

  private

  def handle_args(row1, col1 = T.unsafe(nil), row2 = T.unsafe(nil), col2 = T.unsafe(nil), param = T.unsafe(nil)); end
  def handle_the_column_formula(col_data, _col_num, formula, _format); end
  def handle_the_function_for_the_table_row(row2, col_data, col_num, user_data); end
  def set_the_autofilter_range; end
  def set_the_table_and_autofilter_ranges; end
  def set_the_table_name; end
  def set_the_table_options; end
  def set_the_table_style; end
  def table_function_to_formula(function, col_name); end
  def total_label_only(row2, col_num, col_data, total_string, format); end
  def valid_table_parameter; end
  def write_auto_filter; end
  def write_calculated_column_formula(formula); end
  def write_table_attributes; end
  def write_table_column(col_data); end
  def write_table_columns; end
  def write_table_style_info; end
  def write_totals_row_formula(formula); end
end

class Writexlsx::Package::Table::ColumnData
  def initialize(id, param = T.unsafe(nil)); end

  def custom_total; end
  def custom_total=(_arg0); end
  def format; end
  def format=(_arg0); end
  def formula; end
  def formula=(_arg0); end
  def id; end
  def name; end
  def name=(_arg0); end
  def name_format; end
  def name_format=(_arg0); end
  def total_function; end
  def total_function=(_arg0); end
  def total_string; end
  def total_string=(_arg0); end
end

class Writexlsx::Package::TextOrWithFormat < ::Writexlsx::Package::ConditionalFormat
  def attributes; end
  def write_cf_rule; end
end

class Writexlsx::Package::Theme
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file; end
  def set_xml_writer(filename); end

  private

  def write_theme_file; end
end

class Writexlsx::Package::TimePeriodFormat < ::Writexlsx::Package::ConditionalFormat
  def attributes; end
  def write_cf_rule; end
end

class Writexlsx::Package::Top10Format < ::Writexlsx::Package::ConditionalFormat
  def attributes; end
end

class Writexlsx::Package::Vml
  include ::Writexlsx::Utility

  def initialize; end

  def assemble_xml_file(data_id, vml_shape_id, comments_data, buttons_data, header_images_data = T.unsafe(nil)); end
  def set_xml_writer(filename); end

  private

  def write_aspect_ratio_lock; end
  def write_button_path; end
  def write_button_shapetype; end
  def write_comment_shapetype; end
  def write_f(eqn); end
  def write_formulas; end
  def write_idmap(data_id); end
  def write_image_path; end
  def write_image_shape(id, index, image_property); end
  def write_image_shapetype; end
  def write_imagedata(image_property); end
  def write_rotation_lock; end
  def write_shape_type_and_shape(data, vml_shape_id, z_index); end
  def write_shapelayout(data_id); end
  def write_shapetype_lock; end
  def write_xml_namespace(&block); end
  def xml_attributes; end
end

class Writexlsx::Package::XMLWriterSimple
  def initialize; end

  def characters(data); end
  def close; end
  def crlf; end
  def data_element(tag, data, attr = T.unsafe(nil)); end
  def empty_tag(tag, attr = T.unsafe(nil)); end
  def end_tag(tag); end
  def end_tag_str(tag); end
  def io_write(str); end
  def set_xml_writer(filename = T.unsafe(nil)); end
  def si_element(data, attr); end
  def si_rich_element(data); end
  def start_tag(tag, attr = T.unsafe(nil)); end
  def start_tag_str(tag, attr = T.unsafe(nil)); end
  def string; end
  def tag_elements(tag, attributes = T.unsafe(nil)); end
  def tag_elements_str(tag, attributes = T.unsafe(nil)); end
  def xml_decl(encoding = T.unsafe(nil), standalone = T.unsafe(nil)); end

  private

  def escape_attributes(str = T.unsafe(nil)); end
  def escape_data(str = T.unsafe(nil)); end
  def key_vals(attribute); end
end

Writexlsx::Package::XMLWriterSimple::XMLNS = T.let(T.unsafe(nil), String)

class Writexlsx::Shape
  include ::Writexlsx::Utility

  def initialize(properties = T.unsafe(nil)); end

  def adjustments; end
  def adjustments=(args); end
  def align; end
  def anchor; end
  def auto_locate_connectors(shapes, shape_hash); end
  def calc_position_emus(worksheet); end
  def column_end; end
  def column_end=(_arg0); end
  def column_start; end
  def column_start=(_arg0); end
  def connect; end
  def connect=(_arg0); end
  def dimensions; end
  def drawing; end
  def edit_as; end
  def element; end
  def element=(_arg0); end
  def end; end
  def end=(_arg0); end
  def end_index; end
  def end_index=(_arg0); end
  def end_side; end
  def end_side=(_arg0); end
  def fill; end
  def flip_h; end
  def flip_h=(_arg0); end
  def flip_v; end
  def flip_v=(_arg0); end
  def format; end
  def height; end
  def height=(_arg0); end
  def height_emu; end
  def height_emu=(_arg0); end
  def id; end
  def id=(_arg0); end
  def line; end
  def line_type; end
  def line_type=(_arg0); end
  def line_weight; end
  def line_weight=(_arg0); end
  def name; end
  def name=(_arg0); end
  def palette; end
  def palette=(_arg0); end
  def rotation; end
  def rotation=(_arg0); end
  def row_end; end
  def row_end=(_arg0); end
  def row_start; end
  def row_start=(_arg0); end
  def scale_x; end
  def scale_x=(_arg0); end
  def scale_y; end
  def scale_y=(_arg0); end
  def set_position(row_start, column_start, x_offset, y_offset, x_scale, y_scale, anchor); end
  def set_properties(properties); end
  def start; end
  def start=(_arg0); end
  def start_index; end
  def start_index=(_arg0); end
  def start_side; end
  def start_side=(_arg0); end
  def stencil; end
  def stencil=(_arg0); end
  def text; end
  def text=(_arg0); end
  def tx_box; end
  def type; end
  def type=(_arg0); end
  def validate(index); end
  def valign; end
  def width; end
  def width=(_arg0); end
  def width_emu; end
  def width_emu=(_arg0); end
  def x1; end
  def x1=(_arg0); end
  def x2; end
  def x2=(_arg0); end
  def x_abs; end
  def x_abs=(_arg0); end
  def x_offset; end
  def x_offset=(_arg0); end
  def y1; end
  def y1=(_arg0); end
  def y2; end
  def y2=(_arg0); end
  def y_abs; end
  def y_abs=(_arg0); end
  def y_offset; end
  def y_offset=(_arg0); end
end

class Writexlsx::Sheets
  include ::Writexlsx::Utility

  def initialize; end

  def chartname_count; end
  def chartsheet_count; end
  def chartsheets; end
  def index_by_name(sheetname); end
  def make_and_check_sheet_chart_name(type, name); end
  def sheetname_count; end
  def tables; end
  def tables_count; end
  def visible_first; end
  def worksheets; end
  def write_chartsheet_files(package_dir); end
  def write_chartsheet_rels_files(package_dir); end
  def write_comment_files(package_dir); end
  def write_drawing_rels_files(package_dir); end
  def write_sheet_rels_files_base(sheets, dir, body); end
  def write_sheets(writer); end
  def write_table_files(package_dir); end
  def write_vml_drawing_rels_files(package_dir, worksheet, index); end
  def write_vml_files(package_dir); end
  def write_worksheet_files(package_dir); end
  def write_worksheet_rels_files(package_dir); end

  private

  def check_valid_sheetname(name); end
  def is_sheetname_uniq?(name); end
  def sheet_chart_count(type); end
  def write_sheet(writer, sheet, sheet_id); end
  def write_sheet_files(dir, sheet, index); end
end

Writexlsx::Sheets::BASE_NAME = T.let(T.unsafe(nil), Hash)

class Writexlsx::Sparkline
  include ::Writexlsx::Utility

  def initialize(ws, param, sheetname); end

  def count; end
  def group_attributes; end
  def write_sparkline_group(writer); end

  private

  def cust_max_min(max_min); end
  def set_spark_color(user_color, palette_color); end
  def spark_styles; end
  def valid_sparkline_parameter; end
  def write; end
  def write_color_axis; end
  def write_color_first; end
  def write_color_high; end
  def write_color_last; end
  def write_color_low; end
  def write_color_markers; end
  def write_color_negative; end
  def write_color_series; end
  def write_spark_color(element, color); end
  def write_sparklines; end
  def write_xmf_date_axis; end
end

class Writexlsx::Table
  include ::Writexlsx::Utility

  def initialize(params = T.unsafe(nil)); end

  def font; end
  def horizontal; end
  def outline; end
  def palette=(_arg0); end
  def show_keys; end
  def vertical; end
  def write_d_table(writer); end

  private

  def attributes; end
end

module Writexlsx::Utility
  def absolute_char(absolute); end
  def check_dimensions(row, col); end
  def check_dimensions_and_update_max_min_values(row, col, ignore_row = T.unsafe(nil), ignore_col = T.unsafe(nil)); end
  def check_parameter(params, valid_keys, method); end
  def color(color_code); end
  def convert_date_time(date_time_string); end
  def convert_font_args(params); end
  def dash_types; end
  def escape_url(url); end
  def fill_properties(fill); end
  def float_to_str(float); end
  def get_font_latin_attributes(font); end
  def get_font_style_attributes(font); end
  def layout_properties(args, is_text = T.unsafe(nil)); end
  def legend_properties(params); end
  def line_fill_properties(params); end
  def line_properties(line); end
  def palette_color_from_index(index); end
  def params_to_font(params); end
  def pattern_properties(args); end
  def pixels_to_points(vertices); end
  def ptrue?(value); end
  def put_deprecate_message(method); end
  def quote_sheetname(sheetname); end
  def r_id_attributes(id); end
  def row_col_notation(row_or_a1); end
  def shape_style_base(left_str, top_str, width_str, height_str, z_index_str); end
  def store_col_max_min_values(col); end
  def store_row_max_min_values(row); end
  def substitute_cellref(cell, *args); end
  def underline_attributes(underline); end
  def v_shape_attributes_base(id); end
  def v_shape_style_base(z_index, vertices); end
  def value_or_raise(hash, key, msg); end
  def write_a_body_pr(rot, is_y_axis = T.unsafe(nil)); end
  def write_a_def_rpr(font = T.unsafe(nil)); end
  def write_a_end_para_rpr; end
  def write_a_lst_style; end
  def write_a_p_formula(font = T.unsafe(nil)); end
  def write_a_p_pr_formula(font); end
  def write_a_solid_fill(fill); end
  def write_a_srgb_clr(color, transparency = T.unsafe(nil)); end
  def write_anchor; end
  def write_auto_fill; end
  def write_color(name, value, writer = T.unsafe(nil)); end
  def write_comment_path(gradientshapeok, connecttype); end
  def write_def_rpr_r_pr_common(font, style_attributes, tag); end
  def write_div(align, font = T.unsafe(nil)); end
  def write_fill; end
  def write_font(font); end
  def write_stroke; end
  def write_tx_pr(font, is_y_axis = T.unsafe(nil)); end
  def write_xml_declaration; end
  def xl_cell_to_rowcol(cell); end
  def xl_col_to_name(col, col_absolute); end
  def xl_range(row_1, row_2, col_1, col_2, row_abs_1 = T.unsafe(nil), row_abs_2 = T.unsafe(nil), col_abs_1 = T.unsafe(nil), col_abs_2 = T.unsafe(nil)); end
  def xl_range_formula(sheetname, row_1, row_2, col_1, col_2); end
  def xl_rowcol_to_cell(row_or_name, col, row_absolute = T.unsafe(nil), col_absolute = T.unsafe(nil)); end
  def xl_string_pixel_width(string); end
  def xml_str; end

  class << self
    def delete_files(path); end
  end
end

Writexlsx::Utility::CHAR_WIDTHS = T.let(T.unsafe(nil), Hash)
Writexlsx::Utility::COL_MAX = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::DEFAULT_COL_PIXELS = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::MAX_DIGIT_WIDTH = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::PADDING = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::PERL_TRUE_VALUES = T.let(T.unsafe(nil), Array)
Writexlsx::Utility::ROW_MAX = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::SHEETNAME_MAX = T.let(T.unsafe(nil), Integer)
Writexlsx::Utility::STR_MAX = T.let(T.unsafe(nil), Integer)

class Writexlsx::Workbook
  include ::Writexlsx::Utility

  def initialize(file, *option_params); end

  def activesheet; end
  def activesheet=(_arg0); end
  def add_chart(params = T.unsafe(nil)); end
  def add_format(property_hash = T.unsafe(nil)); end
  def add_shape(properties = T.unsafe(nil)); end
  def add_vba_project(vba_project); end
  def add_worksheet(name = T.unsafe(nil)); end
  def assemble_xml_file; end
  def charts; end
  def charts=(_arg0); end
  def chartsheet_count; end
  def chartsheets; end
  def close; end
  def custom_properties; end
  def date_1904?; end
  def default_url_format; end
  def define_name(name, formula); end
  def doc_properties; end
  def drawings; end
  def drawings=(_arg0); end
  def embedded_descriptions; end
  def embedded_image_indexes; end
  def embedded_images; end
  def excel2003_style; end
  def firstsheet; end
  def firstsheet=(_arg0); end
  def get_1904; end
  def get_default_url_format; end
  def get_worksheet_by_name(sheetname = T.unsafe(nil)); end
  def has_dynamic_functions?; end
  def has_embedded_descriptions=(_arg0); end
  def has_embedded_descriptions?; end
  def has_embedded_images?; end
  def has_metadata?; end
  def image_types; end
  def images; end
  def max_url_length; end
  def named_ranges; end
  def non_chartsheet_count; end
  def non_chartsheets; end
  def num_comment_files; end
  def num_vml_files; end
  def palette; end
  def read_only; end
  def read_only_recommended; end
  def set_1904(mode = T.unsafe(nil)); end
  def set_calc_mode(mode, calc_id = T.unsafe(nil)); end
  def set_custom_color(index, red = T.unsafe(nil), green = T.unsafe(nil), blue = T.unsafe(nil)); end
  def set_custom_property(name, value, type = T.unsafe(nil)); end
  def set_properties(params); end
  def set_size(width = T.unsafe(nil), height = T.unsafe(nil)); end
  def set_tab_ratio(tab_ratio = T.unsafe(nil)); end
  def set_tempdir(dir); end
  def set_vba_name(vba_codename = T.unsafe(nil)); end
  def set_xml_writer(filename); end
  def shared_string_index(str); end
  def shared_strings; end
  def shared_strings_empty?; end
  def sheets(*args); end
  def store_image_types(type); end
  def str_unique; end
  def strings_to_urls; end
  def style_properties; end
  def vba_project; end
  def worksheet_by_name(sheetname = T.unsafe(nil)); end
  def worksheets; end
  def writer; end
  def xml_str; end

  private

  def add_chart_data; end
  def chart_data(worksheet, cells); end
  def check_chart_sheetname(name); end
  def check_sheetname(name); end
  def defined_names; end
  def eq_0?(val); end
  def extract_named_ranges(defined_names); end
  def filename; end
  def fileobj; end
  def get_chart_range(range); end
  def ne_0?(val); end
  def normalise_defined_name(name); end
  def normalise_sheet_name(name); end
  def prepare_borders; end
  def prepare_defined_names; end
  def prepare_drawings; end
  def prepare_drawings_of_all_sheets; end
  def prepare_fills; end
  def prepare_fonts; end
  def prepare_format_properties; end
  def prepare_formats; end
  def prepare_metadata; end
  def prepare_num_formats; end
  def prepare_sst_string_data; end
  def prepare_tables; end
  def prepare_vml_objects; end
  def process_workbook_options(*params); end
  def set_color_palette; end
  def setup_filename; end
  def sort_defined_names(names); end
  def store_workbook; end
  def tempdir; end
  def write_book_views; end
  def write_calc_pr; end
  def write_defined_name(defined_name); end
  def write_defined_names; end
  def write_ext; end
  def write_ext_lst; end
  def write_file_sharing; end
  def write_file_version; end
  def write_io(str); end
  def write_mx_arch_id; end
  def write_workbook(&block); end
  def write_workbook_pr; end
  def write_workbook_view; end
  def zip_entry_for_part(part); end
end

Writexlsx::Workbook::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

class Writexlsx::Worksheet
  include ::Writexlsx::Utility

  def initialize(workbook, index, name); end

  def activate; end
  def add_sparkline(param); end
  def add_table(*args); end
  def assemble_xml_file; end
  def autofilter(row1, col1 = T.unsafe(nil), row2 = T.unsafe(nil), col2 = T.unsafe(nil)); end
  def autofilter_area; end
  def autofit; end
  def background_image; end
  def buttons_data; end
  def center_horizontally; end
  def center_vertically; end
  def charts; end
  def col_info; end
  def comments; end
  def comments_author; end
  def comments_author=(author); end
  def comments_visible?; end
  def conditional_formatting(*args); end
  def data_bars_2010; end
  def data_bars_2010=(_arg0); end
  def data_validation(*args); end
  def date_1904?; end
  def default_row_height; end
  def default_row_height=(_arg0); end
  def drawing_links; end
  def drawings; end
  def dxf_priority; end
  def dxf_priority=(_arg0); end
  def embed_image(row, col, filename, options = T.unsafe(nil)); end
  def excel2003_style?; end
  def excel_version=(_arg0); end
  def external_links; end
  def filter_cells; end
  def filter_column(col, expression); end
  def filter_column_list(col, *tokens); end
  def fit_to_pages(width = T.unsafe(nil), height = T.unsafe(nil)); end
  def footer_images; end
  def freeze_panes(*args); end
  def get_range_data(row_start, col_start, row_end, col_end); end
  def has_comments?; end
  def has_dynamic_functions?; end
  def has_embedded_images?; end
  def has_header_vml?; end
  def has_shapes?; end
  def has_vml?; end
  def header_images; end
  def header_images_data; end
  def hidden?; end
  def hide(hidden = T.unsafe(nil)); end
  def hide_gridlines(option = T.unsafe(nil)); end
  def hide_row_col_headers; end
  def hide_zero(flag = T.unsafe(nil)); end
  def horizontal_dpi=(val); end
  def ignore_errors(ignores); end
  def images; end
  def index; end
  def insert_button(row, col, properties = T.unsafe(nil)); end
  def insert_chart(row, col, chart = T.unsafe(nil), *options); end
  def insert_image(row, col, image = T.unsafe(nil), *options); end
  def insert_shape(row_start, column_start, shape = T.unsafe(nil), x_offset = T.unsafe(nil), y_offset = T.unsafe(nil), x_scale = T.unsafe(nil), y_scale = T.unsafe(nil), anchor = T.unsafe(nil)); end
  def is_chartsheet?; end
  def keep_leading_zeros(flag = T.unsafe(nil)); end
  def margin_bottom=(margin); end
  def margin_left=(margin); end
  def margin_right=(margin); end
  def margin_top=(margin); end
  def margins=(margin); end
  def margins_left_right=(margin); end
  def margins_top_bottom=(margin); end
  def merge_range(*args); end
  def merge_range_type(type, *args); end
  def name; end
  def num_comments_block; end
  def outline_settings(visible = T.unsafe(nil), symbols_below = T.unsafe(nil), symbols_right = T.unsafe(nil), auto_style = T.unsafe(nil)); end
  def palette_color(index); end
  def paper=(paper_size); end
  def position_object_pixels(col_start, row_start, x1, y1, width, height, anchor = T.unsafe(nil)); end
  def prepare_chart(index, chart_id, drawing_id); end
  def prepare_drawings(drawing_id, chart_ref_id, image_ref_id, image_ids, header_image_ids, background_ids); end
  def prepare_formula(given_formula, expand_future_functions = T.unsafe(nil)); end
  def prepare_header_vml_objects(vml_header_id, vml_drawing_id); end
  def prepare_tables(table_id, seen); end
  def prepare_vml_objects(vml_data_id, vml_shape_id, vml_drawing_id, comment_id); end
  def print_across(across = T.unsafe(nil)); end
  def print_area(*args); end
  def print_black_and_white; end
  def print_repeat_cols; end
  def print_repeat_rows; end
  def print_row_col_headers(headers = T.unsafe(nil)); end
  def print_scale=(scale = T.unsafe(nil)); end
  def protect(password = T.unsafe(nil), options = T.unsafe(nil)); end
  def repeat_columns(*args); end
  def repeat_formula(row, col, formula, format, *pairs); end
  def repeat_rows(row_min, row_max = T.unsafe(nil)); end
  def right_to_left(flag = T.unsafe(nil)); end
  def row_sizes; end
  def select; end
  def set_background(image); end
  def set_column(*args); end
  def set_column_pixels(*data); end
  def set_comments_author(author); end
  def set_default_row(height = T.unsafe(nil), zero_height = T.unsafe(nil)); end
  def set_first_sheet; end
  def set_footer(string = T.unsafe(nil), margin = T.unsafe(nil), options = T.unsafe(nil)); end
  def set_h_pagebreaks(*args); end
  def set_header(string = T.unsafe(nil), margin = T.unsafe(nil), options = T.unsafe(nil)); end
  def set_landscape; end
  def set_margin_bottom(margin = T.unsafe(nil)); end
  def set_margin_left(margin = T.unsafe(nil)); end
  def set_margin_right(margin = T.unsafe(nil)); end
  def set_margin_top(margin = T.unsafe(nil)); end
  def set_margins(margin); end
  def set_margins_LR(margin); end
  def set_margins_TB(margin); end
  def set_page_view(flag = T.unsafe(nil)); end
  def set_pagebreak_view; end
  def set_paper(paper_size); end
  def set_portrait; end
  def set_print_scale(scale = T.unsafe(nil)); end
  def set_row(*args); end
  def set_row_pixels(*data); end
  def set_rows; end
  def set_selection(*args); end
  def set_start_page(page_start); end
  def set_tab_color(color); end
  def set_top_left_cell(row, col = T.unsafe(nil)); end
  def set_v_pagebreaks(*args); end
  def set_vba_name(vba_codename = T.unsafe(nil)); end
  def set_xml_writer(filename); end
  def set_zoom(scale); end
  def shapes; end
  def show_comments(visible = T.unsafe(nil)); end
  def some_image_or_drawing_to_be_processed?; end
  def sorted_comments; end
  def split_panes(*args); end
  def start_page=(page_start); end
  def store_formula(string); end
  def tab_color=(color); end
  def tables; end
  def tables_count; end
  def unprotect_range(range, range_name = T.unsafe(nil), password = T.unsafe(nil)); end
  def update_format_with_params(row, col, params = T.unsafe(nil)); end
  def update_range_format_with_params(row_first, col_first, row_last = T.unsafe(nil), col_last = T.unsafe(nil), params = T.unsafe(nil)); end
  def vba_codename; end
  def vertical_dpi=(val); end
  def very_hidden; end
  def very_hidden?; end
  def vml_data_id; end
  def vml_drawing_links; end
  def vml_header_id; end
  def vml_shape_id; end
  def write(row, col, token = T.unsafe(nil), format = T.unsafe(nil), value1 = T.unsafe(nil), value2 = T.unsafe(nil)); end
  def write_array_formula(row1, col1, row2 = T.unsafe(nil), col2 = T.unsafe(nil), formula = T.unsafe(nil), format = T.unsafe(nil), value = T.unsafe(nil)); end
  def write_array_formula_base(type, *args); end
  def write_blank(row, col, format = T.unsafe(nil)); end
  def write_boolean(row, col, val = T.unsafe(nil), format = T.unsafe(nil)); end
  def write_cell_array_formula(formula, range); end
  def write_cell_formula(formula = T.unsafe(nil)); end
  def write_cell_value(value = T.unsafe(nil)); end
  def write_col(row, col, tokens = T.unsafe(nil), *options); end
  def write_comment(row, col, string = T.unsafe(nil), options = T.unsafe(nil)); end
  def write_date_time(row, col, str, format = T.unsafe(nil)); end
  def write_dynamic_array_formula(row1, col1, row2 = T.unsafe(nil), col2 = T.unsafe(nil), formula = T.unsafe(nil), format = T.unsafe(nil), value = T.unsafe(nil)); end
  def write_ext(url, &block); end
  def write_formula(row, col, formula = T.unsafe(nil), format = T.unsafe(nil), value = T.unsafe(nil)); end
  def write_number(row, col, number, format = T.unsafe(nil)); end
  def write_rich_string(row, col, *rich_strings); end
  def write_row(row, col, tokens = T.unsafe(nil), *options); end
  def write_sparkline_groups; end
  def write_string(row, col, string = T.unsafe(nil), format = T.unsafe(nil)); end
  def write_url(row, col, url = T.unsafe(nil), format = T.unsafe(nil), str = T.unsafe(nil), tip = T.unsafe(nil), ignore_write_string = T.unsafe(nil)); end
  def writer; end
  def zoom=(scale); end

  private

  def autofilter_ref?; end
  def calc_spans(data, row_num, span_min, span_max); end
  def calculate_spans; end
  def calculate_x_split_width(width); end
  def cell_format_of_rich_string(rich_strings); end
  def col_info_attributes(args); end
  def compare_col_info(col_options, previous_options); end
  def convert_name_area(row_num_1, col_num_1, row_num_2, col_num_2); end
  def drawing_rel_index(target = T.unsafe(nil)); end
  def drawings?; end
  def encode_password(password); end
  def expand_formula(formula, function, addition = T.unsafe(nil)); end
  def extract_filter_tokens(expression = T.unsafe(nil)); end
  def filter_on?; end
  def fit_page?; end
  def get_vml_drawing_rel_index(target); end
  def hyperlinks_count; end
  def increment_rel_id_and_write_r_id(tag); end
  def not_contain_formatting_or_data?(row_num); end
  def outline_changed?; end
  def parse_filter_expression(expression, tokens); end
  def parse_filter_tokens(expression, tokens); end
  def pixels_to_height(pixels); end
  def pixels_to_width(pixels); end
  def position_object_emus(graphical_object); end
  def prepare_background(image_id, image_type); end
  def prepare_background_image(background_ids, image_ref_id); end
  def prepare_filter_column(col); end
  def prepare_header_footer_image(image, header_image_ids, image_ref_id); end
  def prepare_header_image(image_id, image_property); end
  def prepare_image(image, drawing_id, image_ids, image_ref_id); end
  def prepare_shape(index, drawing_id); end
  def protect?; end
  def protect_default_settings; end
  def remove_white_space(margin); end
  def rich_strings_fragments(rich_strings); end
  def right_to_left?; end
  def row_attributes(args); end
  def set_active_pane_and_cell_selections(row, col, top_row, left_col, active_cell, sqref); end
  def set_external_comment_links(comment_id); end
  def set_external_vml_links(vml_drawing_id); end
  def shared_string_index(str); end
  def show_zeros?; end
  def size_col(col, anchor = T.unsafe(nil)); end
  def size_row(row, anchor = T.unsafe(nil)); end
  def sort_pagebreaks(*args); end
  def sparkline_groups_attributes; end
  def store_data_to_table(cell_data, row, col); end
  def store_hyperlink(row, col, hyperlink); end
  def store_row_col_max_min_values(row, col); end
  def tab_color?; end
  def tab_outline_fit?; end
  def vba_codename?; end
  def write_auto_filter; end
  def write_autofilters; end
  def write_breaks(tag); end
  def write_brk(id, max); end
  def write_cell_column_dimension(row_num); end
  def write_col_breaks; end
  def write_col_info(args); end
  def write_cols; end
  def write_conditional_formats; end
  def write_conditional_formatting(range, cond_formats); end
  def write_conditional_formatting_2010(data_bar); end
  def write_custom_filter(operator, val); end
  def write_custom_filters(*tokens); end
  def write_data_validations; end
  def write_dimension; end
  def write_drawings; end
  def write_empty_row(*args); end
  def write_ext_list; end
  def write_ext_list_data_bars; end
  def write_ext_list_sparklines; end
  def write_filter(val); end
  def write_filter_column(col_id, type, *filters); end
  def write_filters(*filters); end
  def write_formatted_blank_to_area(row_first, row_last, col_first, col_last, format); end
  def write_freeze_panes(row, col, top_row, left_col, type); end
  def write_header_footer; end
  def write_hyperlinks; end
  def write_ignored_error(type, sqref); end
  def write_ignored_errors; end
  def write_legacy_drawing; end
  def write_legacy_drawing_hf; end
  def write_merge_cell(merged_range); end
  def write_merge_cells; end
  def write_outline_pr; end
  def write_page_margins; end
  def write_page_set_up_pr; end
  def write_page_setup; end
  def write_panes; end
  def write_phonetic_pr; end
  def write_picture; end
  def write_print_options; end
  def write_protected_range(sqref, name, password); end
  def write_protected_ranges; end
  def write_r_id(tag, id); end
  def write_row_breaks; end
  def write_row_element(*args, &block); end
  def write_rows; end
  def write_selection(pane, active_cell, sqref); end
  def write_selections; end
  def write_sheet_calc_pr; end
  def write_sheet_data; end
  def write_sheet_format_pr; end
  def write_sheet_pr; end
  def write_sheet_protection; end
  def write_sheet_view; end
  def write_sheet_views; end
  def write_some_elements(tag, container, &block); end
  def write_sparklines(sparkline); end
  def write_split_panes; end
  def write_tab_color; end
  def write_table_part(id); end
  def write_table_parts; end
  def write_underline(writer, underline); end
  def write_worksheet_attributes; end
  def write_x14_axis_color(rgb); end
  def write_x14_border_color(rgb); end
  def write_x14_cf_rule(data_bar); end
  def write_x14_cfvo(type, value); end
  def write_x14_data_bar(data_bar); end
  def write_x14_negative_border_color(rgb); end
  def write_x14_negative_fill_color(rgb); end
  def xml_str_of_rich_string(fragments); end
  def zoom_scale_normal?; end
end

class Writexlsx::Worksheet::BlankCellData < ::Writexlsx::Worksheet::CellData
  def initialize(xf); end

  def data; end
  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::BooleanCellData < ::Writexlsx::Worksheet::CellData
  def initialize(val, xf); end

  def data; end
  def token; end
  def write_cell(worksheet, row, row_name, col); end
end

Writexlsx::Worksheet::COLINFO = Struct

class Writexlsx::Worksheet::CellData
  include ::Writexlsx::Utility

  def cell_attributes(worksheet, row, row_name, col); end
  def display_url_string?; end
  def xf; end
end

class Writexlsx::Worksheet::DataValidation
  include ::Writexlsx::Utility

  def initialize(*args); end

  def cells; end
  def criteria; end
  def dropdown; end
  def error_message; end
  def error_title; end
  def error_type; end
  def ignore_blank; end
  def input_message; end
  def input_title; end
  def keys; end
  def maximum; end
  def minimum; end
  def options_to_instance_variable(params); end
  def other_cells; end
  def show_error; end
  def show_input; end
  def source; end
  def validate; end
  def validate_none?; end
  def value; end
  def write_data_validation(writer); end

  private

  def attributes; end
  def check_criteria_required; end
  def check_for_valid_input_params; end
  def check_maximum_value_when_criteria_is_between_or_notbetween; end
  def check_valid_citeria_types; end
  def convert_date_time_value_if_required; end
  def date_1904?; end
  def error_type_hash; end
  def has_key?(key); end
  def set_some_defaults; end
  def valid_criteria_type; end
  def valid_validation_parameter; end
  def valid_validation_type; end
  def write_formula_1(formula); end
  def write_formula_2(formula); end
end

class Writexlsx::Worksheet::DateTimeCellData < ::Writexlsx::Worksheet::NumberCellData; end

class Writexlsx::Worksheet::DynamicFormulaArrayCellData < ::Writexlsx::Worksheet::CellData
  def initialize(formula, xf, range, result); end

  def data; end
  def link_type; end
  def range; end
  def result; end
  def token; end
  def url; end
  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::EmbedImageCellData < ::Writexlsx::Worksheet::CellData
  def initialize(image_index, xf); end

  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::ExternalHyperlink < ::Writexlsx::Worksheet::Hyperlink
  def initialize(url, str, tip, max_url_length); end
end

class Writexlsx::Worksheet::FormulaArrayCellData < ::Writexlsx::Worksheet::CellData
  def initialize(formula, xf, range, result); end

  def data; end
  def link_type; end
  def range; end
  def result; end
  def token; end
  def url; end
  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::FormulaCellData < ::Writexlsx::Worksheet::CellData
  def initialize(formula, xf, result); end

  def data; end
  def link_type; end
  def range; end
  def result; end
  def token; end
  def url; end
  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::Hyperlink
  include ::Writexlsx::Utility

  def initialize(url, str, tip, max_url_length); end

  def attributes(row, col, id); end
  def display_on; end
  def external_hyper_link; end
  def str; end
  def tip; end

  class << self
    def factory(url, str = T.unsafe(nil), tip = T.unsafe(nil), max_url_length = T.unsafe(nil)); end
  end
end

Writexlsx::Worksheet::Hyperlink::MAXIMUM_URLS_SIZE = T.let(T.unsafe(nil), Integer)

class Writexlsx::Worksheet::InternalHyperlink < ::Writexlsx::Worksheet::Hyperlink
  def initialize(url, str, tip, max_url_length); end

  def attributes(row, col, _dummy = T.unsafe(nil)); end
end

class Writexlsx::Worksheet::NumberCellData < ::Writexlsx::Worksheet::CellData
  def initialize(num, xf); end

  def data; end
  def token; end
  def write_cell(worksheet, row, row_name, col); end
end

class Writexlsx::Worksheet::PageSetup
  include ::Writexlsx::Utility

  def initialize; end

  def across=(_arg0); end
  def black_white; end
  def black_white=(_arg0); end
  def center_horizontally; end
  def center_vertically; end
  def fit_height; end
  def fit_height=(_arg0); end
  def fit_page; end
  def fit_page=(_arg0); end
  def fit_width; end
  def fit_width=(_arg0); end
  def footer; end
  def footer=(_arg0); end
  def hbreaks; end
  def hbreaks=(_arg0); end
  def header; end
  def header=(_arg0); end
  def header_footer_aligns; end
  def header_footer_aligns=(_arg0); end
  def header_footer_changed; end
  def header_footer_changed=(_arg0); end
  def header_footer_scales; end
  def header_footer_scales=(_arg0); end
  def hide_gridlines(option); end
  def horizontal_dpi=(_arg0); end
  def margin_bottom; end
  def margin_bottom=(_arg0); end
  def margin_footer; end
  def margin_footer=(_arg0); end
  def margin_header; end
  def margin_header=(_arg0); end
  def margin_left; end
  def margin_left=(_arg0); end
  def margin_right; end
  def margin_right=(_arg0); end
  def margin_top; end
  def margin_top=(_arg0); end
  def orientation; end
  def orientation=(_arg0); end
  def page_setup_changed; end
  def page_setup_changed=(_arg0); end
  def page_start=(_arg0); end
  def paper=(paper_size); end
  def print_area; end
  def print_area=(_arg0); end
  def print_options_changed; end
  def print_options_changed=(_arg0); end
  def print_row_col_headers(headers); end
  def repeat_cols; end
  def repeat_cols=(_arg0); end
  def repeat_rows; end
  def repeat_rows=(_arg0); end
  def scale; end
  def scale=(_arg0); end
  def vbreaks; end
  def vbreaks=(_arg0); end
  def vertical_dpi=(_arg0); end
  def write_header_footer(writer, excel2003_style); end
  def write_page_margins(writer); end
  def write_page_setup(writer); end
  def write_print_options(writer); end

  private

  def margin_attributes; end
  def write_odd_footer(writer); end
  def write_odd_header(writer); end
end

class Writexlsx::Worksheet::RichStringCellData < ::Writexlsx::Worksheet::StringCellData; end

class Writexlsx::Worksheet::StringCellData < ::Writexlsx::Worksheet::CellData
  def initialize(index, xf, raw_string); end

  def data; end
  def display_url_string?; end
  def raw_string; end
  def token; end
  def write_cell(worksheet, row, row_name, col); end
end

Writexlsx::Worksheet::StringCellData::TYPE_STR_ATTRS = T.let(T.unsafe(nil), Array)

module Writexlsx::WriteDPtPoint
  def write_d_pt_point(index, point); end
end

module ZipFileUtils
  class << self
    def each_dir_for(dir_path, &block); end
    def each_file_for(path, &block); end
    def encode_path(path, encode_s); end
    def relative(path, base_dir); end
    def unzip(src, dest, options = T.unsafe(nil)); end
    def zip(src, dest, options = T.unsafe(nil)); end
  end
end
