# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `asciidoctor` gem.
# Please instead update this file by running `bin/tapioca gem asciidoctor`.


class Array
  include ::Enumerable

  def nil_or_empty?; end
end

module Asciidoctor
  class << self
    def const_missing(name); end
    def convert(input, options = T.unsafe(nil)); end
    def convert_file(filename, options = T.unsafe(nil)); end
    def load(input, options = T.unsafe(nil)); end
    def load_file(filename, options = T.unsafe(nil)); end
    def render(input, options = T.unsafe(nil)); end
    def render_file(filename, options = T.unsafe(nil)); end
  end
end

Asciidoctor::ADMONITION_STYLES = T.let(T.unsafe(nil), Set)
Asciidoctor::ADMONITION_STYLE_HEADS = T.let(T.unsafe(nil), Set)
Asciidoctor::ASCIIDOC_EXTENSIONS = T.let(T.unsafe(nil), Hash)
Asciidoctor::ATTR_REF_HEAD = T.let(T.unsafe(nil), String)

class Asciidoctor::AbstractBlock < ::Asciidoctor::AbstractNode
  def initialize(parent, context, opts = T.unsafe(nil)); end

  def <<(block); end
  def alt; end
  def append(block); end
  def assign_caption(value, caption_context = T.unsafe(nil)); end
  def assign_numeral(section); end
  def block?; end
  def blocks; end
  def blocks?; end
  def caption; end
  def caption=(_arg0); end
  def captioned_title; end
  def content; end
  def content_model; end
  def content_model=(_arg0); end
  def context=(context); end
  def convert; end
  def file; end
  def find_by(selector = T.unsafe(nil), &block); end
  def inline?; end
  def level; end
  def level=(_arg0); end
  def lineno; end
  def list_marker_keyword(list_type = T.unsafe(nil)); end
  def next_adjacent_block; end
  def number; end
  def number=(val); end
  def numeral; end
  def numeral=(_arg0); end
  def query(selector = T.unsafe(nil), &block); end
  def reindex_sections; end
  def remove_sub(sub); end
  def render; end
  def sections; end
  def sections?; end
  def source_location; end
  def source_location=(_arg0); end
  def style; end
  def style=(_arg0); end
  def sub?(name); end
  def subs; end
  def title; end
  def title=(val); end
  def title?; end
  def xreftext(xrefstyle = T.unsafe(nil)); end

  protected

  def find_by_internal(selector = T.unsafe(nil), result = T.unsafe(nil), &block); end
end

class Asciidoctor::AbstractNode
  include ::Asciidoctor::Logging
  include ::Asciidoctor::Substitutors
  extend ::Asciidoctor::Logging

  def initialize(parent, context, opts = T.unsafe(nil)); end

  def add_role(name); end
  def attr(name, default_value = T.unsafe(nil), fallback_name = T.unsafe(nil)); end
  def attr?(name, expected_value = T.unsafe(nil), fallback_name = T.unsafe(nil)); end
  def attributes; end
  def block?; end
  def context; end
  def converter; end
  def document; end
  def enabled_options; end
  def generate_data_uri(target_image, asset_dir_key = T.unsafe(nil)); end
  def generate_data_uri_from_uri(image_uri, cache_uri = T.unsafe(nil)); end
  def has_role?(name); end
  def icon_uri(name); end
  def id; end
  def id=(_arg0); end
  def image_uri(target_image, asset_dir_key = T.unsafe(nil)); end
  def inline?; end
  def is_uri?(str); end
  def media_uri(target, asset_dir_key = T.unsafe(nil)); end
  def node_name; end
  def normalize_asset_path(asset_ref, asset_name = T.unsafe(nil), autocorrect = T.unsafe(nil)); end
  def normalize_system_path(target, start = T.unsafe(nil), jail = T.unsafe(nil), opts = T.unsafe(nil)); end
  def normalize_web_path(target, start = T.unsafe(nil), preserve_uri_target = T.unsafe(nil)); end
  def option?(name); end
  def parent; end
  def parent=(parent); end
  def read_asset(path, opts = T.unsafe(nil)); end
  def read_contents(target, opts = T.unsafe(nil)); end
  def reftext; end
  def reftext?; end
  def remove_attr(name); end
  def remove_role(name); end
  def role; end
  def role=(names); end
  def role?(expected_value = T.unsafe(nil)); end
  def roles; end
  def set_attr(name, value = T.unsafe(nil), overwrite = T.unsafe(nil)); end
  def set_option(name); end
  def update_attributes(new_attributes); end
end

Asciidoctor::AdmonitionParagraphRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AnyListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AttributeEntryPassMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AttributeEntryRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::AttributeList
  def initialize(source, block = T.unsafe(nil), delimiter = T.unsafe(nil)); end

  def parse(positional_attrs = T.unsafe(nil)); end
  def parse_into(attributes, positional_attrs = T.unsafe(nil)); end
  def rekey(positional_attrs); end

  private

  def parse_attribute(index, positional_attrs); end
  def parse_attribute_value(quote); end
  def scan_name; end
  def scan_to_delimiter; end
  def scan_to_quote(quote); end
  def skip_blank; end
  def skip_delimiter; end

  class << self
    def rekey(attributes, positional_attrs); end
  end
end

Asciidoctor::AttributeList::APOS = T.let(T.unsafe(nil), String)
Asciidoctor::AttributeList::BACKSLASH = T.let(T.unsafe(nil), String)
Asciidoctor::AttributeList::BlankRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AttributeList::BoundaryRx = T.let(T.unsafe(nil), Hash)
Asciidoctor::AttributeList::EscapedQuotes = T.let(T.unsafe(nil), Hash)
Asciidoctor::AttributeList::NameRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AttributeList::QUOT = T.let(T.unsafe(nil), String)
Asciidoctor::AttributeList::SkipRx = T.let(T.unsafe(nil), Hash)
Asciidoctor::AttributeReferenceRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AtxSectionTitleRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AuthorDelimiterRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::AuthorInfoLineRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BACKEND_ALIASES = T.let(T.unsafe(nil), Hash)
Asciidoctor::BLOCK_MATH_DELIMITERS = T.let(T.unsafe(nil), Hash)
Asciidoctor::BOM_BYTES_UTF_16BE = T.let(T.unsafe(nil), Array)
Asciidoctor::BOM_BYTES_UTF_16LE = T.let(T.unsafe(nil), Array)
Asciidoctor::BOM_BYTES_UTF_8 = T.let(T.unsafe(nil), Array)
Asciidoctor::BlankLineRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::Block < ::Asciidoctor::AbstractBlock
  def initialize(parent, context, opts = T.unsafe(nil)); end

  def blockname; end
  def content; end
  def lines; end
  def lines=(_arg0); end
  def source; end
  def to_s; end
end

Asciidoctor::Block::DEFAULT_CONTENT_MODEL = T.let(T.unsafe(nil), Hash)
Asciidoctor::BlockAnchorRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BlockAttributeLineRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BlockAttributeListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BlockMediaMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BlockTitleRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::BlockTocMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CAPTION_ATTRIBUTE_NAMES = T.let(T.unsafe(nil), Hash)
Asciidoctor::CC_ALL = T.let(T.unsafe(nil), String)
Asciidoctor::CC_ALNUM = T.let(T.unsafe(nil), String)
Asciidoctor::CC_ALPHA = T.let(T.unsafe(nil), String)
Asciidoctor::CC_ANY = T.let(T.unsafe(nil), String)
Asciidoctor::CC_EOL = T.let(T.unsafe(nil), String)
Asciidoctor::CC_WORD = T.let(T.unsafe(nil), String)
Asciidoctor::CG_ALNUM = T.let(T.unsafe(nil), String)
Asciidoctor::CG_ALPHA = T.let(T.unsafe(nil), String)
Asciidoctor::CG_BLANK = T.let(T.unsafe(nil), String)
Asciidoctor::CG_WORD = T.let(T.unsafe(nil), String)
Asciidoctor::CalloutExtractRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CalloutExtractRxMap = T.let(T.unsafe(nil), Hash)
Asciidoctor::CalloutExtractRxt = T.let(T.unsafe(nil), String)
Asciidoctor::CalloutListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CalloutScanRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CalloutSourceRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CalloutSourceRxMap = T.let(T.unsafe(nil), Hash)
Asciidoctor::CalloutSourceRxt = T.let(T.unsafe(nil), String)

class Asciidoctor::Callouts
  def initialize; end

  def callout_ids(li_ordinal); end
  def current_list; end
  def next_list; end
  def read_next_id; end
  def register(li_ordinal); end
  def rewind; end

  private

  def generate_callout_id(list_index, co_index); end
  def generate_next_callout_id; end
end

Asciidoctor::CellSpecEndRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::CellSpecStartRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::ColumnSpecRx = T.let(T.unsafe(nil), Regexp)

module Asciidoctor::Compliance
  class << self
    def attribute_missing; end
    def attribute_missing=(_arg0); end
    def attribute_undefined; end
    def attribute_undefined=(_arg0); end
    def block_terminates_paragraph; end
    def block_terminates_paragraph=(_arg0); end
    def define(key, value); end
    def keys; end
    def markdown_syntax; end
    def markdown_syntax=(_arg0); end
    def natural_xrefs; end
    def natural_xrefs=(_arg0); end
    def shorthand_property_syntax; end
    def shorthand_property_syntax=(_arg0); end
    def strict_verbatim_paragraphs; end
    def strict_verbatim_paragraphs=(_arg0); end
    def underline_style_section_titles; end
    def underline_style_section_titles=(_arg0); end
    def unique_id_start_index; end
    def unique_id_start_index=(_arg0); end
    def unwrap_standalone_preamble; end
    def unwrap_standalone_preamble=(_arg0); end
  end
end

Asciidoctor::ConditionalDirectiveRx = T.let(T.unsafe(nil), Regexp)

module Asciidoctor::Converter
  extend ::Asciidoctor::Converter::Factory
  extend ::Asciidoctor::Converter::DefaultFactory
  include ::Asciidoctor::Converter::BackendTraits

  mixes_in_class_methods ::Asciidoctor::Converter::Config

  def initialize(backend, opts = T.unsafe(nil)); end

  def backend; end
  def convert(node, transform = T.unsafe(nil), opts = T.unsafe(nil)); end
  def handles?(transform); end

  class << self
    def derive_backend_traits(backend, basebackend = T.unsafe(nil)); end

    private

    def included(into); end
  end
end

module Asciidoctor::Converter::BackendTraits
  def backend_info(basebackend = T.unsafe(nil)); end
  def backend_traits(basebackend = T.unsafe(nil)); end
  def basebackend(value = T.unsafe(nil)); end
  def filetype(value = T.unsafe(nil)); end
  def htmlsyntax(value = T.unsafe(nil)); end
  def init_backend_traits(value = T.unsafe(nil)); end
  def outfilesuffix(value = T.unsafe(nil)); end
  def supports_templates(value = T.unsafe(nil)); end
  def supports_templates?; end

  class << self
    def derive_backend_traits(backend, basebackend = T.unsafe(nil)); end
  end
end

class Asciidoctor::Converter::Base
  include ::Asciidoctor::Logging
  include ::Asciidoctor::Converter
  include ::Asciidoctor::Converter::BackendTraits
  extend ::Asciidoctor::Logging
  extend ::Asciidoctor::Converter::Config

  def content_only(node); end
  def convert(node, transform = T.unsafe(nil), opts = T.unsafe(nil)); end
  def handles?(transform); end
  def skip(node); end
end

class Asciidoctor::Converter::CompositeConverter < ::Asciidoctor::Converter::Base
  def initialize(backend, *converters, backend_traits_source: T.unsafe(nil)); end

  def convert(node, transform = T.unsafe(nil), opts = T.unsafe(nil)); end
  def converter_for(transform); end
  def converters; end
  def find_converter(transform); end
end

module Asciidoctor::Converter::Config
  def register_for(*backends); end
end

class Asciidoctor::Converter::CustomFactory
  include ::Asciidoctor::Converter::Factory

  def initialize(seed_registry = T.unsafe(nil)); end

  def unregister_all; end

  private

  def registry; end
end

module Asciidoctor::Converter::DefaultFactory
  include ::Asciidoctor::Converter::Factory

  def for(backend); end
  def register(converter, *backends); end
  def unregister_all; end

  private

  def catch_all; end
  def registry; end
end

Asciidoctor::Converter::DefaultFactory::PROVIDED = T.let(T.unsafe(nil), Hash)

class Asciidoctor::Converter::DefaultFactoryProxy < ::Asciidoctor::Converter::CustomFactory
  include ::Asciidoctor::Converter::DefaultFactory

  def for(backend); end
  def unregister_all; end

  private

  def catch_all; end
end

module Asciidoctor::Converter::Factory
  def converters; end
  def create(backend, opts = T.unsafe(nil)); end
  def for(backend); end
  def register(converter, *backends); end

  private

  def registry; end

  class << self
    def create(backend, opts = T.unsafe(nil)); end
    def default(*args); end
    def new(converters = T.unsafe(nil), proxy_default: T.unsafe(nil)); end
  end
end

class Asciidoctor::Converter::TemplateConverter < ::Asciidoctor::Converter::Base
  def initialize(backend, template_dirs, opts = T.unsafe(nil)); end

  def convert(node, template_name = T.unsafe(nil), opts = T.unsafe(nil)); end
  def handles?(name); end
  def register(name, template); end
  def templates; end

  private

  def load_eruby(name); end
  def scan; end
  def scan_dir(template_dir, pattern, template_cache = T.unsafe(nil)); end

  class << self
    def caches; end
    def clear_caches; end
  end
end

Asciidoctor::Converter::TemplateConverter::DEFAULT_ENGINE_OPTIONS = T.let(T.unsafe(nil), Hash)
Asciidoctor::CustomBlockMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::DATA_DIR = T.let(T.unsafe(nil), String)
Asciidoctor::DEFAULT_ATTRIBUTES = T.let(T.unsafe(nil), Hash)
Asciidoctor::DEFAULT_BACKEND = T.let(T.unsafe(nil), String)
Asciidoctor::DEFAULT_DOCTYPE = T.let(T.unsafe(nil), String)
Asciidoctor::DEFAULT_EXTENSIONS = T.let(T.unsafe(nil), Hash)
Asciidoctor::DEFAULT_PAGE_WIDTHS = T.let(T.unsafe(nil), Hash)
Asciidoctor::DEFAULT_STYLESHEET_KEYS = T.let(T.unsafe(nil), Set)
Asciidoctor::DEFAULT_STYLESHEET_NAME = T.let(T.unsafe(nil), String)
Asciidoctor::DELIMITED_BLOCKS = T.let(T.unsafe(nil), Hash)
Asciidoctor::DELIMITED_BLOCK_HEADS = T.let(T.unsafe(nil), Hash)
Asciidoctor::DELIMITED_BLOCK_TAILS = T.let(T.unsafe(nil), Hash)
Asciidoctor::DescriptionListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::DescriptionListSiblingRx = T.let(T.unsafe(nil), Hash)

class Asciidoctor::Document < ::Asciidoctor::AbstractBlock
  def initialize(data = T.unsafe(nil), options = T.unsafe(nil)); end

  def <<(block); end
  def attribute_locked?(name); end
  def author; end
  def authors; end
  def backend; end
  def base_dir; end
  def basebackend?(base); end
  def callouts; end
  def catalog; end
  def compat_mode; end
  def content; end
  def convert(opts = T.unsafe(nil)); end
  def converter; end
  def counter(name, seed = T.unsafe(nil)); end
  def counter_increment(counter_name, block); end
  def counters; end
  def delete_attribute(name); end
  def docinfo(location = T.unsafe(nil), suffix = T.unsafe(nil)); end
  def docinfo_processors?(location = T.unsafe(nil)); end
  def doctitle(opts = T.unsafe(nil)); end
  def doctype; end
  def embedded?; end
  def extensions; end
  def extensions?; end
  def finalize_header(unrooted_attributes, header_valid = T.unsafe(nil)); end
  def first_section; end
  def footnotes; end
  def footnotes?; end
  def has_header?; end
  def header; end
  def header?; end
  def increment_and_store_counter(counter_name, block); end
  def name(opts = T.unsafe(nil)); end
  def nested?; end
  def nofooter; end
  def noheader; end
  def notitle; end
  def options; end
  def outfilesuffix; end
  def parent_document; end
  def parse(data = T.unsafe(nil)); end
  def parsed?; end
  def path_resolver; end
  def playback_attributes(block_attributes); end
  def reader; end
  def references; end
  def register(type, value); end
  def render(opts = T.unsafe(nil)); end
  def resolve_id(text); end
  def restore_attributes; end
  def revdate; end
  def safe; end
  def sections?; end
  def set_attribute(name, value = T.unsafe(nil)); end
  def set_header_attribute(name, value = T.unsafe(nil), overwrite = T.unsafe(nil)); end
  def source; end
  def source_lines; end
  def sourcemap; end
  def sourcemap=(_arg0); end
  def syntax_highlighter; end
  def title; end
  def title=(title); end
  def to_s; end
  def write(output, target); end
  def xreftext(xrefstyle = T.unsafe(nil)); end

  private

  def apply_attribute_value_subs(value); end
  def clear_playback_attributes(attributes); end
  def create_converter(backend, delegate_backend); end
  def fill_datetime_attributes(attrs, input_mtime); end
  def limit_bytesize(str, max); end
  def resolve_docinfo_subs; end
  def save_attributes; end
  def update_backend_attributes(new_backend, init = T.unsafe(nil)); end
  def update_doctype_attributes(new_doctype); end
end

class Asciidoctor::Document::AttributeEntry
  def initialize(name, value, negate = T.unsafe(nil)); end

  def name; end
  def negate; end
  def save_to(block_attributes); end
  def value; end
end

class Asciidoctor::Document::Author < ::Struct
  def email; end
  def email=(_); end
  def firstname; end
  def firstname=(_); end
  def initials; end
  def initials=(_); end
  def lastname; end
  def lastname=(_); end
  def middlename; end
  def middlename=(_); end
  def name; end
  def name=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Asciidoctor::Document::Footnote < ::Struct
  def id; end
  def id=(_); end
  def index; end
  def index=(_); end
  def text; end
  def text=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Asciidoctor::Document::ImageReference < ::Struct
  def imagesdir; end
  def imagesdir=(_); end
  def target; end
  def target=(_); end
  def to_s; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Asciidoctor::Document::Title
  def initialize(val, opts = T.unsafe(nil)); end

  def combined; end
  def main; end
  def sanitized?; end
  def subtitle; end
  def subtitle?; end
  def title; end
  def to_s; end
end

Asciidoctor::EscapedSpaceRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::EvalExpressionRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::ExtAtxSectionTitleRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::ExtLayoutBreakRx = T.let(T.unsafe(nil), Regexp)

module Asciidoctor::Extensions
  class << self
    def create(name = T.unsafe(nil), &block); end
    def generate_name; end
    def groups; end
    def next_auto_id; end
    def register(*args, &block); end
    def unregister(*names); end
    def unregister_all; end
  end
end

class Asciidoctor::Extensions::BlockMacroProcessor < ::Asciidoctor::Extensions::MacroProcessor
  def name; end
end

Asciidoctor::Extensions::BlockMacroProcessor::DSL = Asciidoctor::Extensions::MacroProcessorDsl

class Asciidoctor::Extensions::BlockProcessor < ::Asciidoctor::Extensions::Processor
  def initialize(name = T.unsafe(nil), config = T.unsafe(nil)); end

  def name; end
  def name=(_arg0); end
  def process(parent, reader, attributes); end
end

Asciidoctor::Extensions::BlockProcessor::DSL = Asciidoctor::Extensions::BlockProcessorDsl

module Asciidoctor::Extensions::BlockProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl
  include ::Asciidoctor::Extensions::SyntaxProcessorDsl

  def bind_to(*value); end
  def contexts(*value); end
  def on_context(*value); end
  def on_contexts(*value); end
end

class Asciidoctor::Extensions::DocinfoProcessor < ::Asciidoctor::Extensions::Processor
  def initialize(config = T.unsafe(nil)); end

  def process(document); end
end

Asciidoctor::Extensions::DocinfoProcessor::DSL = Asciidoctor::Extensions::DocinfoProcessorDsl

module Asciidoctor::Extensions::DocinfoProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl
  include ::Asciidoctor::Extensions::DocumentProcessorDsl

  def at_location(value); end
end

module Asciidoctor::Extensions::DocumentProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl

  def prefer; end
end

class Asciidoctor::Extensions::Extension
  def initialize(kind, instance, config); end

  def config; end
  def instance; end
  def kind; end
end

class Asciidoctor::Extensions::Group
  def activate(registry); end

  class << self
    def register(name = T.unsafe(nil)); end
  end
end

class Asciidoctor::Extensions::IncludeProcessor < ::Asciidoctor::Extensions::Processor
  def handles?(target); end
  def process(document, reader, target, attributes); end
end

Asciidoctor::Extensions::IncludeProcessor::DSL = Asciidoctor::Extensions::IncludeProcessorDsl

module Asciidoctor::Extensions::IncludeProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl
  include ::Asciidoctor::Extensions::DocumentProcessorDsl

  def handles?(*args, &block); end
end

class Asciidoctor::Extensions::InlineMacroProcessor < ::Asciidoctor::Extensions::MacroProcessor
  def regexp; end
  def resolve_regexp(name, format); end
end

Asciidoctor::Extensions::InlineMacroProcessor::DSL = Asciidoctor::Extensions::InlineMacroProcessorDsl

module Asciidoctor::Extensions::InlineMacroProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl
  include ::Asciidoctor::Extensions::SyntaxProcessorDsl
  include ::Asciidoctor::Extensions::MacroProcessorDsl

  def format(value); end
  def match(value); end
  def match_format(value); end
  def using_format(value); end
end

class Asciidoctor::Extensions::MacroProcessor < ::Asciidoctor::Extensions::Processor
  def initialize(name = T.unsafe(nil), config = T.unsafe(nil)); end

  def name; end
  def name=(_arg0); end
  def process(parent, target, attributes); end
end

module Asciidoctor::Extensions::MacroProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl
  include ::Asciidoctor::Extensions::SyntaxProcessorDsl

  def resolve_attributes(*args); end
  def resolves_attributes(*args); end
end

class Asciidoctor::Extensions::Postprocessor < ::Asciidoctor::Extensions::Processor
  def process(document, output); end
end

Asciidoctor::Extensions::Postprocessor::DSL = Asciidoctor::Extensions::DocumentProcessorDsl

class Asciidoctor::Extensions::Preprocessor < ::Asciidoctor::Extensions::Processor
  def process(document, reader); end
end

Asciidoctor::Extensions::Preprocessor::DSL = Asciidoctor::Extensions::DocumentProcessorDsl

class Asciidoctor::Extensions::Processor
  def initialize(config = T.unsafe(nil)); end

  def config; end
  def create_anchor(*args); end
  def create_block(parent, context, source, attrs, opts = T.unsafe(nil)); end
  def create_example_block(*args); end
  def create_image_block(parent, attrs, opts = T.unsafe(nil)); end
  def create_inline(parent, context, text, opts = T.unsafe(nil)); end
  def create_inline_pass(*args); end
  def create_list(parent, context, attrs = T.unsafe(nil)); end
  def create_list_item(parent, text = T.unsafe(nil)); end
  def create_listing_block(*args); end
  def create_literal_block(*args); end
  def create_open_block(*args); end
  def create_paragraph(*args); end
  def create_pass_block(*args); end
  def create_section(parent, title, attrs, opts = T.unsafe(nil)); end
  def parse_attributes(block, attrlist, opts = T.unsafe(nil)); end
  def parse_content(parent, content, attributes = T.unsafe(nil)); end
  def process(*args); end
  def update_config(config); end

  class << self
    def config; end
    def enable_dsl; end
    def option(key, default_value); end
    def use_dsl; end
  end
end

module Asciidoctor::Extensions::ProcessorDsl
  def option(key, value); end
  def process(*args, &block); end
  def process_block_given?; end
end

class Asciidoctor::Extensions::ProcessorExtension < ::Asciidoctor::Extensions::Extension
  def initialize(kind, instance, process_method = T.unsafe(nil)); end

  def process_method; end
end

class Asciidoctor::Extensions::Registry
  def initialize(groups = T.unsafe(nil)); end

  def activate(document); end
  def block(*args, &block); end
  def block_macro(*args, &block); end
  def block_macros?; end
  def blocks?; end
  def docinfo_processor(*args, &block); end
  def docinfo_processors(location = T.unsafe(nil)); end
  def docinfo_processors?(location = T.unsafe(nil)); end
  def document; end
  def find_block_extension(name); end
  def find_block_macro_extension(name); end
  def find_inline_macro_extension(name); end
  def groups; end
  def include_processor(*args, &block); end
  def include_processors; end
  def include_processors?; end
  def inline_macro(*args, &block); end
  def inline_macros; end
  def inline_macros?; end
  def postprocessor(*args, &block); end
  def postprocessors; end
  def postprocessors?; end
  def prefer(*args, &block); end
  def preprocessor(*args, &block); end
  def preprocessors; end
  def preprocessors?; end
  def registered_for_block?(name, context); end
  def registered_for_block_macro?(name); end
  def registered_for_inline_macro?(name); end
  def tree_processor(*args, &block); end
  def tree_processors; end
  def tree_processors?; end
  def treeprocessor(*args, &block); end
  def treeprocessors; end
  def treeprocessors?; end

  private

  def add_document_processor(kind, args, &block); end
  def add_syntax_processor(kind, args, &block); end
  def as_symbol(name); end
  def reset; end
  def resolve_args(args, expect); end
end

module Asciidoctor::Extensions::SyntaxProcessorDsl
  include ::Asciidoctor::Extensions::ProcessorDsl

  def content_model(value); end
  def default_attributes(value); end
  def default_attrs(value); end
  def name_positional_attributes(*value); end
  def named(value); end
  def parse_content_as(value); end
  def positional_attributes(*value); end
  def positional_attrs(*value); end
  def resolve_attributes(*args); end
  def resolves_attributes(*args); end
end

class Asciidoctor::Extensions::TreeProcessor < ::Asciidoctor::Extensions::Processor
  def process(document); end
end

Asciidoctor::Extensions::TreeProcessor::DSL = Asciidoctor::Extensions::DocumentProcessorDsl
Asciidoctor::Extensions::Treeprocessor = Asciidoctor::Extensions::TreeProcessor
Asciidoctor::FILE_READ_MODE = T.let(T.unsafe(nil), String)
Asciidoctor::FILE_WRITE_MODE = T.let(T.unsafe(nil), String)
Asciidoctor::FLEXIBLE_ATTRIBUTES = T.let(T.unsafe(nil), Array)
Asciidoctor::FONT_AWESOME_VERSION = T.let(T.unsafe(nil), String)
Asciidoctor::HARD_LINE_BREAK = T.let(T.unsafe(nil), String)
Asciidoctor::HIGHLIGHT_JS_VERSION = T.let(T.unsafe(nil), String)
Asciidoctor::HYBRID_LAYOUT_BREAK_CHARS = T.let(T.unsafe(nil), Hash)
Asciidoctor::HardLineBreakRx = T.let(T.unsafe(nil), Regexp)

module Asciidoctor::Helpers
  private

  def basename(filename, drop_ext = T.unsafe(nil)); end
  def class_for_name(qualified_name); end
  def encode_spaces_in_uri(str); end
  def encode_uri_component(str); end
  def extname(path, fallback = T.unsafe(nil)); end
  def extname?(path); end
  def int_to_roman(val); end
  def mkdir_p(dir); end
  def nextval(current); end
  def prepare_source_array(data, trim_end = T.unsafe(nil)); end
  def prepare_source_string(data, trim_end = T.unsafe(nil)); end
  def require_library(name, gem_name = T.unsafe(nil), on_failure = T.unsafe(nil)); end
  def require_open_uri(cache = T.unsafe(nil)); end
  def resolve_class(object); end
  def rootname(filename); end
  def uriish?(str); end

  class << self
    def basename(filename, drop_ext = T.unsafe(nil)); end
    def class_for_name(qualified_name); end
    def encode_spaces_in_uri(str); end
    def encode_uri_component(str); end
    def extname(path, fallback = T.unsafe(nil)); end
    def extname?(path); end
    def int_to_roman(val); end
    def mkdir_p(dir); end
    def nextval(current); end
    def prepare_source_array(data, trim_end = T.unsafe(nil)); end
    def prepare_source_string(data, trim_end = T.unsafe(nil)); end
    def require_library(name, gem_name = T.unsafe(nil), on_failure = T.unsafe(nil)); end
    def require_open_uri(cache = T.unsafe(nil)); end
    def resolve_class(object); end
    def rootname(filename); end
    def uriish?(str); end
  end
end

Asciidoctor::Helpers::CGI = CGI
Asciidoctor::Helpers::ROMAN_NUMERALS = T.let(T.unsafe(nil), Hash)
Asciidoctor::INLINE_MATH_DELIMITERS = T.let(T.unsafe(nil), Hash)
Asciidoctor::INTRINSIC_ATTRIBUTES = T.let(T.unsafe(nil), Hash)
Asciidoctor::IncludeDirectiveRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::Inline < ::Asciidoctor::AbstractNode
  def initialize(parent, context, text = T.unsafe(nil), opts = T.unsafe(nil)); end

  def alt; end
  def block?; end
  def convert; end
  def inline?; end
  def reftext; end
  def reftext?; end
  def render; end
  def target; end
  def target=(_arg0); end
  def text; end
  def text=(_arg0); end
  def type; end
  def xreftext(xrefstyle = T.unsafe(nil)); end
end

Asciidoctor::InlineAnchorRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineAnchorScanRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineBiblioAnchorRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineEmailRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineFootnoteMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineImageMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineIndextermMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineKbdBtnMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineLinkMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineLinkRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineMenuMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineMenuRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlinePassMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlinePassRx = T.let(T.unsafe(nil), Hash)
Asciidoctor::InlineSectionAnchorRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineStemMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InlineXrefMacroRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InvalidAttributeNameCharsRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::InvalidSectionIdCharsRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::LAYOUT_BREAK_CHARS = T.let(T.unsafe(nil), Hash)
Asciidoctor::LF = T.let(T.unsafe(nil), String)
Asciidoctor::LIB_DIR = T.let(T.unsafe(nil), String)
Asciidoctor::LINE_CONTINUATION = T.let(T.unsafe(nil), String)
Asciidoctor::LINE_CONTINUATION_LEGACY = T.let(T.unsafe(nil), String)
Asciidoctor::LIST_CONTINUATION = T.let(T.unsafe(nil), String)
Asciidoctor::LeadingInlineAnchorRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::List < ::Asciidoctor::AbstractBlock
  def initialize(parent, context, opts = T.unsafe(nil)); end

  def content; end
  def convert; end
  def items; end
  def items?; end
  def outline?; end
  def render; end
  def to_s; end
end

class Asciidoctor::ListItem < ::Asciidoctor::AbstractBlock
  def initialize(parent, text = T.unsafe(nil)); end

  def compound?; end
  def fold_first; end
  def list; end
  def marker; end
  def marker=(_arg0); end
  def simple?; end
  def text; end
  def text=(_arg0); end
  def text?; end
  def to_s; end
end

Asciidoctor::ListRxMap = T.let(T.unsafe(nil), Hash)
Asciidoctor::LiteralParagraphRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::Logger < ::Logger
  def initialize(*args, **opts); end

  def add(severity, message = T.unsafe(nil), progname = T.unsafe(nil)); end
  def max_severity; end
end

module Asciidoctor::Logger::AutoFormattingMessage
  def inspect; end
end

class Asciidoctor::Logger::BasicFormatter < ::Logger::Formatter
  def call(severity, _, progname, msg); end
end

Asciidoctor::Logger::BasicFormatter::SEVERITY_LABEL_SUBSTITUTES = T.let(T.unsafe(nil), Hash)

module Asciidoctor::LoggerManager
  class << self
    def logger(pipe = T.unsafe(nil)); end
    def logger=(new_logger); end
    def logger_class; end
    def logger_class=(_arg0); end

    private

    def memoize_logger; end
  end
end

module Asciidoctor::Logging
  def logger; end
  def message_with_context(text, context = T.unsafe(nil)); end

  class << self
    private

    def included(into); end
  end
end

Asciidoctor::MARKDOWN_THEMATIC_BREAK_CHARS = T.let(T.unsafe(nil), Hash)
Asciidoctor::MATHJAX_VERSION = T.let(T.unsafe(nil), String)
Asciidoctor::MAX_INT = T.let(T.unsafe(nil), Integer)
Asciidoctor::MacroNameRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::ManpageNamePurposeRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::ManpageTitleVolnumRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::MarkdownThematicBreakRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::MemoryLogger < ::Logger
  def initialize; end

  def add(severity, message = T.unsafe(nil), progname = T.unsafe(nil)); end
  def clear; end
  def empty?; end
  def max_severity; end
  def messages; end
end

Asciidoctor::MemoryLogger::SEVERITY_SYMBOL_BY_VALUE = T.let(T.unsafe(nil), Hash)
Asciidoctor::NESTABLE_LIST_CONTEXTS = T.let(T.unsafe(nil), Array)
Asciidoctor::NULL = T.let(T.unsafe(nil), String)

class Asciidoctor::NullLogger < ::Logger
  def initialize; end

  def add(severity, message = T.unsafe(nil), progname = T.unsafe(nil)); end
  def max_severity; end
end

Asciidoctor::ORDERED_LIST_KEYWORDS = T.let(T.unsafe(nil), Hash)
Asciidoctor::ORDERED_LIST_STYLES = T.let(T.unsafe(nil), Array)
Asciidoctor::OrderedListMarkerRxMap = T.let(T.unsafe(nil), Hash)
Asciidoctor::OrderedListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::PARAGRAPH_STYLES = T.let(T.unsafe(nil), Set)

class Asciidoctor::Parser
  include ::Asciidoctor::Logging
  extend ::Asciidoctor::Logging

  class << self
    def adjust_indentation!(lines, indent_size = T.unsafe(nil), tab_size = T.unsafe(nil)); end
    def atx_section_title?(line); end
    def build_block(block_context, content_model, terminator, parent, reader, attributes, options = T.unsafe(nil)); end
    def catalog_callouts(text, document); end
    def catalog_inline_anchor(id, reftext, node, location, doc = T.unsafe(nil)); end
    def catalog_inline_anchors(text, block, document, reader); end
    def catalog_inline_biblio_anchor(id, reftext, node, reader); end
    def initialize_section(reader, parent, attributes = T.unsafe(nil)); end
    def is_delimited_block?(line, return_match_data = T.unsafe(nil)); end
    def is_next_line_doctitle?(reader, attributes, leveloffset); end
    def is_next_line_section?(reader, attributes); end
    def is_section_title?(line1, line2 = T.unsafe(nil)); end
    def is_sibling_list_item?(line, list_type, sibling_trait); end
    def next_block(reader, parent, attributes = T.unsafe(nil), options = T.unsafe(nil)); end
    def next_section(reader, parent, attributes = T.unsafe(nil)); end
    def parse(reader, document, options = T.unsafe(nil)); end
    def parse_block_metadata_line(reader, document, attributes, options = T.unsafe(nil)); end
    def parse_block_metadata_lines(reader, document, attributes = T.unsafe(nil), options = T.unsafe(nil)); end
    def parse_blocks(reader, parent, attributes = T.unsafe(nil)); end
    def parse_callout_list(reader, match, parent, callouts); end
    def parse_cellspec(line, pos = T.unsafe(nil), delimiter = T.unsafe(nil)); end
    def parse_colspecs(records); end
    def parse_description_list(reader, match, parent); end
    def parse_document_header(reader, document, header_only = T.unsafe(nil)); end
    def parse_header_metadata(reader, document = T.unsafe(nil), retrieve = T.unsafe(nil)); end
    def parse_list(reader, list_type, parent, style); end
    def parse_list_item(reader, list_block, match, sibling_trait, style = T.unsafe(nil)); end
    def parse_manpage_header(reader, document, block_attributes, header_only = T.unsafe(nil)); end
    def parse_section_title(reader, document, sect_id = T.unsafe(nil)); end
    def parse_style_attribute(attributes, reader = T.unsafe(nil)); end
    def parse_table(table_reader, parent, attributes); end
    def process_attribute_entries(reader, document, attributes = T.unsafe(nil)); end
    def process_attribute_entry(reader, document, attributes = T.unsafe(nil), match = T.unsafe(nil)); end
    def process_authors(author_line, names_only = T.unsafe(nil), multiple = T.unsafe(nil)); end
    def read_lines_for_list_item(reader, list_type, sibling_trait = T.unsafe(nil), has_text = T.unsafe(nil)); end
    def read_paragraph_lines(reader, break_at_list, opts = T.unsafe(nil)); end
    def resolve_list_marker(list_type, marker, ordinal = T.unsafe(nil), validate = T.unsafe(nil), reader = T.unsafe(nil)); end
    def resolve_ordered_list_marker(marker, ordinal = T.unsafe(nil), validate = T.unsafe(nil), reader = T.unsafe(nil)); end
    def sanitize_attribute_name(name); end
    def setext_section_title?(line1, line2); end
    def store_attribute(name, value, doc = T.unsafe(nil), attrs = T.unsafe(nil)); end
    def uniform?(str, chr, len); end
    def yield_buffered_attribute(attrs, name, value, reader); end

    private

    def new(*_arg0); end
  end
end

Asciidoctor::Parser::AuthorKeys = T.let(T.unsafe(nil), Array)

class Asciidoctor::Parser::BlockMatchData < ::Struct
  def context; end
  def context=(_); end
  def masq; end
  def masq=(_); end
  def terminator; end
  def terminator=(_); end
  def tip; end
  def tip=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

module Asciidoctor::Parser::ListContinuationMarker; end
Asciidoctor::Parser::ListContinuationPlaceholder = T.let(T.unsafe(nil), String)
Asciidoctor::Parser::ListContinuationString = T.let(T.unsafe(nil), String)
Asciidoctor::Parser::NoOp = T.let(T.unsafe(nil), T.untyped)
Asciidoctor::Parser::StartOfBlockOrListProc = T.let(T.unsafe(nil), Proc)
Asciidoctor::Parser::StartOfBlockProc = T.let(T.unsafe(nil), Proc)
Asciidoctor::Parser::StartOfListProc = T.let(T.unsafe(nil), Proc)
Asciidoctor::Parser::TAB = T.let(T.unsafe(nil), String)
Asciidoctor::Parser::TabIndentRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::Parser::TableCellHorzAlignments = T.let(T.unsafe(nil), Hash)
Asciidoctor::Parser::TableCellStyles = T.let(T.unsafe(nil), Hash)
Asciidoctor::Parser::TableCellVertAlignments = T.let(T.unsafe(nil), Hash)

class Asciidoctor::PathResolver
  include ::Asciidoctor::Logging
  extend ::Asciidoctor::Logging

  def initialize(file_separator = T.unsafe(nil), working_dir = T.unsafe(nil)); end

  def absolute_path?(path); end
  def descends_from?(path, base); end
  def expand_path(path); end
  def file_separator; end
  def file_separator=(_arg0); end
  def join_path(segments, root = T.unsafe(nil)); end
  def partition_path(path, web = T.unsafe(nil)); end
  def posixfy(path); end
  def posixify(path); end
  def relative_path(path, base); end
  def root?(path); end
  def system_path(target, start = T.unsafe(nil), jail = T.unsafe(nil), opts = T.unsafe(nil)); end
  def unc?(path); end
  def web_path(target, start = T.unsafe(nil)); end
  def web_root?(path); end
  def working_dir; end
  def working_dir=(_arg0); end

  private

  def extract_uri_prefix(str); end
end

Asciidoctor::PathResolver::BACKSLASH = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::DOT = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::DOT_DOT = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::DOT_SLASH = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::DOUBLE_SLASH = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::SLASH = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::URI_CLASSLOADER = T.let(T.unsafe(nil), String)
Asciidoctor::PathResolver::WindowsRootRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::PreprocessorReader < ::Asciidoctor::Reader
  def initialize(document, data = T.unsafe(nil), cursor = T.unsafe(nil), opts = T.unsafe(nil)); end

  def create_include_cursor(file, path, lineno); end
  def empty?; end
  def eof?; end
  def exceeded_max_depth?; end
  def exceeds_max_depth?; end
  def has_more_lines?; end
  def include_depth; end
  def include_processors?; end
  def include_stack; end
  def peek_line(direct = T.unsafe(nil)); end
  def push_include(data, file = T.unsafe(nil), path = T.unsafe(nil), lineno = T.unsafe(nil), attributes = T.unsafe(nil)); end
  def shift; end
  def to_s; end

  private

  def pop_include; end
  def prepare_lines(data, opts = T.unsafe(nil)); end
  def preprocess_conditional_directive(name, target, delimiter, text); end
  def preprocess_include_directive(target, attrlist); end
  def process_line(line); end
  def resolve_expr_val(val); end
  def resolve_include_path(target, attrlist, attributes); end
  def skip_front_matter!(data, increment_linenos = T.unsafe(nil)); end
  def split_delimited_value(val); end
end

Asciidoctor::QUOTE_SUBS = T.let(T.unsafe(nil), Hash)
Asciidoctor::REPLACEMENTS = T.let(T.unsafe(nil), Array)
Asciidoctor::ROOT_DIR = T.let(T.unsafe(nil), String)
Asciidoctor::RUBY_ENGINE = T.let(T.unsafe(nil), String)
Asciidoctor::RUBY_ENGINE_OPAL = T.let(T.unsafe(nil), FalseClass)

class Asciidoctor::Reader
  include ::Asciidoctor::Logging
  extend ::Asciidoctor::Logging

  def initialize(data = T.unsafe(nil), cursor = T.unsafe(nil), opts = T.unsafe(nil)); end

  def advance; end
  def cursor; end
  def cursor_at_line(lineno); end
  def cursor_at_mark; end
  def cursor_at_prev_line; end
  def cursor_before_mark; end
  def dir; end
  def discard_save; end
  def empty?; end
  def eof?; end
  def file; end
  def has_more_lines?; end
  def line_info; end
  def lineno; end
  def lines; end
  def mark; end
  def next_line_empty?; end
  def path; end
  def peek_line(direct = T.unsafe(nil)); end
  def peek_lines(num = T.unsafe(nil), direct = T.unsafe(nil)); end
  def process_lines; end
  def process_lines=(_arg0); end
  def read; end
  def read_line; end
  def read_lines; end
  def read_lines_until(options = T.unsafe(nil)); end
  def readlines; end
  def replace_line(replacement); end
  def replace_next_line(replacement); end
  def restore_line(line_to_restore); end
  def restore_lines(lines_to_restore); end
  def restore_save; end
  def save; end
  def shift; end
  def skip_blank_lines; end
  def skip_comment_lines; end
  def skip_line_comments; end
  def source; end
  def source_lines; end
  def string; end
  def terminate; end
  def to_s; end
  def unshift(line); end
  def unshift_all(lines_to_restore); end
  def unshift_line(line_to_restore); end
  def unshift_lines(lines_to_restore); end
  def unterminated; end
  def unterminated=(_arg0); end

  private

  def prepare_lines(data, opts = T.unsafe(nil)); end
  def process_line(line); end
end

class Asciidoctor::Reader::Cursor
  def initialize(file, dir = T.unsafe(nil), path = T.unsafe(nil), lineno = T.unsafe(nil)); end

  def advance(num); end
  def dir; end
  def file; end
  def line_info; end
  def lineno; end
  def path; end
  def to_s; end
end

Asciidoctor::ReplaceableTextRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::RevisionInfoLineRx = T.let(T.unsafe(nil), Regexp)
module Asciidoctor::Rx; end
Asciidoctor::SETEXT_SECTION_LEVELS = T.let(T.unsafe(nil), Hash)
Asciidoctor::STEM_TYPE_ALIASES = T.let(T.unsafe(nil), Hash)

module Asciidoctor::SafeMode
  class << self
    def name_for_value(value); end
    def names; end
    def value_for_name(name); end
  end
end

Asciidoctor::SafeMode::SAFE = T.let(T.unsafe(nil), Integer)
Asciidoctor::SafeMode::SECURE = T.let(T.unsafe(nil), Integer)
Asciidoctor::SafeMode::SERVER = T.let(T.unsafe(nil), Integer)
Asciidoctor::SafeMode::UNSAFE = T.let(T.unsafe(nil), Integer)

class Asciidoctor::Section < ::Asciidoctor::AbstractBlock
  def initialize(parent = T.unsafe(nil), level = T.unsafe(nil), numbered = T.unsafe(nil), opts = T.unsafe(nil)); end

  def <<(block); end
  def caption; end
  def generate_id; end
  def index; end
  def index=(_arg0); end
  def name; end
  def numbered; end
  def numbered=(_arg0); end
  def sections?; end
  def sectname; end
  def sectname=(_arg0); end
  def sectnum(delimiter = T.unsafe(nil), append = T.unsafe(nil)); end
  def special; end
  def special=(_arg0); end
  def to_s; end
  def xreftext(xrefstyle = T.unsafe(nil)); end

  class << self
    def generate_id(title, document); end
  end
end

Asciidoctor::SectionLevelStyleRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::SetextSectionTitleRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::SpaceDelimiterRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::Stylesheets
  def coderay_stylesheet_data; end
  def coderay_stylesheet_name; end
  def embed_coderay_stylesheet; end
  def embed_primary_stylesheet; end
  def embed_pygments_stylesheet(style = T.unsafe(nil)); end
  def primary_stylesheet_data; end
  def primary_stylesheet_name; end
  def pygments_stylesheet_data(style = T.unsafe(nil)); end
  def pygments_stylesheet_name(style = T.unsafe(nil)); end
  def write_coderay_stylesheet(target_dir = T.unsafe(nil)); end
  def write_primary_stylesheet(target_dir = T.unsafe(nil)); end
  def write_pygments_stylesheet(target_dir = T.unsafe(nil), style = T.unsafe(nil)); end

  class << self
    def instance; end
  end
end

Asciidoctor::Stylesheets::DEFAULT_STYLESHEET_NAME = T.let(T.unsafe(nil), String)
Asciidoctor::Stylesheets::STYLESHEETS_DIR = T.let(T.unsafe(nil), String)
Asciidoctor::SubModifierSniffRx = T.let(T.unsafe(nil), Regexp)

module Asciidoctor::Substitutors
  def apply_header_subs(text); end
  def apply_normal_subs(text); end
  def apply_reftext_subs(text); end
  def apply_subs(text, subs = T.unsafe(nil)); end
  def apply_title_subs(text, subs = T.unsafe(nil)); end
  def commit_subs; end
  def expand_subs(subs, subject = T.unsafe(nil)); end
  def extract_passthroughs(text); end
  def highlight_source(source, process_callouts); end
  def parse_attributes(attrlist, posattrs = T.unsafe(nil), opts = T.unsafe(nil)); end
  def resolve_block_subs(subs, defaults, subject); end
  def resolve_lines_to_highlight(source, spec, start = T.unsafe(nil)); end
  def resolve_pass_subs(subs, subject = T.unsafe(nil)); end
  def resolve_subs(subs, type = T.unsafe(nil), defaults = T.unsafe(nil), subject = T.unsafe(nil)); end
  def restore_passthroughs(text); end
  def sub_attributes(text, opts = T.unsafe(nil)); end
  def sub_callouts(text); end
  def sub_macros(text); end
  def sub_post_replacements(text); end
  def sub_quotes(text); end
  def sub_replacements(text); end
  def sub_source(source, process_callouts); end
  def sub_specialcharacters(text); end
  def sub_specialchars(text); end

  private

  def convert_quoted_text(match, type, scope); end
  def do_replacement(m, replacement, restore); end
  def extract_attributes_from_text(text, default_text = T.unsafe(nil)); end
  def extract_callouts(source); end
  def normalize_text(text, normalize_whitespace = T.unsafe(nil), unescape_closing_square_brackets = T.unsafe(nil)); end
  def parse_quoted_text_attributes(str); end
  def restore_callouts(source, callout_marks, source_offset = T.unsafe(nil)); end
  def split_simple_csv(str); end
  def sub_placeholder(*_arg0); end
end

Asciidoctor::Substitutors::BASIC_SUBS = T.let(T.unsafe(nil), Array)
Asciidoctor::Substitutors::CAN = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::CGI = CGI
Asciidoctor::Substitutors::DEL = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::ESC_R_SB = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::HEADER_SUBS = T.let(T.unsafe(nil), Array)
Asciidoctor::Substitutors::HighlightedPassSlotRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::Substitutors::NORMAL_SUBS = T.let(T.unsafe(nil), Array)
Asciidoctor::Substitutors::NO_SUBS = T.let(T.unsafe(nil), Array)
Asciidoctor::Substitutors::PASS_END = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::PASS_START = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::PLUS = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::PassSlotRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::Substitutors::QuotedTextSniffRx = T.let(T.unsafe(nil), Hash)
Asciidoctor::Substitutors::REFTEXT_SUBS = T.let(T.unsafe(nil), Array)
Asciidoctor::Substitutors::RS = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::R_SB = T.let(T.unsafe(nil), String)
Asciidoctor::Substitutors::SUB_GROUPS = T.let(T.unsafe(nil), Hash)
Asciidoctor::Substitutors::SUB_HINTS = T.let(T.unsafe(nil), Hash)
Asciidoctor::Substitutors::SUB_OPTIONS = T.let(T.unsafe(nil), Hash)
Asciidoctor::Substitutors::SpecialCharsRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::Substitutors::SpecialCharsTr = T.let(T.unsafe(nil), Hash)
Asciidoctor::Substitutors::VERBATIM_SUBS = T.let(T.unsafe(nil), Array)

module Asciidoctor::SyntaxHighlighter
  extend ::Asciidoctor::SyntaxHighlighter::Factory
  extend ::Asciidoctor::SyntaxHighlighter::DefaultFactory

  mixes_in_class_methods ::Asciidoctor::SyntaxHighlighter::Config

  def initialize(name, backend = T.unsafe(nil), opts = T.unsafe(nil)); end

  def docinfo(location, doc, opts); end
  def docinfo?(location); end
  def format(node, lang, opts); end
  def highlight(node, source, lang, opts); end
  def highlight?; end
  def name; end
  def write_stylesheet(doc, to_dir); end
  def write_stylesheet?(doc); end

  class << self
    private

    def included(into); end
  end
end

class Asciidoctor::SyntaxHighlighter::Base
  include ::Asciidoctor::SyntaxHighlighter
  extend ::Asciidoctor::SyntaxHighlighter::Config

  def format(node, lang, opts); end
end

module Asciidoctor::SyntaxHighlighter::Config
  def register_for(*names); end
end

class Asciidoctor::SyntaxHighlighter::CustomFactory
  include ::Asciidoctor::SyntaxHighlighter::Factory

  def initialize(seed_registry = T.unsafe(nil)); end

  private

  def registry; end
end

module Asciidoctor::SyntaxHighlighter::DefaultFactory
  include ::Asciidoctor::SyntaxHighlighter::Factory

  def for(name); end
  def register(syntax_highlighter, *names); end

  private

  def registry; end
end

Asciidoctor::SyntaxHighlighter::DefaultFactory::PROVIDED = T.let(T.unsafe(nil), Hash)

class Asciidoctor::SyntaxHighlighter::DefaultFactoryProxy < ::Asciidoctor::SyntaxHighlighter::CustomFactory
  include ::Asciidoctor::SyntaxHighlighter::DefaultFactory

  def for(name); end
end

module Asciidoctor::SyntaxHighlighter::Factory
  def create(name, backend = T.unsafe(nil), opts = T.unsafe(nil)); end
  def for(name); end
  def register(syntax_highlighter, *names); end

  private

  def registry; end
end

class Asciidoctor::SyntaxHighlighter::HighlightJsAdapter < ::Asciidoctor::SyntaxHighlighter::Base
  def initialize(*args); end

  def docinfo(location, doc, opts); end
  def docinfo?(location); end
  def format(node, lang, opts); end
end

class Asciidoctor::SyntaxHighlighter::HtmlPipelineAdapter < ::Asciidoctor::SyntaxHighlighter::Base
  def format(node, lang, opts); end
end

Asciidoctor::TAB = T.let(T.unsafe(nil), String)

class Asciidoctor::Table < ::Asciidoctor::AbstractBlock
  def initialize(parent, attributes); end

  def assign_column_widths(width_base = T.unsafe(nil), autowidth_cols = T.unsafe(nil)); end
  def caption; end
  def columns; end
  def columns=(_arg0); end
  def create_columns(colspecs); end
  def has_header_option; end
  def has_header_option=(_arg0); end
  def header_row?; end
  def partition_header_footer(attrs); end
  def rows; end
  def rows=(_arg0); end
end

class Asciidoctor::Table::Cell < ::Asciidoctor::AbstractBlock
  def initialize(column, cell_text, attributes = T.unsafe(nil), opts = T.unsafe(nil)); end

  def catalog_inline_anchor(cell_text = T.unsafe(nil), cursor = T.unsafe(nil)); end
  def colspan; end
  def colspan=(_arg0); end
  def column; end
  def content; end
  def file; end
  def inner_document; end
  def lineno; end
  def lines; end
  def reinitialize(has_header); end
  def rowspan; end
  def rowspan=(_arg0); end
  def source; end
  def text; end
  def text=(_arg0); end
  def to_s; end
end

Asciidoctor::Table::Cell::DOUBLE_LF = T.let(T.unsafe(nil), String)

class Asciidoctor::Table::Column < ::Asciidoctor::AbstractNode
  def initialize(table, index, attributes = T.unsafe(nil)); end

  def assign_width(col_pcwidth, width_base, precision); end
  def block?; end
  def inline?; end
  def style; end
  def style=(_arg0); end
  def table; end
end

Asciidoctor::Table::DEFAULT_PRECISION = T.let(T.unsafe(nil), Integer)

class Asciidoctor::Table::ParserContext
  include ::Asciidoctor::Logging
  extend ::Asciidoctor::Logging

  def initialize(reader, table, attributes = T.unsafe(nil)); end

  def buffer; end
  def buffer=(_arg0); end
  def buffer_has_unclosed_quotes?(append = T.unsafe(nil), q = T.unsafe(nil)); end
  def cell_closed?; end
  def cell_open?; end
  def close_cell(eol = T.unsafe(nil)); end
  def close_open_cell(next_cellspec = T.unsafe(nil)); end
  def close_table; end
  def colcount; end
  def delimiter; end
  def delimiter_re; end
  def format; end
  def format=(_arg0); end
  def keep_cell_open; end
  def mark_cell_closed; end
  def match_delimiter(line); end
  def push_cellspec(cellspec = T.unsafe(nil)); end
  def skip_past_delimiter(pre); end
  def skip_past_escaped_delimiter(pre); end
  def starts_with_delimiter?(line); end
  def table; end
  def table=(_arg0); end
  def take_cellspec; end

  private

  def activate_rowspan(rowspan, colspan); end
  def advance; end
  def close_row(drop = T.unsafe(nil)); end
  def effective_column_visits; end
  def end_of_row?; end
end

Asciidoctor::Table::ParserContext::DELIMITERS = T.let(T.unsafe(nil), Hash)
Asciidoctor::Table::ParserContext::FORMATS = T.let(T.unsafe(nil), Set)

class Asciidoctor::Table::Rows
  def initialize(head = T.unsafe(nil), foot = T.unsafe(nil), body = T.unsafe(nil)); end

  def [](*_arg0); end
  def body; end
  def body=(_arg0); end
  def by_section; end
  def foot; end
  def foot=(_arg0); end
  def head; end
  def head=(_arg0); end
  def to_h; end
end

Asciidoctor::TagDirectiveRx = T.let(T.unsafe(nil), Regexp)

class Asciidoctor::Timings
  def initialize; end

  def convert; end
  def parse; end
  def print_report(to = T.unsafe(nil), subject = T.unsafe(nil)); end
  def read; end
  def read_parse; end
  def read_parse_convert; end
  def record(key); end
  def start(key); end
  def time(*keys); end
  def total; end
  def write; end

  private

  def now; end
end

Asciidoctor::Timings::CLOCK_ID = T.let(T.unsafe(nil), Integer)
Asciidoctor::TrailingDigitsRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::URI_READ_MODE = T.let(T.unsafe(nil), String)
Asciidoctor::USER_HOME = T.let(T.unsafe(nil), String)
Asciidoctor::UTF_8 = T.let(T.unsafe(nil), Encoding)
Asciidoctor::UnorderedListRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::UriSniffRx = T.let(T.unsafe(nil), Regexp)
Asciidoctor::VERBATIM_STYLES = T.let(T.unsafe(nil), Set)
Asciidoctor::VERSION = T.let(T.unsafe(nil), String)

module Asciidoctor::VoidWriter
  include ::Asciidoctor::Writer

  def write(output, target); end
end

module Asciidoctor::Writer
  def write(output, target); end
end

Asciidoctor::XmlSanitizeRx = T.let(T.unsafe(nil), Regexp)

class Hash
  include ::Enumerable

  def nil_or_empty?; end
end

class NilClass
  def nil_or_empty?; end
end

class Numeric
  include ::Comparable

  def nil_or_empty?; end
end

class String
  include ::Comparable

  def nil_or_empty?; end
end
