# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pastel` gem.
# Please instead update this file by running `bin/tapioca gem pastel`.


module Pastel
  private

  def new(enabled: T.unsafe(nil), eachline: T.unsafe(nil)); end

  class << self
    def new(enabled: T.unsafe(nil), eachline: T.unsafe(nil)); end
  end
end

module Pastel::ANSI
  private

  def background?(code); end
  def foreground?(code); end
  def style?(code); end

  class << self
    def background?(code); end
    def foreground?(code); end
    def style?(code); end
  end
end

Pastel::ANSI::ATTRIBUTES = T.let(T.unsafe(nil), Hash)

class Pastel::AliasImporter
  def initialize(color, env, output = T.unsafe(nil)); end

  def import; end

  protected

  def color; end
  def env; end
  def output; end
end

class Pastel::Color
  include ::Pastel::ANSI

  def initialize(enabled: T.unsafe(nil), eachline: T.unsafe(nil)); end

  def ==(other); end
  def alias_color(alias_name, *colors); end
  def apply_codes(string, ansi_colors); end
  def clear; end
  def code(*colors); end
  def colored?(string); end
  def decorate(string, *colors); end
  def disable!; end
  def eachline; end
  def enabled; end
  def enabled?; end
  def eql?(other); end
  def hash; end
  def inspect; end
  def lookup(*colors); end
  def strip(*strings); end
  def style_names; end
  def styles; end
  def valid?(*colors); end

  private

  def blank?(value); end
  def validate(*colors); end
end

Pastel::Color::ALIASES = T.let(T.unsafe(nil), Hash)
Pastel::Color::ANSI_COLOR_REGEXP = T.let(T.unsafe(nil), Regexp)

class Pastel::ColorParser
  include ::Pastel::ANSI

  class << self
    def attribute_name(ansi); end
    def color_name(ansi_code); end
    def parse(text); end
    def unpack_ansi(ansi_stack); end
  end
end

Pastel::ColorParser::CSI = T.let(T.unsafe(nil), String)
Pastel::ColorParser::ESC = T.let(T.unsafe(nil), String)

class Pastel::ColorResolver
  def initialize(color); end

  def color; end
  def resolve(base, unprocessed_string); end
end

class Pastel::DecoratorChain
  include ::Enumerable

  def initialize(decorators = T.unsafe(nil)); end

  def ==(other); end
  def add(decorator); end
  def each(&block); end
  def eql?(other); end
  def hash; end
  def inspect; end

  protected

  def decorators; end

  class << self
    def empty; end
  end
end

class Pastel::Delegator
  extend ::Forwardable

  def initialize(resolver, chain); end

  def ==(other); end
  def alias_color(*args, **_arg1, &block); end
  def colored?(*args, **_arg1, &block); end
  def decorate(*args, **_arg1, &block); end
  def enabled?(*args, **_arg1, &block); end
  def eql?(other); end
  def hash; end
  def inspect; end
  def lookup(*args, **_arg1, &block); end
  def parse(*args, **_arg1, &block); end
  def strip(*args, **_arg1, &block); end
  def styles(*args, **_arg1, &block); end
  def to_s; end
  def undecorate(*args, **_arg1, &block); end
  def valid?(*args, **_arg1, &block); end

  protected

  def chain; end
  def evaluate_block(&block); end
  def method_missing(method_name, *args, &block); end
  def resolver; end

  private

  def respond_to_missing?(name, include_all = T.unsafe(nil)); end

  class << self
    def wrap(resolver, chain = T.unsafe(nil)); end
  end
end

class Pastel::Detached
  def initialize(color, *styles); end

  def ==(other); end
  def [](*args); end
  def call(*args); end
  def eql?(other); end
  def hash; end
  def inspect; end
  def to_proc; end

  protected

  def styles; end
end

class Pastel::InvalidAliasNameError < ::ArgumentError; end
class Pastel::InvalidAttributeNameError < ::ArgumentError; end
Pastel::VERSION = T.let(T.unsafe(nil), String)
