# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `polyglot` gem.
# Please instead update this file by running `bin/tapioca gem polyglot`.


module Kernel
  def require(*a, &b); end

  private

  def polyglot_original_require(name); end
end

module Polyglot
  class << self
    def find(file, *options, &block); end
    def load(*a, &b); end
    def register(extension, klass); end
  end
end

class Polyglot::NestedLoadError < ::LoadError
  def initialize(le); end

  def reraise; end
end

class Polyglot::PolyglotLoadError < ::LoadError; end
