# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-prof` gem.
# Please instead update this file by running `bin/tapioca gem ruby-prof`.


module ERB::Escape; end
module Rack; end

class Rack::RubyProf
  def initialize(app, path: T.unsafe(nil), printers: T.unsafe(nil), skip_paths: T.unsafe(nil), only_paths: T.unsafe(nil), merge_fibers: T.unsafe(nil), measure_mode: T.unsafe(nil), track_allocations: T.unsafe(nil), exclude_common: T.unsafe(nil), ignore_existing_threads: T.unsafe(nil), request_thread_only: T.unsafe(nil), min_percent: T.unsafe(nil), sort_method: T.unsafe(nil)); end

  def call(env); end

  private

  def paths_match?(path, paths); end
  def print(profile, path); end
  def print_options; end
  def profiling_options; end
  def should_profile?(path); end
end

module RubyProf
  class << self
    def figure_measure_mode; end
  end
end

RubyProf::ALLOCATIONS = T.let(T.unsafe(nil), Integer)

class RubyProf::AbstractPrinter
  def initialize(result); end

  def filter_by; end
  def max_percent; end
  def method_href(thread, method); end
  def method_location(method); end
  def min_percent; end
  def open_asset(file); end
  def print(output = T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg5); end
  def print_column_headers; end
  def print_footer(thread); end
  def print_header(thread); end
  def print_thread(thread); end
  def print_threads; end
  def sort_method; end
  def time_format; end

  class << self
    def needs_dir?; end
  end
end

class RubyProf::Allocation
  def _dump_data; end
  def _load_data(_arg0); end
  def count; end
  def klass_flags; end
  def klass_name; end
  def line; end
  def source_file; end
end

RubyProf::CLOCKS_PER_SEC = T.let(T.unsafe(nil), Integer)

class RubyProf::CallInfoPrinter < ::RubyProf::AbstractPrinter
  private

  def print_footer(thread); end
  def print_header(thread); end
  def print_methods(thread); end
end

RubyProf::CallInfoPrinter::TIME_WIDTH = T.let(T.unsafe(nil), Integer)

class RubyProf::CallStackPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  def application; end
  def arguments; end
  def base64_image; end
  def color(p); end
  def dump(ci); end
  def expansion; end
  def graph_link(call_tree); end
  def link(method, recursive); end
  def method_href(method); end
  def name(call_tree); end
  def print(output = T.unsafe(nil), title: T.unsafe(nil), threshold: T.unsafe(nil), expansion: T.unsafe(nil), application: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg9); end
  def print_stack(output, visited, call_tree, parent_time); end
  def sum(a); end
  def template; end
  def threshold; end
  def title; end
  def total_time(call_trees); end
end

class RubyProf::CallTree
  def initialize(_arg0); end

  def <=>(other); end
  def _dump_data; end
  def _load_data(_arg0); end
  def add_child(_arg0); end
  def called; end
  def children; end
  def children_time; end
  def depth; end
  def inspect; end
  def line; end
  def measurement; end
  def parent; end
  def self_time; end
  def source_file; end
  def target; end
  def to_s; end
  def total_time; end
  def wait_time; end
end

class RubyProf::CallTreePrinter < ::RubyProf::AbstractPrinter
  def calltree_name(method_info); end
  def convert(value); end
  def determine_event_specification_and_value_scale; end
  def file(method); end
  def file_name_for_thread(thread); end
  def file_path_for_thread(thread); end
  def path; end
  def print(path: T.unsafe(nil), **_arg1); end
  def print_headers(output, thread); end
  def print_method(output, method); end
  def print_thread(thread); end
  def print_threads; end
  def remove_subsidiary_files_from_previous_profile_runs; end

  class << self
    def needs_dir?; end
  end
end

class RubyProf::CallTreeVisitor
  def initialize(call_tree); end

  def visit(&block); end

  private

  def visit_call_tree(call_tree, &block); end
end

class RubyProf::CallTrees
  def _dump_data; end
  def _load_data(_arg0); end
  def call_trees; end
  def callees; end
  def callers; end
  def min_depth; end
end

class RubyProf::DotPrinter < ::RubyProf::AbstractPrinter
  def initialize(result); end

  def print(output = T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg5); end

  private

  def color_for_class(klass_name); end
  def dot_id(subject); end
  def mode_name; end
  def node_color(total_percentage); end
  def node_fontcolor(total_percentage); end
  def print_classes(thread); end
  def print_edges(total_time, method); end
  def print_thread(thread); end
  def print_threads; end
  def puts(str); end
end

RubyProf::DotPrinter::CLUSTER_COLORS = T.let(T.unsafe(nil), Array)

module RubyProf::ExcludeCommonMethods
  class << self
    def apply!(profile); end
    def exclude_enumerable(profile, mod, *method_or_methods); end
    def exclude_methods(profile, mod, *method_or_methods); end
    def exclude_singleton_methods(profile, mod, *method_or_methods); end
  end
end

RubyProf::ExcludeCommonMethods::ENUMERABLE_NAMES = T.let(T.unsafe(nil), Array)

class RubyProf::FlameGraphPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  def build_flame_data(call_tree, visited = T.unsafe(nil)); end
  def flame_data_json; end
  def print(output = T.unsafe(nil), title: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg6); end
  def template; end
  def title; end
end

class RubyProf::FlatPrinter < ::RubyProf::AbstractPrinter
  def print(output = T.unsafe(nil), sort_method: T.unsafe(nil), **options); end

  private

  def print_column_headers; end
  def print_methods(thread); end
end

class RubyProf::GraphHtmlPrinter < ::RubyProf::AbstractPrinter
  include ::ERB::Escape
  include ::ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate

  def create_link(thread, overall_time, method); end
  def file_link(path, linenum); end
  def method_href(thread, method); end
  def print(output = T.unsafe(nil), min_time: T.unsafe(nil), nonzero: T.unsafe(nil), min_percent: T.unsafe(nil), max_percent: T.unsafe(nil), filter_by: T.unsafe(nil), sort_method: T.unsafe(nil), **_arg7); end
  def template; end
end

class RubyProf::GraphPrinter < ::RubyProf::AbstractPrinter
  def print(output = T.unsafe(nil), sort_method: T.unsafe(nil), **options); end

  private

  def print_children(method); end
  def print_header(thread); end
  def print_methods(thread); end
  def print_parents(thread, method); end
end

RubyProf::GraphPrinter::CALL_WIDTH = T.let(T.unsafe(nil), Integer)
RubyProf::GraphPrinter::PERCENTAGE_WIDTH = T.let(T.unsafe(nil), Integer)
RubyProf::GraphPrinter::TIME_WIDTH = T.let(T.unsafe(nil), Integer)
module RubyProf::Measure; end
class RubyProf::Measure::Allocations; end
class RubyProf::Measure::ProcessTime; end
class RubyProf::Measure::WallTime; end

class RubyProf::Measurement
  def initialize(_arg0, _arg1, _arg2, _arg3); end

  def _dump_data; end
  def _load_data(_arg0); end
  def called; end
  def called=(_arg0); end
  def children_time; end
  def inspect; end
  def merge!(_arg0); end
  def self_time; end
  def self_time=(_arg0); end
  def to_s; end
  def total_time; end
  def total_time=(_arg0); end
  def wait_time; end
  def wait_time=(_arg0); end

  private

  def initialize_copy(_arg0); end
end

class RubyProf::MethodInfo
  include ::Comparable

  def initialize(_arg0, _arg1); end

  def <=>(other); end
  def ==(other); end
  def _dump_data; end
  def _load_data(_arg0); end
  def allocations; end
  def call_trees; end
  def called; end
  def children_time; end
  def eql?(other); end
  def full_name; end
  def hash; end
  def klass_flags; end
  def klass_name; end
  def line; end
  def measurement; end
  def method_name; end
  def recursive?; end
  def self_time; end
  def source_file; end
  def to_s; end
  def total_time; end
  def wait_time; end
end

RubyProf::MethodInfo::CLASS_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::MODULE_INCLUDEE = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::MODULE_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::OBJECT_SINGLETON = T.let(T.unsafe(nil), Integer)
RubyProf::MethodInfo::OTHER_SINGLETON = T.let(T.unsafe(nil), Integer)

class RubyProf::MultiPrinter
  def initialize(result, printers = T.unsafe(nil)); end

  def call_info_report; end
  def dot_report; end
  def flame_graph_report; end
  def flat_report; end
  def graph_html_report; end
  def graph_report; end
  def print(profile: T.unsafe(nil), path: T.unsafe(nil), **options); end
  def print_to_call_info(**options); end
  def print_to_dot(**options); end
  def print_to_flame_graph(**options); end
  def print_to_flat(**options); end
  def print_to_graph(**options); end
  def print_to_graph_html(**options); end
  def print_to_stack(**options); end
  def print_to_tree(**options); end
  def stack_report; end
  def tree_report; end

  class << self
    def needs_dir?; end
  end
end

RubyProf::PROCESS_TIME = T.let(T.unsafe(nil), Integer)

class RubyProf::Profile
  def initialize(*_arg0); end

  def _dump_data; end
  def _load_data(_arg0); end
  def add_thread(_arg0); end
  def exclude_common_methods!; end
  def exclude_method!(_arg0, _arg1); end
  def exclude_methods!(mod, *method_names); end
  def exclude_singleton_methods!(mod, *method_names); end
  def measure_mode; end
  def measure_mode_name; end
  def measure_mode_string; end
  def merge!; end
  def pause; end
  def paused?; end
  def profile; end
  def remove_thread(_arg0); end
  def resume; end
  def running?; end
  def start; end
  def stop; end
  def threads; end
  def track_allocations?; end

  class << self
    def profile(*_arg0); end
  end
end

class RubyProf::Thread
  def initialize(_arg0, _arg1, _arg2); end

  def _dump_data; end
  def _load_data(_arg0); end
  def call_tree; end
  def fiber_id; end
  def id; end
  def merge!(_arg0); end
  def methods; end
  def total_time; end
  def wait_time; end
end

RubyProf::VERSION = T.let(T.unsafe(nil), String)
RubyProf::WALL_TIME = T.let(T.unsafe(nil), Integer)
