# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `terminal-table` gem.
# Please instead update this file by running `bin/tapioca gem terminal-table`.


module Terminal; end

class Terminal::Table
  def initialize(options = T.unsafe(nil), &block); end

  def <<(array); end
  def ==(other); end
  def add_row(array); end
  def add_separator(border_type: T.unsafe(nil)); end
  def align_column(n, alignment); end
  def cell_padding; end
  def cell_spacing; end
  def column(n, method = T.unsafe(nil), array = T.unsafe(nil)); end
  def column_width(n); end
  def column_with_headings(n, method = T.unsafe(nil)); end
  def columns; end
  def elaborate_rows; end
  def headings; end
  def headings=(arrays); end
  def length_of_column(n); end
  def number_of_columns; end
  def render; end
  def rows; end
  def rows=(array); end
  def style; end
  def style=(options); end
  def title; end
  def title=(title); end
  def to_s; end

  private

  def column_widths; end
  def columns_width; end
  def headings_with_rows; end
  def recalc_column_widths; end
  def require_column_widths_recalc; end
  def title_cell_options; end
  def yield_or_eval(&block); end
end

class Terminal::Table::AsciiBorder < ::Terminal::Table::Border
  def initialize; end

  def horizontal(_type); end
  def vertical; end
end

Terminal::Table::AsciiBorder::HORIZONTALS = T.let(T.unsafe(nil), Array)
Terminal::Table::AsciiBorder::INTERSECTIONS = T.let(T.unsafe(nil), Array)
Terminal::Table::AsciiBorder::VERTICALS = T.let(T.unsafe(nil), Array)

class Terminal::Table::Border
  def initialize; end

  def [](key); end
  def []=(key, val); end
  def bottom; end
  def bottom=(_arg0); end
  def data; end
  def data=(_arg0); end
  def left; end
  def left=(_arg0); end
  def maybeleft(key); end
  def mayberight(key); end
  def remove_horizontals; end
  def remove_verticals; end
  def right; end
  def right=(_arg0); end
  def top; end
  def top=(_arg0); end

  private

  def initialize_dup(other); end
end

class Terminal::Table::Cell
  def initialize(options = T.unsafe(nil)); end

  def align(val, position, length); end
  def alignment; end
  def alignment=(val); end
  def alignment?; end
  def colspan; end
  def inspect; end
  def lines; end
  def render(line = T.unsafe(nil)); end
  def to_s(line = T.unsafe(nil)); end
  def value; end
  def value_for_column_width_recalc; end
  def width; end
end

class Terminal::Table::MarkdownBorder < ::Terminal::Table::AsciiBorder
  def initialize; end
end

class Terminal::Table::Row
  def initialize(table, array = T.unsafe(nil), **_kwargs); end

  def <<(item); end
  def [](index); end
  def add_cell(item); end
  def cells; end
  def crossings; end
  def height; end
  def number_of_columns; end
  def render; end
  def table; end
end

class Terminal::Table::Separator < ::Terminal::Table::Row
  def initialize(*args, border_type: T.unsafe(nil), implicit: T.unsafe(nil)); end

  def border_type; end
  def border_type=(_arg0); end
  def implicit; end
  def render; end
  def save_adjacent_rows(prevrow, nextrow); end
end

class Terminal::Table::Style
  extend ::Forwardable

  def initialize(options = T.unsafe(nil)); end

  def alignment; end
  def alignment=(_arg0); end
  def all_separators; end
  def all_separators=(_arg0); end
  def apply(options); end
  def border; end
  def border=(val); end
  def border_bottom; end
  def border_bottom=(val); end
  def border_i=(val); end
  def border_left; end
  def border_left=(val); end
  def border_right; end
  def border_right=(val); end
  def border_top; end
  def border_top=(val); end
  def border_x=(val); end
  def border_y; end
  def border_y=(val); end
  def border_y_width; end
  def horizontal(*args, **_arg1, &block); end
  def margin_left; end
  def margin_left=(_arg0); end
  def on_change(attr); end
  def padding_left; end
  def padding_left=(_arg0); end
  def padding_right; end
  def padding_right=(_arg0); end
  def remove_horizontals(*args, **_arg1, &block); end
  def remove_verticals(*args, **_arg1, &block); end
  def vertical(*args, **_arg1, &block); end
  def width; end
  def width=(_arg0); end

  class << self
    def defaults; end
    def defaults=(options); end
  end
end

module Terminal::Table::TableHelper
  def table(headings = T.unsafe(nil), *rows, &block); end
end

class Terminal::Table::UnicodeBorder < ::Terminal::Table::Border
  def initialize; end

  def horizontal(type); end
  def vertical; end
end

Terminal::Table::UnicodeBorder::ALLOWED_SEPARATOR_BORDER_STYLES = T.let(T.unsafe(nil), Array)
Terminal::Table::UnicodeBorder::HORIZONTALS = T.let(T.unsafe(nil), Array)
Terminal::Table::UnicodeBorder::INTERSECTIONS = T.let(T.unsafe(nil), Array)
Terminal::Table::UnicodeBorder::VERTICALS = T.let(T.unsafe(nil), Array)

class Terminal::Table::UnicodeRoundBorder < ::Terminal::Table::UnicodeBorder
  def initialize; end
end

class Terminal::Table::UnicodeThickEdgeBorder < ::Terminal::Table::UnicodeBorder
  def initialize; end
end

module Terminal::Table::Util
  private

  def ansi_escape(line); end

  class << self
    def ansi_escape(line); end
  end
end

Terminal::Table::VERSION = T.let(T.unsafe(nil), String)
