# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-color` gem.
# Please instead update this file by running `bin/tapioca gem tty-color`.


module TTY; end

module TTY::Color
  extend ::TTY::Color

  def color?; end
  def command?(cmd); end
  def disabled?; end
  def mode; end
  def output; end
  def output=(_arg0); end
  def support?; end
  def supports?; end
  def supports_color?; end
  def tty?; end
  def verbose; end
  def verbose=(_arg0); end
  def windows?; end
end

class TTY::Color::Mode
  def initialize(env); end

  def from_term; end
  def from_tput; end
  def mode; end
end

TTY::Color::Mode::METHODS = T.let(T.unsafe(nil), Array)
TTY::Color::Mode::TERM_16 = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TERM_24BIT = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TERM_256 = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TERM_52 = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TERM_64 = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TERM_8 = T.let(T.unsafe(nil), Regexp)
TTY::Color::Mode::TRUECOLORS = T.let(T.unsafe(nil), Integer)
module TTY::Color::NoValue; end

class TTY::Color::Support
  def initialize(env, verbose: T.unsafe(nil)); end

  def disabled?; end
  def from_curses(curses_class = T.unsafe(nil)); end
  def from_env; end
  def from_term; end
  def from_tput; end
  def support?; end
end

TTY::Color::Support::ENV_VARS = T.let(T.unsafe(nil), Array)
TTY::Color::Support::SOURCES = T.let(T.unsafe(nil), Array)
TTY::Color::Support::TERM_REGEX = T.let(T.unsafe(nil), Regexp)
TTY::Color::VERSION = T.let(T.unsafe(nil), String)
