# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-cursor` gem.
# Please instead update this file by running `bin/tapioca gem tty-cursor`.


module TTY; end

module TTY::Cursor
  private

  def backward(n = T.unsafe(nil)); end
  def clear_char(n = T.unsafe(nil)); end
  def clear_line; end
  def clear_line_after; end
  def clear_line_before; end
  def clear_lines(n, direction = T.unsafe(nil)); end
  def clear_rows(n, direction = T.unsafe(nil)); end
  def clear_screen; end
  def clear_screen_down; end
  def clear_screen_up; end
  def column(n = T.unsafe(nil)); end
  def current; end
  def cursor_backward(n = T.unsafe(nil)); end
  def cursor_down(n = T.unsafe(nil)); end
  def cursor_forward(n = T.unsafe(nil)); end
  def cursor_up(n = T.unsafe(nil)); end
  def down(n = T.unsafe(nil)); end
  def forward(n = T.unsafe(nil)); end
  def hide; end
  def invisible(stream = T.unsafe(nil)); end
  def move(x, y); end
  def move_to(row = T.unsafe(nil), column = T.unsafe(nil)); end
  def next_line; end
  def prev_line; end
  def restore; end
  def row(n = T.unsafe(nil)); end
  def save; end
  def scroll_down; end
  def scroll_up; end
  def show; end
  def up(n = T.unsafe(nil)); end

  class << self
    def backward(n = T.unsafe(nil)); end
    def clear_char(n = T.unsafe(nil)); end
    def clear_line; end
    def clear_line_after; end
    def clear_line_before; end
    def clear_lines(n, direction = T.unsafe(nil)); end
    def clear_screen; end
    def clear_screen_down; end
    def clear_screen_up; end
    def column(n = T.unsafe(nil)); end
    def current; end
    def down(n = T.unsafe(nil)); end
    def forward(n = T.unsafe(nil)); end
    def hide; end
    def invisible(stream = T.unsafe(nil)); end
    def move(x, y); end
    def move_to(row = T.unsafe(nil), column = T.unsafe(nil)); end
    def next_line; end
    def prev_line; end
    def restore; end
    def row(n = T.unsafe(nil)); end
    def save; end
    def scroll_down; end
    def scroll_up; end
    def show; end
    def up(n = T.unsafe(nil)); end
  end
end

TTY::Cursor::CSI = T.let(T.unsafe(nil), String)
TTY::Cursor::DEC_RST = T.let(T.unsafe(nil), String)
TTY::Cursor::DEC_SET = T.let(T.unsafe(nil), String)
TTY::Cursor::DEC_TCEM = T.let(T.unsafe(nil), String)
TTY::Cursor::ESC = T.let(T.unsafe(nil), String)
TTY::Cursor::VERSION = T.let(T.unsafe(nil), String)
