# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-logger` gem.
# Please instead update this file by running `bin/tapioca gem tty-logger`.


module TTY; end

class TTY::Logger
  include ::TTY::Logger::Levels

  def initialize(output: T.unsafe(nil), fields: T.unsafe(nil)); end

  def <<(*msg); end
  def add_handler(handler, **options); end
  def add_type(name, log_level); end
  def coerce_handler(name); end
  def configure; end
  def copy(new_fields); end
  def copy_error(error, message, backtrace = T.unsafe(nil)); end
  def debug(*msg, &block); end
  def error(*msg, &block); end
  def fatal(*msg, &block); end
  def filter(*objects); end
  def info(*msg, &block); end
  def log(current_level, *msg); end
  def log?(level, other_level); end
  def log_at(tmp_level, &block); end
  def raise_handler_error; end
  def remove_handler(handler); end
  def success(*msg, &block); end
  def swap_filtered(obj); end
  def wait(*msg, &block); end
  def warn(*msg, &block); end
  def write(*msg); end

  class << self
    def config; end
    def configure; end
    def define_level(name, log_level = T.unsafe(nil)); end
  end
end

class TTY::Logger::Config
  def initialize(**options); end

  def date_format; end
  def date_format=(_arg0); end
  def filters; end
  def filters=(_arg0); end
  def formatter; end
  def formatter=(_arg0); end
  def handlers; end
  def handlers=(_arg0); end
  def level; end
  def level=(_arg0); end
  def max_bytes; end
  def max_bytes=(_arg0); end
  def max_depth; end
  def max_depth=(_arg0); end
  def metadata; end
  def metadata=(_arg0); end
  def output; end
  def output=(_arg0); end
  def time_format; end
  def time_format=(_arg0); end
  def to_h; end
  def to_proc; end
  def types; end
  def types=(_arg0); end
end

TTY::Logger::Config::FILTERED = T.let(T.unsafe(nil), String)

class TTY::Logger::Config::FiltersProvider
  def initialize; end

  def data; end
  def data=(_arg0); end
  def mask; end
  def mask=(_arg0); end
  def message; end
  def message=(_arg0); end
  def to_h; end
  def to_s; end
end

class TTY::Logger::DataFilter
  def initialize(filters = T.unsafe(nil), mask: T.unsafe(nil)); end

  def compiled_filters; end
  def filter(obj); end
  def filters; end
  def mask; end

  private

  def compile(filters); end
  def filter_arr(key, obj, composite); end
  def filter_obj(_key, obj, composite); end
  def filter_val(key, val, composite = T.unsafe(nil)); end
  def filtered?(key, composite); end
end

TTY::Logger::DataFilter::DOT = T.let(T.unsafe(nil), String)
TTY::Logger::DataFilter::FILTERED = T.let(T.unsafe(nil), String)
class TTY::Logger::Error < ::StandardError; end

class TTY::Logger::Event
  def initialize(message, fields = T.unsafe(nil), metadata = T.unsafe(nil)); end

  def backtrace; end
  def fields; end
  def message; end
  def metadata; end

  private

  def evaluate_message; end
end

module TTY::Logger::Formatters; end

class TTY::Logger::Formatters::JSON
  def dump(obj, max_bytes: T.unsafe(nil), max_depth: T.unsafe(nil)); end

  private

  def dump_val(val, depth); end
  def enc_arr(obj, depth); end
  def enc_obj(obj, depth); end
end

TTY::Logger::Formatters::JSON::ELLIPSIS = T.let(T.unsafe(nil), String)

class TTY::Logger::Formatters::Text
  def dump(obj, max_bytes: T.unsafe(nil), max_depth: T.unsafe(nil)); end

  private

  def dump_key(key); end
  def dump_val(val, depth); end
  def enc_arr(array, depth); end
  def enc_cpx(val); end
  def enc_float(val); end
  def enc_num(val); end
  def enc_obj(obj, depth); end
  def enc_str(str); end
  def enc_time(time); end
end

TTY::Logger::Formatters::Text::ELLIPSIS = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::ESCAPE_DOUBLE_QUOTE = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::ESCAPE_STR_REGEX = T.let(T.unsafe(nil), Regexp)
TTY::Logger::Formatters::Text::LBRACE = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::LBRACKET = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::LITERAL_FALSE = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::LITERAL_NIL = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::LITERAL_TRUE = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::LPAREN = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::NUM_REGEX = T.let(T.unsafe(nil), Regexp)
TTY::Logger::Formatters::Text::RBRACE = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::RBRACKET = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::RPAREN = T.let(T.unsafe(nil), String)
TTY::Logger::Formatters::Text::SINGLE_QUOTE_REGEX = T.let(T.unsafe(nil), Regexp)
TTY::Logger::Formatters::Text::SPACE = T.let(T.unsafe(nil), String)
module TTY::Logger::Handlers; end

module TTY::Logger::Handlers::Base
  def coerce_formatter(name); end
  def format_filepath(event); end
  def log_at(tmp_level); end
  def metadata; end
  def raise_formatter_error(name); end
end

class TTY::Logger::Handlers::Console
  include ::TTY::Logger::Handlers::Base

  def initialize(output: T.unsafe(nil), formatter: T.unsafe(nil), config: T.unsafe(nil), level: T.unsafe(nil), styles: T.unsafe(nil), enable_color: T.unsafe(nil), message_format: T.unsafe(nil)); end

  def call(event); end
  def config; end
  def level; end
  def message_format; end
  def output; end

  private

  def configure_color(style); end
  def configure_styles(event); end
  def format_backtrace(event); end
end

TTY::Logger::Handlers::Console::ARROW = T.let(T.unsafe(nil), String)
TTY::Logger::Handlers::Console::COLOR_PATTERNS = T.let(T.unsafe(nil), Hash)
TTY::Logger::Handlers::Console::JSON_REGEXP = T.let(T.unsafe(nil), Regexp)
TTY::Logger::Handlers::Console::STYLES = T.let(T.unsafe(nil), Hash)
TTY::Logger::Handlers::Console::TEXT_REGEXP = T.let(T.unsafe(nil), Regexp)

class TTY::Logger::Handlers::Null
  def initialize(*_arg0); end

  def call(*_arg0); end
end

class TTY::Logger::Handlers::Stream
  include ::TTY::Logger::Handlers::Base

  def initialize(output: T.unsafe(nil), formatter: T.unsafe(nil), config: T.unsafe(nil), level: T.unsafe(nil)); end

  def call(event); end
  def config; end
  def level; end
  def output; end
end

TTY::Logger::LOG_TYPES = T.let(T.unsafe(nil), Hash)

module TTY::Logger::Levels
  def compare_levels(left, right); end
  def level_names; end
  def level_to_number(level); end
  def number_to_level(number); end
end

TTY::Logger::Levels::DEBUG_LEVEL = T.let(T.unsafe(nil), Integer)
TTY::Logger::Levels::ERROR_LEVEL = T.let(T.unsafe(nil), Integer)
TTY::Logger::Levels::FATAL_LEVEL = T.let(T.unsafe(nil), Integer)
TTY::Logger::Levels::INFO_LEVEL = T.let(T.unsafe(nil), Integer)
TTY::Logger::Levels::LEVEL_NAMES = T.let(T.unsafe(nil), Hash)
TTY::Logger::Levels::WARN_LEVEL = T.let(T.unsafe(nil), Integer)
TTY::Logger::VERSION = T.let(T.unsafe(nil), String)
