# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-screen` gem.
# Please instead update this file by running `bin/tapioca gem tty-screen`.


module TTY; end

module TTY::Screen
  private

  def cols; end
  def columns; end
  def command_exist?(command); end
  def height; end
  def ioctl?(control, buf); end
  def jruby?; end
  def lines; end
  def nonzero_column?(column); end
  def rows; end
  def run_command(*args); end
  def size(verbose: T.unsafe(nil)); end
  def size_from_ansicon; end
  def size_from_default; end
  def size_from_env; end
  def size_from_io_console(verbose: T.unsafe(nil)); end
  def size_from_ioctl; end
  def size_from_java(verbose: T.unsafe(nil)); end
  def size_from_readline(verbose: T.unsafe(nil)); end
  def size_from_stty; end
  def size_from_tput; end
  def size_from_win_api(verbose: T.unsafe(nil)); end
  def width; end
  def windows?; end

  class << self
    def cols; end
    def columns; end
    def env; end
    def env=(_arg0); end
    def height; end
    def ioctl?(control, buf); end
    def jruby?; end
    def lines; end
    def output; end
    def output=(_arg0); end
    def private_module_function(name); end
    def rows; end
    def size(verbose: T.unsafe(nil)); end
    def size_from_ansicon; end
    def size_from_default; end
    def size_from_env; end
    def size_from_io_console(verbose: T.unsafe(nil)); end
    def size_from_ioctl; end
    def size_from_java(verbose: T.unsafe(nil)); end
    def size_from_readline(verbose: T.unsafe(nil)); end
    def size_from_stty; end
    def size_from_tput; end
    def size_from_win_api(verbose: T.unsafe(nil)); end
    def width; end
    def windows?; end

    private

    def command_exist?(command); end
    def nonzero_column?(column); end
    def run_command(*args); end
  end
end

TTY::Screen::DEFAULT_SIZE = T.let(T.unsafe(nil), Array)
TTY::Screen::RUBY_CONFIG = T.let(T.unsafe(nil), Hash)
TTY::Screen::TIOCGWINSZ = T.let(T.unsafe(nil), Integer)
TTY::Screen::TIOCGWINSZ_BUF_FMT = T.let(T.unsafe(nil), String)
TTY::Screen::TIOCGWINSZ_BUF_LEN = T.let(T.unsafe(nil), Integer)
TTY::Screen::TIOCGWINSZ_PPC = T.let(T.unsafe(nil), Integer)
TTY::Screen::TIOCGWINSZ_SOL = T.let(T.unsafe(nil), Integer)
TTY::Screen::VERSION = T.let(T.unsafe(nil), String)
