# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-progressbar` gem.
# Please instead update this file by running `bin/tapioca gem tty-progressbar`.


module TTY; end

class TTY::ProgressBar
  include ::MonitorMixin
  extend ::Forwardable

  def initialize(format, options = T.unsafe(nil)); end

  def advance(progress = T.unsafe(nil), tokens = T.unsafe(nil)); end
  def attach_to(multibar); end
  def bar_format(*args, **_arg1, &block); end
  def clear(*args, **_arg1, &block); end
  def clear_head(*args, **_arg1, &block); end
  def clear_line; end
  def complete(*args, **_arg1, &block); end
  def complete?; end
  def configure; end
  def current; end
  def current=(value); end
  def done?; end
  def elapsed_time(*args, **_arg1, &block); end
  def finish; end
  def format; end
  def format=(_arg0); end
  def frequency(*args, **_arg1, &block); end
  def head(*args, **_arg1, &block); end
  def hide_cursor(*args, **_arg1, &block); end
  def incomplete(*args, **_arg1, &block); end
  def indeterminate?; end
  def inset(*args, **_arg1, &block); end
  def inspect; end
  def interval(*args, **_arg1, &block); end
  def iterate(collection, progress = T.unsafe(nil), &block); end
  def log(message); end
  def mean_rate(*args, **_arg1, &block); end
  def move_to_row; end
  def on(name, &callback); end
  def output(*args, **_arg1, &block); end
  def pause; end
  def paused?; end
  def rate(*args, **_arg1, &block); end
  def ratio; end
  def ratio=(value); end
  def render; end
  def reset; end
  def resize(new_width = T.unsafe(nil)); end
  def resume; end
  def row; end
  def start; end
  def start_time(*args, **_arg1, &block); end
  def stop; end
  def stopped?; end
  def to_s; end
  def total(*args, **_arg1, &block); end
  def unknown(*args, **_arg1, &block); end
  def update(options = T.unsafe(nil)); end
  def use(formatter_class); end
  def width(*args, **_arg1, &block); end
  def width=(*args, **_arg1, &block); end
  def write(data, clear_first = T.unsafe(nil)); end

  private

  def emit(name, *args); end
  def padout(message); end
  def tty?; end

  class << self
    def display_columns(value); end
    def max_columns; end
  end
end

class TTY::ProgressBar::BarFormatter
  def call(value); end

  private

  def format_determinate(value, width); end
  def format_indeterminate(value, width); end
end

class TTY::ProgressBar::ByteFormatter
  def call(value); end
end

class TTY::ProgressBar::ByteRateFormatter
  def call(value); end
end

TTY::ProgressBar::CURSOR_LOCK = T.let(T.unsafe(nil), Monitor)

class TTY::ProgressBar::Configuration
  include ::TTY::ProgressBar::Formats

  def initialize(options); end

  def bar_format; end
  def bar_format=(_arg0); end
  def clear; end
  def clear=(_arg0); end
  def clear_head; end
  def clear_head=(_arg0); end
  def complete; end
  def complete=(value); end
  def frequency; end
  def frequency=(_arg0); end
  def head; end
  def head=(_arg0); end
  def hide_cursor; end
  def hide_cursor=(_arg0); end
  def incomplete; end
  def incomplete=(value); end
  def inset; end
  def inset=(_arg0); end
  def interval; end
  def interval=(_arg0); end
  def output; end
  def output=(_arg0); end
  def total; end
  def total=(value); end
  def unknown; end
  def unknown=(value); end
  def width; end
  def width=(_arg0); end

  private

  def fetch_char(name, property); end
  def raise_if_empty(name, value); end
end

module TTY::ProgressBar::Converter
  private

  def to_bytes(value, decimals: T.unsafe(nil), separator: T.unsafe(nil), unit_separator: T.unsafe(nil)); end
  def to_seconds(seconds, precision: T.unsafe(nil)); end
  def to_time(seconds); end

  class << self
    def to_bytes(value, decimals: T.unsafe(nil), separator: T.unsafe(nil), unit_separator: T.unsafe(nil)); end
    def to_seconds(seconds, precision: T.unsafe(nil)); end
    def to_time(seconds); end
  end
end

TTY::ProgressBar::Converter::BYTE_UNITS = T.let(T.unsafe(nil), Array)
TTY::ProgressBar::Converter::HOURSECONDS = T.let(T.unsafe(nil), Integer)

class TTY::ProgressBar::CurrentFormatter
  def call(value); end
end

TTY::ProgressBar::ECMA_CSI = T.let(T.unsafe(nil), String)

class TTY::ProgressBar::ElapsedFormatter
  def call(value); end
end

class TTY::ProgressBar::EstimatedFormatter
  def call(value); end
end

class TTY::ProgressBar::EstimatedTimeFormatter
  def call(value); end
end

module TTY::ProgressBar::Formats; end
TTY::ProgressBar::Formats::FORMATS = T.let(T.unsafe(nil), Hash)

class TTY::ProgressBar::Formatter < ::Module
  def initialize(token_match); end

  class << self
    def [](token_match); end
  end
end

class TTY::ProgressBar::Formatters
  extend ::Forwardable

  def initialize(pipeline = T.unsafe(nil)); end

  def decorate(*args, **_arg1, &block); end
  def load(progress); end
  def use(*args, **_arg1, &block); end
end

class TTY::ProgressBar::MeanByteFormatter
  def call(value); end
end

class TTY::ProgressBar::MeanRateFormatter
  def call(value); end
end

class TTY::ProgressBar::Meter
  def initialize(interval); end

  def avg_rate; end
  def clear; end
  def mean_rate; end
  def prune_samples(at); end
  def rate; end
  def rates; end
  def sample(at, value); end
  def save_rate(at); end
  def start; end
end

class TTY::ProgressBar::Multi
  include ::Enumerable
  include ::MonitorMixin
  extend ::Forwardable

  def initialize(*args); end

  def [](*args, **_arg1, &block); end
  def complete?; end
  def current; end
  def done?; end
  def each(*args, **_arg1, &block); end
  def empty?(*args, **_arg1, &block); end
  def finish; end
  def length(*args, **_arg1, &block); end
  def line_inset(bar); end
  def next_row; end
  def observe(bar); end
  def on(name, &callback); end
  def pause; end
  def paused?; end
  def progress_handler; end
  def register(format, options = T.unsafe(nil)); end
  def resume; end
  def rows; end
  def start; end
  def stop; end
  def stopped?; end
  def top_bar; end
  def total; end
  def width(*args, **_arg1, &block); end
  def width=(*args, **_arg1, &block); end

  private

  def emit(name, *args); end
end

TTY::ProgressBar::Multi::DEFAULT_INSET = T.let(T.unsafe(nil), Hash)
TTY::ProgressBar::NEWLINE = T.let(T.unsafe(nil), String)

class TTY::ProgressBar::PercentFormatter
  def call(value); end
end

class TTY::ProgressBar::Pipeline
  include ::Enumerable

  def initialize(formatters = T.unsafe(nil)); end

  def decorate(tokenized); end
  def each(&block); end
  def use(formatter); end

  protected

  def formatters; end
end

class TTY::ProgressBar::RateFormatter
  def call(value); end
end

class TTY::ProgressBar::Timer
  def initialize; end

  def elapsed_time; end
  def elapsed_until_now; end
  def reset; end
  def running?; end
  def start; end
  def start_time; end
  def stop; end
end

class TTY::ProgressBar::TotalByteFormatter
  def call(value); end
end

class TTY::ProgressBar::TotalFormatter
  def call(value); end
end

TTY::ProgressBar::VERSION = T.let(T.unsafe(nil), String)
